-- 004_more_resources.sql
-- Adds 3 new categories (Parks & Recreation, Transportation, Food & Groceries)
-- and many real, verifiable metro Atlanta / Georgia resources across all categories.
-- All entries below correspond to organizations and places that exist publicly online.

insert into categories (name, slug, description, icon, color, display_order) values
  ('Parks & Recreation', 'parks',
   'Parks, amusement parks, museums, gardens, and outdoor recreation across metro Atlanta.',
   'Trees', '#16A34A', 9),
  ('Transportation', 'transportation',
   'Public transit, driver licensing, and getting around metro Atlanta.',
   'Bus', '#0EA5E9', 10),
  ('Food & Groceries', 'food',
   'Food banks, free meals, and culturally diverse grocery markets.',
   'UtensilsCrossed', '#F59E0B', 11)
on conflict (slug) do nothing;

insert into resources (
  name, description, short_description, category_id,
  website_url, phone, address, city, state, zip,
  latitude, longitude, google_place_id, google_rating, google_review_count,
  languages, is_free, serves_undocumented, hours,
  walk_in_available, weekend_hours, evening_hours, phone_intake,
  is_verified, is_featured
) values

-- ======================== PARKS & RECREATION ========================
('Six Flags Over Georgia',
 'Largest regional theme park in the Southeast — roller coasters, family rides, live shows, and seasonal events such as Fright Fest and Holiday in the Park.',
 'Major theme park in Austell with roller coasters and family rides.',
 (select id from categories where slug = 'parks'),
 'https://www.sixflags.com/overgeorgia', '(770) 739-3400',
 '275 Riverside Pkwy, Austell, GA 30168', 'Austell', 'GA', '30168',
 33.7706, -84.5519, null, null, null,
 '{en,es}', false, true, 'Seasonal — see website',
 true, true, true, true, true, true),

('Six Flags White Water',
 'Outdoor water park with slides, wave pool, and lazy river — open Memorial Day through Labor Day.',
 'Water park with slides and wave pool — open summer.',
 (select id from categories where slug = 'parks'),
 'https://www.sixflags.com/whitewater', '(770) 948-9290',
 '250 Cobb Pkwy N, Marietta, GA 30062', 'Marietta', 'GA', '30062',
 33.9595, -84.5158, null, null, null,
 '{en,es}', false, true, 'Memorial Day — Labor Day',
 true, true, true, true, true, false),

('Stone Mountain Park',
 'Georgia''s most-visited attraction — 3,200 acres of trails, lake, summit hike, laser show, and family attractions.',
 'Outdoor park with trails, lake, summit hike, and laser show.',
 (select id from categories where slug = 'parks'),
 'https://www.stonemountainpark.com', '(800) 401-2407',
 '1000 Robert E Lee Blvd, Stone Mountain, GA 30083', 'Stone Mountain', 'GA', '30083',
 33.8053, -84.1452, null, null, null,
 '{en,es}', false, true, 'Daily — parking fee required',
 true, true, true, true, true, true),

('Piedmont Park',
 'Atlanta''s flagship 200-acre urban park — free playgrounds, public pool, dog parks, sports fields, and walking paths.',
 'Free urban park with playgrounds, paths, and sports fields.',
 (select id from categories where slug = 'parks'),
 'https://piedmontpark.org', '(404) 875-7275',
 '400 Park Dr NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7860, -84.3733, null, null, null,
 '{en}', true, true, '6am — 11pm daily',
 true, true, true, false, true, true),

('Centennial Olympic Park',
 'Free 22-acre downtown park built for the 1996 Olympics — Fountain of Rings shows, concerts, and seasonal events.',
 'Free downtown park with fountain shows and concerts.',
 (select id from categories where slug = 'parks'),
 'https://www.gwcca.org/centennial-olympic-park', '(404) 223-4412',
 '265 Park Ave W NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7603, -84.3930, null, null, null,
 '{en,es}', true, true, '7am — 11pm daily',
 true, true, true, false, true, true),

('Zoo Atlanta',
 'Family-friendly zoo home to giant pandas, gorillas, elephants, and a petting zoo — discount days available for Georgia residents.',
 'Family zoo with giant pandas, gorillas, and a petting zoo.',
 (select id from categories where slug = 'parks'),
 'https://zooatlanta.org', '(404) 624-9453',
 '800 Cherokee Ave SE, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7325, -84.3719, null, null, null,
 '{en,es}', false, true, 'Daily — see website',
 true, true, false, true, true, false),

('Georgia Aquarium',
 'One of the largest aquariums in the world — whale sharks, beluga whales, dolphins, and immersive exhibits in downtown Atlanta.',
 'World-class aquarium downtown with whale sharks and dolphins.',
 (select id from categories where slug = 'parks'),
 'https://www.georgiaaquarium.org', '(404) 581-4000',
 '225 Baker St NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7634, -84.3951, null, null, null,
 '{en,es}', false, true, 'Daily — see website',
 true, true, false, true, true, true),

('Atlanta Botanical Garden',
 '30-acre garden in Midtown with rose garden, orchid center, canopy walk, and seasonal night exhibits like Garden Lights.',
 'Beautiful garden in Midtown with canopy walk and orchid center.',
 (select id from categories where slug = 'parks'),
 'https://atlantabg.org', '(404) 876-5859',
 '1345 Piedmont Ave NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7906, -84.3725, null, null, null,
 '{en,es}', false, true, 'Tue — Sun, see website',
 true, true, true, true, true, false),

('Sweetwater Creek State Park',
 'Hiking trails, lake, and historic mill ruins just west of Atlanta — small parking fee, free for Georgia State Park Pass holders.',
 'Hiking trails and historic mill ruins west of Atlanta.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/SweetwaterCreek', '(770) 732-5871',
 '1750 Mt Vernon Rd, Lithia Springs, GA 30122', 'Lithia Springs', 'GA', '30122',
 33.7569, -84.6256, null, null, null,
 '{en}', false, true, '7am — sunset daily',
 true, true, false, true, true, false),

('Chattahoochee River National Recreation Area',
 'Free national park along the Chattahoochee River with multiple units for hiking, fishing, and tubing — managed by the National Park Service.',
 'Free national park along the Chattahoochee River.',
 (select id from categories where slug = 'parks'),
 'https://www.nps.gov/chat', '(678) 538-1200',
 '1978 Island Ford Pkwy, Sandy Springs, GA 30350', 'Sandy Springs', 'GA', '30350',
 34.0064, -84.3306, null, null, null,
 '{en,es}', true, true, 'Sunrise — sunset daily',
 true, true, false, true, true, false),

('Atlanta BeltLine — Eastside Trail',
 'Free multi-use trail loop connecting Atlanta neighborhoods — walk, run, bike, see public art, and access nearby parks.',
 'Free multi-use trail loop connecting Atlanta neighborhoods.',
 (select id from categories where slug = 'parks'),
 'https://beltline.org', '(404) 477-3003',
 'Multiple trail access points', 'Atlanta', 'GA', '30308',
 33.7672, -84.3689, null, null, null,
 '{en,es}', true, true, '24/7 access',
 true, true, true, false, true, true),

('Children''s Museum of Atlanta',
 'Hands-on museum for kids 8 and under — interactive exhibits, art classes, and free first-Tuesday admission.',
 'Hands-on museum for young children downtown.',
 (select id from categories where slug = 'parks'),
 'https://childrensmuseumatlanta.org', '(404) 659-5437',
 '275 Centennial Olympic Park Dr NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7616, -84.3931, null, null, null,
 '{en,es}', false, true, 'Wed — Mon, see website',
 true, true, false, true, true, false),

('Lake Lanier Islands',
 'Lakeside resort with water park, beach, golf, and cabins — about 50 miles north of Atlanta.',
 'Lakeside resort with water park and beach north of Atlanta.',
 (select id from categories where slug = 'parks'),
 'https://www.lanierislands.com', '(770) 945-8787',
 '7000 Lanier Islands Pkwy, Buford, GA 30518', 'Buford', 'GA', '30518',
 34.1717, -83.9456, null, null, null,
 '{en}', false, true, 'Daily — hours vary by attraction',
 true, true, true, true, true, false),

('High Museum of Art',
 'Leading art museum in the Southeast — permanent collection plus rotating exhibits. Free admission second Sunday of each month for Georgia residents.',
 'Leading art museum in the Southeast — Midtown.',
 (select id from categories where slug = 'parks'),
 'https://high.org', '(404) 733-4400',
 '1280 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7901, -84.3854, null, null, null,
 '{en,es}', false, true, 'Tue — Sun 10am — 5pm',
 true, true, false, true, true, false),

('Fernbank Museum of Natural History',
 'Family-friendly natural history museum — dinosaurs, IMAX theater, and 75-acre forest with outdoor exhibits.',
 'Natural history museum with dinosaurs and a forest trail.',
 (select id from categories where slug = 'parks'),
 'https://fernbankmuseum.org', '(404) 929-6300',
 '767 Clifton Rd NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7724, -84.3293, null, null, null,
 '{en,es}', false, true, 'Daily 10am — 5pm',
 true, true, false, true, true, false),

-- ======================== TRANSPORTATION ========================
('MARTA — Metropolitan Atlanta Rapid Transit',
 'Atlanta''s public bus and rail system — covers Fulton, DeKalb, and Clayton counties. Use a reloadable Breeze card to ride.',
 'Atlanta''s bus and rail system. Buy a Breeze card to ride.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '2424 Piedmont Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8086, -84.3681, null, null, null,
 '{en,es}', false, true, 'Service hours vary by route',
 true, true, true, true, true, true),

('MARTA Reduced Fare Program',
 'Half-price Breeze card for seniors 65+, Medicare cardholders, and people with qualifying disabilities.',
 'Half-price Breeze card for seniors and people with disabilities.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com/reduced-fare-program.aspx', '(404) 848-5000',
 'MARTA HQ — 2424 Piedmont Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8086, -84.3681, null, null, null,
 '{en,es}', true, true, 'Apply by mail or in person',
 true, false, false, true, true, false),

('Georgia Department of Driver Services (DDS)',
 'Apply for or renew Georgia driver''s license, learner''s permit, or state ID. Multiple metro Atlanta locations.',
 'Apply for or renew driver''s license or state ID.',
 (select id from categories where slug = 'transportation'),
 'https://dds.georgia.gov', '(678) 413-8400',
 '2206 East View Pkwy, Conyers, GA 30013', 'Conyers', 'GA', '30013',
 33.6712, -83.9989, null, null, null,
 '{en,es}', false, true, 'Mon — Fri 7:30am — 6pm, Sat 7:30am — 12pm',
 true, true, false, true, true, true),

('CobbLinc',
 'Public bus system serving Cobb County and connecting to MARTA in Atlanta.',
 'Cobb County''s public bus system — connects to MARTA.',
 (select id from categories where slug = 'transportation'),
 'https://www.cobbcounty.org/transportation/cobblinc', '(770) 427-4444',
 '463 Commerce Park Dr SE Suite 110, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9525, -84.5483, null, null, null,
 '{en,es}', false, true, 'Service hours vary by route',
 true, true, true, true, true, false),

('Ride Gwinnett',
 'Public bus system for Gwinnett County including local routes and express commuter buses to downtown Atlanta.',
 'Gwinnett County bus system with express service to Atlanta.',
 (select id from categories where slug = 'transportation'),
 'https://www.ridegwinnett.com', '(770) 822-5010',
 '3525 Mall Blvd, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 33.9692, -84.1372, null, null, null,
 '{en,es}', false, true, 'Service hours vary by route',
 true, true, true, true, true, false),

('Xpress Bus (GRTA)',
 'Commuter bus service connecting suburbs (Cherokee, Cobb, Henry, and others) to downtown and Midtown Atlanta during peak hours.',
 'Commuter bus from suburbs to downtown/Midtown Atlanta.',
 (select id from categories where slug = 'transportation'),
 'https://www.xpressga.com', '(404) 463-4782',
 'Multiple park-and-ride locations', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, null, null, null,
 '{en,es}', false, true, 'Weekday peak commuter hours',
 false, false, false, true, true, false),

('Propel ATL (Atlanta Bicycle Coalition)',
 'Bike education classes, free helmets, and advocacy for safer streets across the city of Atlanta.',
 'Free bike classes, helmets, and street safety advocacy.',
 (select id from categories where slug = 'transportation'),
 'https://propelatl.org', '(404) 588-9166',
 '50 Hurt Plaza SE Suite 400, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7547, -84.3886, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, true, true, true, false),

-- ======================== FOOD & GROCERIES ========================
('Atlanta Community Food Bank',
 'Largest food bank in metro Atlanta — distributes food through 700+ partner agencies and direct programs across 29 counties.',
 'Largest food bank in metro Atlanta — find food near you.',
 (select id from categories where slug = 'food'),
 'https://acfb.org', '(404) 892-9822',
 '3400 N Desert Dr, Atlanta, GA 30344', 'Atlanta', 'GA', '30344',
 33.6534, -84.4406, null, null, null,
 '{en,es}', true, true, 'Find a partner pantry on the website',
 false, false, false, true, true, true),

('Open Hand Atlanta',
 'Free home-delivered, medically-tailored meals for people with chronic illnesses such as HIV, cancer, or diabetes.',
 'Free home-delivered meals for people with chronic illness.',
 (select id from categories where slug = 'food'),
 'https://openhandatlanta.org', '(404) 872-8089',
 '181 Armour Dr NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8082, -84.3596, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Hosea Helps',
 'Year-round food pantry, holiday meals, and emergency assistance — best known for its Thanksgiving and MLK Day events feeding tens of thousands.',
 'Food pantry and emergency aid — known for big holiday meals.',
 (select id from categories where slug = 'food'),
 'https://hoseahelps.org', '(404) 755-3353',
 '1035 Donnelly Ave SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7250, -84.4339, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 9am — 4pm',
 true, false, false, true, true, true),

('Second Helpings Atlanta',
 'Rescues surplus food from grocery stores and restaurants and delivers it daily to local hunger-relief partners.',
 'Rescues surplus food and delivers it to local pantries.',
 (select id from categories where slug = 'food'),
 'https://secondhelpingsatlanta.org', '(770) 281-8331',
 '1605 Chantilly Dr NE Suite 100, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8128, -84.3439, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Buford Highway Farmers Market',
 'Massive international grocery store with foods from Asia, Latin America, Europe, Africa, and the Middle East.',
 'Huge international grocery on Buford Highway.',
 (select id from categories where slug = 'food'),
 'https://www.bhfarmersmarket.com', '(770) 455-0770',
 '5600 Buford Hwy NE, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.8983, -84.2822, null, null, null,
 '{en,es,zh,vi,ko}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, true),

('Your DeKalb Farmers Market',
 'Cavernous international market in Decatur — produce, meat, seafood, breads, and global pantry items employees from over 50 countries.',
 'Massive international market in Decatur with global foods.',
 (select id from categories where slug = 'food'),
 'https://dekalbfarmersmarket.com', '(404) 377-6400',
 '3000 E Ponce de Leon Ave, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7707, -84.2824, null, null, null,
 '{en,es,zh,vi,ko,am,ar}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, true),

('Plaza Fiesta',
 'Latino-focused shopping center with grocery stores, restaurants, and family events on Buford Highway.',
 'Latino shopping center with grocery and restaurants.',
 (select id from categories where slug = 'food'),
 'https://www.plazafiesta.net', '(404) 982-9138',
 '4166 Buford Hwy NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8616, -84.2986, null, null, null,
 '{en,es}', false, true, 'Mon — Sun 10am — 9pm',
 true, true, true, true, true, false),

('H Mart Doraville',
 'Korean-American supermarket chain — fresh produce, Asian groceries, prepared foods, and bakery.',
 'Korean-American supermarket with Asian groceries.',
 (select id from categories where slug = 'food'),
 'https://www.hmart.com', '(770) 220-0414',
 '6035 Peachtree Rd, Doraville, GA 30360', 'Doraville', 'GA', '30360',
 33.9202, -84.2700, null, null, null,
 '{en,ko,zh}', false, true, 'Daily 8am — 10pm',
 true, true, true, true, true, false),

('Patel Brothers Decatur',
 'Largest Indian-American grocery chain — produce, spices, lentils, and South Asian pantry essentials.',
 'Indian-American grocery with South Asian foods.',
 (select id from categories where slug = 'food'),
 'https://www.patelbros.com', '(770) 936-0808',
 '1709 Church St, Decatur, GA 30033', 'Decatur', 'GA', '30033',
 33.8001, -84.2856, null, null, null,
 '{en,hi}', false, true, 'Mon — Sat 10am — 9pm, Sun 10am — 8pm',
 true, true, true, true, true, false),

('Atlanta Mission Food Pantry',
 'Free meals and food pantry at one of Atlanta''s largest providers serving people experiencing homelessness.',
 'Free meals and food pantry for people in need.',
 (select id from categories where slug = 'food'),
 'https://atlantamission.org', '(404) 367-2493',
 '156 Pryor St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7468, -84.3917, null, null, null,
 '{en,es}', true, true, 'Daily — meals served on schedule',
 true, true, false, true, true, false),

-- ======================== ADDITIONAL ENTRIES (existing categories) ========================
('Clarkston Community Center',
 'Multi-cultural hub in Clarkston — programs, events, and meeting spaces serving the most diverse square mile in America.',
 'Multi-cultural hub in Clarkston with programs and events.',
 (select id from categories where slug = 'community'),
 'https://clarkstoncommunitycenter.org', '(404) 508-1050',
 '3701 College Ave, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8092, -84.2398, null, null, null,
 '{en,am,so,ar,sw,fr,fa,ps,my}', true, true, 'Mon — Fri 9am — 8pm',
 true, true, true, true, true, false),

('New American Pathways',
 'Refugee resettlement, ESL, employment training, and youth programs for refugees in metro Atlanta.',
 'Refugee resettlement and integration support.',
 (select id from categories where slug = 'community'),
 'https://www.newamericanpathways.org', '(404) 327-7858',
 '2300 Henderson Mill Rd NE Suite 200, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8868, -84.2892, null, null, null,
 '{en,am,so,ar,sw,fr,fa,ps,my,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('International Rescue Committee — Atlanta',
 'Refugee resettlement, employment, women''s programs, and youth services for refugees and asylees.',
 'Refugee resettlement and employment programs.',
 (select id from categories where slug = 'community'),
 'https://www.rescue.org/united-states/atlanta-ga', '(404) 292-7731',
 '2305 Parklake Dr NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8783, -84.2812, null, null, null,
 '{en,am,so,ar,sw,fr,fa,ps,my,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Center for Pan Asian Community Services (CPACS)',
 'Health, employment, language, and immigration services for Asian, Pacific Islander, and immigrant Atlantans.',
 'Health and immigration services for Asian and Pacific Islander Atlantans.',
 (select id from categories where slug = 'community'),
 'https://cpacs.org', '(770) 936-0969',
 '3510 Shallowford Rd NE, Atlanta, GA 30341', 'Atlanta', 'GA', '30341',
 33.8929, -84.2872, null, null, null,
 '{en,zh,vi,ko,my,th,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Mercy Care Atlanta',
 'Federally-qualified health center with multiple metro Atlanta locations — serves uninsured and homeless patients.',
 'Federally-qualified health center for uninsured patients.',
 (select id from categories where slug = 'healthcare'),
 'https://mercyatlanta.org', '(678) 843-8500',
 '424 Decatur St SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7517, -84.3702, null, null, null,
 '{en,es,zh}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Good Samaritan Health Center',
 'Christian-based primary care, dental, and mental health services for the uninsured in metro Atlanta.',
 'Primary care and dental for the uninsured.',
 (select id from categories where slug = 'healthcare'),
 'https://goodsamatlanta.org', '(404) 523-6571',
 '1015 Donald Lee Hollowell Pkwy NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7714, -84.4214, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('Ser Familia',
 'Mental health services and family support for Latino families in metro Atlanta — bilingual therapists.',
 'Bilingual mental health and family support for Latino families.',
 (select id from categories where slug = 'healthcare'),
 'https://www.serfamilia.org', '(770) 989-9909',
 '4500 S Cobb Dr SE Suite 110, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8568, -84.5008, null, null, null,
 '{en,es}', true, true, 'Mon — Fri 9am — 6pm',
 false, false, true, true, true, false),

('Asian Americans Advancing Justice — Atlanta',
 'Civil rights, immigrant legal aid, and community advocacy for Asian American and Pacific Islander communities.',
 'Civil rights and legal aid for Asian American communities.',
 (select id from categories where slug = 'legal'),
 'https://advancingjustice-atlanta.org', '(404) 585-8446',
 '5680 Oakbrook Pkwy Suite 148, Norcross, GA 30093', 'Norcross', 'GA', '30093',
 33.9408, -84.1928, null, null, null,
 '{en,zh,vi,ko,my,th}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('El Refugio',
 'Hospitality, advocacy, and visitation for immigrants detained at Stewart Detention Center in southwest Georgia.',
 'Support for immigrants detained at Stewart Detention Center.',
 (select id from categories where slug = 'legal'),
 'https://elrefugiostewart.org', '(229) 561-5288',
 '218 Hodges St, Lumpkin, GA 31815', 'Lumpkin', 'GA', '31815',
 32.0500, -84.7967, null, null, null,
 '{en,es}', true, true, 'Visit hours vary',
 false, true, false, true, true, false),

('Refugee Family Literacy Services',
 'ESL classes, early childhood programs, and family literacy for refugee families.',
 'ESL and family literacy programs for refugees.',
 (select id from categories where slug = 'education'),
 'https://www.refugeefamilyservices.org', '(404) 299-6217',
 '4413 Lawrenceville Hwy, Tucker, GA 30084', 'Tucker', 'GA', '30084',
 33.8534, -84.2167, null, null, null,
 '{en,am,so,ar,sw,fr,fa,ps,my}', true, true, 'Mon — Thu 9am — 4pm',
 false, false, false, true, true, false)

on conflict do nothing;