-- 005_real_data_pass.sql
-- Two purposes:
--   1) Remove all previously-seeded google_rating / google_review_count values.
--      They were estimates, not pulled from Google. Until we wire up the Google
--      Places API to fetch live ratings, we should not display invented numbers.
--   2) Add 4 more categories (Family & Childcare, Faith & Worship, Libraries &
--      Tech, Women's Services) and ~90 more real, verifiable metro Atlanta /
--      Georgia organizations across every category. Bringing the catalog past
--      200 entries.
-- Every entry below corresponds to an organization or place that exists publicly.

-- ============================================================
-- 1. Null out all rating/review fields (no fake data anywhere)
-- ============================================================
update resources
set google_rating = null,
    google_review_count = null
where google_rating is not null or google_review_count is not null;

-- ============================================================
-- 2. New categories
-- ============================================================
insert into categories (name, slug, description, icon, color, display_order) values
  ('Family & Childcare', 'family',
   'Childcare assistance, parenting support, after-school programs, and youth mentoring.',
   'Baby', '#EC4899', 12),
  ('Faith & Worship', 'faith',
   'Mosques, churches, temples, synagogues, and gurdwaras across metro Atlanta.',
   'Church', '#A855F7', 13),
  ('Libraries & Tech', 'libraries',
   'Public libraries, free internet access, computer labs, and digital literacy.',
   'Library', '#4F46E5', 14),
  ('Women''s Services', 'womens',
   'Domestic violence support, women''s health, and women-led services.',
   'HeartHandshake', '#F43F5E', 15)
on conflict (slug) do nothing;

-- ============================================================
-- 3. New resources (real organizations)
-- ============================================================
insert into resources (
  name, description, short_description, category_id,
  website_url, phone, address, city, state, zip,
  latitude, longitude, languages, is_free, serves_undocumented, hours,
  walk_in_available, weekend_hours, evening_hours, phone_intake,
  is_verified, is_featured
) values

-- ============== FAMILY & CHILDCARE ==============
('Quality Care for Children',
 'Statewide childcare resource and referral agency — helps parents find quality childcare and access subsidies.',
 'Helps parents find quality childcare and subsidies.',
 (select id from categories where slug = 'family'),
 'https://www.qualitycareforchildren.org', '(404) 479-4200',
 '50 Executive Park S NE Suite 5025, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8252, -84.3265, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, true),

('Bright from the Start (Georgia DECAL)',
 'Georgia''s state agency for early childhood education and childcare licensing — also runs the CAPS childcare subsidy program.',
 'Georgia''s state childcare and pre-K agency.',
 (select id from categories where slug = 'family'),
 'https://www.decal.ga.gov', '(404) 656-5957',
 '2 Martin Luther King Jr Dr SE Suite 754, Atlanta, GA 30334', 'Atlanta', 'GA', '30334',
 33.7488, -84.3884, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, true),

('Sheltering Arms Early Education and Family Centers',
 'Affordable, high-quality early education and family support at multiple metro Atlanta centers.',
 'Affordable early education and family centers.',
 (select id from categories where slug = 'family'),
 'https://shelteringarmsforkids.com', '(404) 523-2767',
 '385 Centennial Olympic Park Dr NW Suite 200, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7619, -84.3946, '{en,es}', false, true, 'Mon — Fri 6:30am — 6pm',
 false, false, false, true, true, false),

('Boys & Girls Clubs of Metro Atlanta',
 'Safe after-school and summer programs at 25+ club sites — academic support, sports, arts, and mentoring.',
 'After-school clubs with mentoring, sports, and academic help.',
 (select id from categories where slug = 'family'),
 'https://www.bgcma.org', '(404) 527-7100',
 '1275 Peachtree St NE Suite 250, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7833, -84.3838, '{en,es}', false, true, 'After-school hours, summer day camp',
 false, false, true, true, true, true),

('YMCA of Metropolitan Atlanta',
 'Family wellness, childcare, day camps, and after-school programs at branches across metro Atlanta. Financial assistance available.',
 'Family Y branches with childcare, fitness, and camps.',
 (select id from categories where slug = 'family'),
 'https://ymcaatlanta.org', '(404) 588-9622',
 '101 Marietta St NW Suite 1900, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7548, -84.3942, '{en,es}', false, true, 'Hours vary by branch',
 true, true, true, true, true, true),

('Big Brothers Big Sisters of Metro Atlanta',
 'One-to-one youth mentoring program matching adult volunteers with young people across metro Atlanta.',
 'One-to-one youth mentoring program.',
 (select id from categories where slug = 'family'),
 'https://www.bbbsatl.org', '(404) 601-7000',
 '1382 Peachtree St NE Suite 100, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7867, -84.3839, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Cool Girls, Inc.',
 'Mentoring program for girls ages 8–18 in Atlanta — academic, life-skill, and self-esteem programs at school sites.',
 'Mentoring for girls ages 8–18.',
 (select id from categories where slug = 'family'),
 'https://www.coolgirls.org', '(404) 420-3475',
 '848 Edgewood Ave NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7574, -84.3650, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, true, true, true, false),

('Atlanta Speech School',
 'Comprehensive speech, hearing, language, and learning programs for children — financial aid available.',
 'Speech, hearing, and learning support for children.',
 (select id from categories where slug = 'family'),
 'https://www.atlantaspeechschool.org', '(404) 233-5332',
 '3160 Northside Pkwy NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8550, -84.4119, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('Easter Seals North Georgia',
 'Early childhood education, autism services, and family support across metro Atlanta and north Georgia.',
 'Early childhood and autism services for families.',
 (select id from categories where slug = 'family'),
 'https://www.esng.org', '(404) 943-1070',
 '5600 Roswell Rd NE Suite 250 Bldg N, Sandy Springs, GA 30342', 'Sandy Springs', 'GA', '30342',
 33.8761, -84.3839, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('Children''s Healthcare of Atlanta — Family Resource Library',
 'Free family resource libraries at all three CHOA hospitals — books, support groups, and education for families with sick or special-needs children.',
 'Free family support and resources at CHOA hospitals.',
 (select id from categories where slug = 'family'),
 'https://www.choa.org', '(404) 785-5437',
 '1405 Clifton Rd NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7951, -84.3236, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

-- ============== FAITH & WORSHIP ==============
('Atlanta Masjid of Al-Islam',
 'Historic Atlanta mosque — daily prayers, Jumu''ah service, school, and community programs.',
 'Historic Atlanta mosque with school and community programs.',
 (select id from categories where slug = 'faith'),
 'https://www.atlantamasjid.com', '(404) 378-1600',
 '560 Fayetteville Rd SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7384, -84.3494, '{en,ar}', true, true, 'Daily prayers — see schedule',
 true, true, true, true, true, false),

('Al-Farooq Masjid of Atlanta',
 'Large mosque in Midtown Atlanta — daily prayers, Jumu''ah, classes, and community services.',
 'Large mosque in Midtown Atlanta with classes and prayer.',
 (select id from categories where slug = 'faith'),
 'https://alfarooqmasjid.org', '(404) 874-7521',
 '442 14th St NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7847, -84.4011, '{en,ar,ur}', true, true, 'Daily prayers — see schedule',
 true, true, true, true, true, false),

('BAPS Shri Swaminarayan Mandir Atlanta',
 'Hindu temple in Lilburn — one of the largest traditional Hindu mandirs in North America. Free to visit.',
 'Major Hindu temple in Lilburn with daily darshan.',
 (select id from categories where slug = 'faith'),
 'https://www.baps.org/Global-Network/North-America/Atlanta.aspx', '(678) 906-2277',
 '460 Rockbridge Rd NW, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.8717, -84.1411, '{en,gu,hi}', true, true, 'Daily — see website',
 true, true, true, true, true, true),

('Hindu Temple of Atlanta',
 'Hindu temple in Riverdale — daily worship, festivals, classes, and a community kitchen.',
 'Hindu temple in Riverdale with daily worship and classes.',
 (select id from categories where slug = 'faith'),
 'https://www.hindutempleofatlanta.org', '(770) 907-7102',
 '5851 GA-85, Riverdale, GA 30274', 'Riverdale', 'GA', '30274',
 33.5701, -84.4148, '{en,hi,ta,te}', true, true, 'Daily — see website',
 true, true, true, true, true, false),

('Cathedral of Christ the King',
 'Catholic cathedral of the Archdiocese of Atlanta in Buckhead — Mass in English and Spanish, plus parish ministries.',
 'Catholic cathedral in Buckhead with English and Spanish Mass.',
 (select id from categories where slug = 'faith'),
 'https://cathedralctk.com', '(404) 233-2145',
 '2699 Peachtree Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8348, -84.3786, '{en,es}', true, true, 'Daily Mass — see schedule',
 true, true, true, true, true, false),

('Ebenezer Baptist Church',
 'Historic Black Baptist church and former pulpit of Dr. Martin Luther King Jr. — open for worship and visitor tours.',
 'Historic church — Dr. King''s former pulpit.',
 (select id from categories where slug = 'faith'),
 'https://www.ebenezeratl.org', '(404) 688-7263',
 '101 Jackson St NE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7553, -84.3727, '{en}', true, true, 'Sun service + weekday tours',
 true, true, false, true, true, true),

('The Temple',
 'Historic Reform Jewish congregation in Midtown — Shabbat services, schools, and social-justice programs.',
 'Historic Reform Jewish congregation in Midtown.',
 (select id from categories where slug = 'faith'),
 'https://www.the-temple.org', '(404) 873-1731',
 '1589 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7965, -84.3863, '{en,he}', true, true, 'Shabbat & weekly services',
 true, true, true, true, true, false),

('Congregation Beth Jacob',
 'Modern Orthodox Jewish synagogue in Toco Hills — daily minyan, Shabbat, and learning programs.',
 'Modern Orthodox synagogue in Toco Hills.',
 (select id from categories where slug = 'faith'),
 'https://bethjacobatlanta.org', '(404) 633-0551',
 '1855 Lavista Rd NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8203, -84.3162, '{en,he}', true, true, 'Daily minyan — see schedule',
 true, true, true, true, true, false),

('Holy Cross Greek Orthodox Cathedral',
 'Greek Orthodox cathedral in Atlanta — Divine Liturgy, Greek school, and community festival.',
 'Greek Orthodox cathedral with weekly Divine Liturgy.',
 (select id from categories where slug = 'faith'),
 'https://www.atlantagoc.org', '(404) 633-5870',
 '2480 Clairmont Rd NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8268, -84.3225, '{en,el}', true, true, 'Sunday liturgy + weekday services',
 true, true, false, true, true, false),

('North Avenue Presbyterian Church',
 'Historic mainline Presbyterian congregation in Midtown — worship, music, and community ministries.',
 'Historic Presbyterian church in Midtown.',
 (select id from categories where slug = 'faith'),
 'https://www.napc.org', '(404) 875-0431',
 '607 Peachtree St NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7706, -84.3853, '{en}', true, true, 'Sunday worship + weekday programs',
 true, true, false, true, true, false),

('Cascade United Methodist Church',
 'Large historic United Methodist church in southwest Atlanta — worship, schools, and community outreach.',
 'Large UMC in southwest Atlanta with outreach.',
 (select id from categories where slug = 'faith'),
 'https://www.cascadeumc.org', '(404) 691-1721',
 '3144 Cascade Rd SW, Atlanta, GA 30311', 'Atlanta', 'GA', '30311',
 33.7283, -84.4915, '{en}', true, true, 'Sunday worship + weekday programs',
 true, true, false, true, true, false),

-- ============== LIBRARIES & TECH ==============
('Atlanta-Fulton Public Library — Central Library',
 'Main downtown library — free books, computers, internet, classes, and meeting space. Get a library card with proof of address.',
 'Free books, computers, internet, and classes downtown.',
 (select id from categories where slug = 'libraries'),
 'https://afpls.org', '(404) 730-1700',
 '1 Margaret Mitchell Sq NW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7553, -84.3895, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, true),

('Auburn Avenue Research Library on African American Culture and History',
 'Specialized AFPL branch with major archives on African American history, culture, and genealogy. Free to visit.',
 'African American history and genealogy library.',
 (select id from categories where slug = 'libraries'),
 'https://afpls.org/aarl', '(404) 613-4001',
 '101 Auburn Ave NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7553, -84.3839, '{en}', true, true, 'Tue — Sat — see hours',
 true, true, false, true, true, false),

('DeKalb County Public Library — Decatur',
 'Main DeKalb library — books, computers, internet, ESL classes, and storytime in multiple languages.',
 'Main DeKalb library with computers and ESL classes.',
 (select id from categories where slug = 'libraries'),
 'https://dekalblibrary.org', '(404) 370-3070',
 '215 Sycamore St, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7748, -84.2952, '{en,es,am,so}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, true),

('Cobb County Public Library — Central',
 'Main Cobb library in Marietta — books, computers, internet, programs for kids and adults.',
 'Main Cobb County library with computers and programs.',
 (select id from categories where slug = 'libraries'),
 'https://cobbcat.org', '(770) 528-2320',
 '266 Roswell St NE, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9530, -84.5478, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Gwinnett County Public Library — Lawrenceville',
 'Major Gwinnett branch — books, computers, ESL classes, and citizenship support.',
 'Gwinnett library with ESL and citizenship support.',
 (select id from categories where slug = 'libraries'),
 'https://www.gwinnettpl.org', '(770) 822-4522',
 '1001 Lawrenceville Hwy, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9526, -83.9889, '{en,es,vi,ko,zh}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, true),

('Clayton County Library System',
 'Public library system serving Clayton County with branches in Jonesboro, Forest Park, and more.',
 'Clayton County library — books, computers, programs.',
 (select id from categories where slug = 'libraries'),
 'https://www.claytoncountypl.org', '(770) 473-3850',
 '865 Battle Creek Rd, Jonesboro, GA 30236', 'Jonesboro', 'GA', '30236',
 33.5293, -84.3573, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Per Scholas Atlanta',
 'Free 15-week tech training in IT support, cybersecurity, and software engineering for adults.',
 'Free tech training for adults — IT, cyber, software.',
 (select id from categories where slug = 'libraries'),
 'https://perscholas.org/locations/atlanta', '(404) 996-2670',
 '675 Ponce de Leon Ave NE Suite N400, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7732, -84.3672, '{en,es}', true, true, 'Cohorts run year-round',
 false, false, true, true, true, true),

('Goodwill of North Georgia — Career Center',
 'Free career and digital skills training, computer access, and job search help.',
 'Free career training and computer access.',
 (select id from categories where slug = 'libraries'),
 'https://goodwillng.org', '(404) 420-9900',
 '2201 Glenwood Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7376, -84.3458, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

-- ============== WOMEN''S SERVICES ==============
('Partnership Against Domestic Violence (PADV)',
 'Domestic violence emergency shelter, 24-hour crisis line, counseling, and legal advocacy across metro Atlanta.',
 '24/7 DV crisis line, shelter, and legal advocacy.',
 (select id from categories where slug = 'womens'),
 'https://padv.org', '(404) 873-1766',
 'Confidential locations — Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7 crisis line',
 true, true, true, true, true, true),

('Tapestri',
 'Anti-trafficking, domestic violence, and family violence services for refugee and immigrant women.',
 'DV and trafficking services for immigrant women.',
 (select id from categories where slug = 'womens'),
 'https://tapestri.org', '(404) 299-2185',
 '3939 Lavista Rd Suite E, Tucker, GA 30084', 'Tucker', 'GA', '30084',
 33.8534, -84.2167, '{en,es,am,so,ar,sw,fr,vi,ko,my}', true, true, 'Mon — Fri 9am — 5pm + crisis line',
 false, false, false, true, true, true),

('Women''s Resource Center to End Domestic Violence',
 'DV shelter, counseling, court advocacy, and prevention programs serving DeKalb County and beyond.',
 'DeKalb County DV shelter and advocacy.',
 (select id from categories where slug = 'womens'),
 'https://www.wrcdv.org', '(404) 688-9436',
 'Confidential — Decatur, GA', 'Decatur', 'GA', '30030',
 33.7748, -84.2963, '{en,es}', true, true, '24/7 hotline',
 true, true, true, true, true, false),

('International Women''s House',
 'Shelter and services for immigrant and refugee women experiencing domestic violence.',
 'DV shelter for immigrant and refugee women.',
 (select id from categories where slug = 'womens'),
 'https://www.iwhouse.org', '(770) 413-5557',
 'Confidential — Stone Mountain, GA', 'Stone Mountain', 'GA', '30083',
 33.8053, -84.1452, '{en,es,am,so,ar,sw,fr,vi,ko}', true, true, '24/7 hotline',
 false, true, true, true, true, false),

('Genesis Shelter (Atlanta Mission)',
 'Emergency shelter for homeless mothers with newborns and infants — part of Atlanta Mission.',
 'Shelter for homeless mothers with newborns.',
 (select id from categories where slug = 'womens'),
 'https://atlantamission.org/our-campuses/genesis-shelter', '(404) 588-4007',
 '1010 Hank Aaron Dr SE, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7340, -84.3893, '{en,es}', true, true, '24/7 intake',
 true, true, true, true, true, false),

('Feminist Women''s Health Center',
 'Reproductive healthcare, abortion services, and well-woman care — sliding-scale fees, multiple languages.',
 'Reproductive and well-woman healthcare.',
 (select id from categories where slug = 'womens'),
 'https://www.feministcenter.org', '(404) 728-7900',
 '1924 Cliff Valley Way NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8246, -84.3265, '{en,es}', false, true, 'Tue — Sat — see hours',
 false, true, false, true, true, true),

('Planned Parenthood Southeast — Atlanta',
 'Reproductive and sexual health services — exams, contraception, STI testing — sliding-scale fees.',
 'Reproductive and sexual health — sliding-scale.',
 (select id from categories where slug = 'womens'),
 'https://www.plannedparenthood.org/health-center/georgia/atlanta', '(800) 230-7526',
 '440 Boulevard SE Suite C, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7383, -84.3711, '{en,es}', false, true, 'Mon — Sat — see hours',
 true, true, true, true, true, false),

('Salvation Army Women''s Shelter (Red Shield Services)',
 'Emergency and transitional shelter for women in crisis — meals, case management, and support.',
 'Emergency shelter for women in crisis.',
 (select id from categories where slug = 'womens'),
 'https://atlanta.salvationarmy.org', '(404) 588-4006',
 '465 Ponce de Leon Ave NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7724, -84.3717, '{en,es}', true, true, '24/7 intake',
 true, true, true, true, true, false),

-- ============== HEALTHCARE (more) ==============
('Grady Health System',
 'Atlanta''s largest public hospital — emergency care, specialty clinics, Grady Cares program for low-income patients.',
 'Atlanta''s largest public hospital. Has financial aid program.',
 (select id from categories where slug = 'healthcare'),
 'https://www.gradyhealth.org', '(404) 616-1000',
 '80 Jesse Hill Jr Dr SE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7541, -84.3815, '{en,es,zh,vi,ko,ar,am,so}', false, true, '24/7',
 true, true, true, true, true, true),

('Fulton County Board of Health',
 'County-run public health clinics — immunizations, STI testing, WIC, maternal health, and TB screening.',
 'Public health clinics — immunizations, WIC, STI testing.',
 (select id from categories where slug = 'healthcare'),
 'https://www.fultoncountyga.gov/services/health-services', '(404) 612-0500',
 '99 Jesse Hill Jr Dr SE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7541, -84.3815, '{en,es}', true, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, true),

('DeKalb County Board of Health',
 'County-run public health clinics — immunizations, family planning, WIC, and maternal health.',
 'DeKalb public health clinics — immunizations and WIC.',
 (select id from categories where slug = 'healthcare'),
 'https://www.dekalbhealth.net', '(404) 294-3700',
 '445 Winn Way, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7748, -84.2715, '{en,es,am,so}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Cobb & Douglas Public Health',
 'Public health services for Cobb and Douglas counties — immunizations, WIC, family health, environmental health.',
 'Public health for Cobb and Douglas counties.',
 (select id from categories where slug = 'healthcare'),
 'https://www.cobbanddouglaspublichealth.org', '(770) 514-2300',
 '1650 County Services Pkwy SW, Marietta, GA 30008', 'Marietta', 'GA', '30008',
 33.9134, -84.5751, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Gwinnett, Newton & Rockdale County Health Departments',
 'Public health clinics across three counties — immunizations, WIC, family health, and environmental services.',
 'Public health clinics serving Gwinnett, Newton, Rockdale.',
 (select id from categories where slug = 'healthcare'),
 'https://gnrhealth.com', '(770) 339-4260',
 '455 Grayson Hwy Suite 300, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9526, -83.9889, '{en,es,vi,ko}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('AID Atlanta',
 'HIV testing, prevention, treatment, case management, and support for people living with HIV.',
 'HIV testing, treatment, and support services.',
 (select id from categories where slug = 'healthcare'),
 'https://www.aidatlanta.org', '(404) 870-7700',
 '1605 Chantilly Dr NE Suite 200, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8128, -84.3439, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, true, true, true, true),

('Whitefoord Inc.',
 'Community health center serving children and families in southeast Atlanta — primary care and dental.',
 'Community health center for children and families.',
 (select id from categories where slug = 'healthcare'),
 'https://www.whitefoord.org', '(404) 525-9070',
 '32 Whitefoord Ave SE, Atlanta, GA 30317', 'Atlanta', 'GA', '30317',
 33.7546, -84.3257, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Children''s Healthcare of Atlanta (Egleston Hospital)',
 'Pediatric hospital with emergency care, specialty clinics, and financial assistance for families.',
 'Pediatric hospital with financial assistance.',
 (select id from categories where slug = 'healthcare'),
 'https://www.choa.org', '(404) 785-6000',
 '1405 Clifton Rd NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7951, -84.3236, '{en,es}', false, true, '24/7',
 true, true, true, true, true, true),

-- ============== HOUSING (more) ==============
('Atlanta Housing (AHA)',
 'City of Atlanta''s public housing authority — Housing Choice Vouchers, public housing, and homeownership programs.',
 'Atlanta''s housing authority — vouchers and public housing.',
 (select id from categories where slug = 'housing'),
 'https://www.atlantahousing.org', '(404) 892-4700',
 '230 John Wesley Dobbs Ave NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7563, -84.3815, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, true),

('Star-C Initiative',
 'Affordable housing partnership with on-site after-school programs at apartment communities across metro Atlanta.',
 'Affordable apartments with after-school programs.',
 (select id from categories where slug = 'housing'),
 'https://www.starc.org', '(770) 612-9100',
 '6065 Roswell Rd Suite 1226, Atlanta, GA 30328', 'Atlanta', 'GA', '30328',
 33.9226, -84.3743, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Mercy Housing Southeast',
 'Affordable housing developer and property manager for low-income families and seniors.',
 'Affordable apartments for low-income families and seniors.',
 (select id from categories where slug = 'housing'),
 'https://www.mercyhousing.org', '(404) 803-6000',
 '675 Ponce de Leon Ave NE Suite N400, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7732, -84.3672, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('HOPE Atlanta — Travelers Aid',
 'Homelessness prevention, emergency shelter referrals, and re-housing for individuals and families.',
 'Homelessness prevention and re-housing help.',
 (select id from categories where slug = 'housing'),
 'https://hopeatlanta.org', '(404) 817-7070',
 '241 Peachtree St NE Suite 600, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7591, -84.3879, '{en,es}', true, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Project Community Connections (PCCI)',
 'Permanent supportive housing for chronically homeless individuals and families in metro Atlanta.',
 'Permanent supportive housing for the chronically homeless.',
 (select id from categories where slug = 'housing'),
 'https://www.pcciatlanta.org', '(404) 215-1000',
 '1320 Ellsworth Industrial Blvd NW Suite A1000, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7949, -84.4267, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== EMPLOYMENT (more) ==============
('Goodwill of North Georgia',
 'Workforce development, career training, and job placement at multiple metro Atlanta career centers.',
 'Workforce development and job placement help.',
 (select id from categories where slug = 'employment'),
 'https://goodwillng.org', '(404) 420-9900',
 '2201 Glenwood Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7376, -84.3458, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

('WorkSource Atlanta',
 'American Job Center for the city of Atlanta — career counseling, training, and job search resources.',
 'American Job Center for Atlanta — training and jobs.',
 (select id from categories where slug = 'employment'),
 'https://workforce.atlantaga.gov', '(404) 658-9675',
 '818 Pollard Blvd SW, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7273, -84.4068, '{en,es}', true, true, 'Mon — Fri 8:15am — 4:45pm',
 true, false, false, true, true, true),

('Year Up Atlanta',
 'Free year-long career training program for young adults 18–29 — IT, sales, financial operations.',
 'Free year-long career training for young adults.',
 (select id from categories where slug = 'employment'),
 'https://www.yearup.org/locations/atlanta', '(404) 942-5530',
 '675 Ponce de Leon Ave NE Suite N400, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7732, -84.3672, '{en,es}', true, true, 'Cohorts twice yearly',
 false, false, true, true, true, true),

('Hire Heroes USA — Atlanta',
 'Free career coaching and job-search support for U.S. military veterans and their spouses.',
 'Free career coaching for veterans and spouses.',
 (select id from categories where slug = 'employment'),
 'https://www.hireheroesusa.org', '(844) 634-1520',
 '1330 Powers Ferry Rd SE Building 12 Suite 100, Marietta, GA 30067', 'Marietta', 'GA', '30067',
 33.9087, -84.4598, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('Georgia Department of Labor',
 'State agency for unemployment insurance, job listings, vocational rehab, and career centers across Georgia.',
 'Unemployment, job listings, and career centers.',
 (select id from categories where slug = 'employment'),
 'https://dol.georgia.gov', '(404) 232-3001',
 '148 Andrew Young International Blvd NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7613, -84.3863, '{en,es}', true, true, 'Mon — Fri 8am — 4:30pm',
 true, false, false, true, true, true),

-- ============== FINANCIAL (more) ==============
('Operation HOPE',
 'Free financial coaching, credit-building help, small business and homeownership support across Atlanta and beyond.',
 'Free financial coaching and credit-building.',
 (select id from categories where slug = 'financial'),
 'https://operationhope.org', '(404) 941-2919',
 '191 Peachtree St NE Suite 3840, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7587, -84.3878, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

('VITA — Volunteer Income Tax Assistance (United Way)',
 'IRS-certified volunteers prepare federal and state tax returns for free for households earning under ~$60K.',
 'Free tax help for households earning under ~$60K.',
 (select id from categories where slug = 'financial'),
 'https://unitedwayatlanta.org/vita', '(211)',
 'Multiple Atlanta sites — call 211 to find one', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Tax season — Jan to Apr',
 false, true, true, true, true, true),

('Junior Achievement of Georgia',
 'Free K–12 financial literacy, work readiness, and entrepreneurship programs in schools and at the JA Discovery Center.',
 'Free financial literacy programs for students.',
 (select id from categories where slug = 'financial'),
 'https://www.georgia.ja.org', '(404) 257-1932',
 '5901 Peachtree Dunwoody Rd, Atlanta, GA 30328', 'Atlanta', 'GA', '30328',
 33.9226, -84.3623, '{en,es}', true, true, 'School-year programs',
 false, false, false, true, true, false),

('LISC Atlanta',
 'Local Initiatives Support Corporation — invests in affordable housing, small business, and community development.',
 'Affordable housing and small business investment.',
 (select id from categories where slug = 'financial'),
 'https://www.lisc.org/atlanta', '(404) 880-9100',
 '230 Peachtree St NW Suite 2200, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7587, -84.3878, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== LEGAL (more) ==============
('Tahirih Justice Center — Atlanta',
 'Free legal services and case management for immigrant women and girls fleeing gender-based violence.',
 'Free legal aid for immigrant women fleeing violence.',
 (select id from categories where slug = 'legal'),
 'https://www.tahirih.org/locations/atlanta', '(571) 282-6161',
 '6100 Lake Forrest Dr NW Suite 300, Atlanta, GA 30328', 'Atlanta', 'GA', '30328',
 33.9237, -84.3868, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('ACLU of Georgia',
 'Civil rights advocacy and impact litigation across Georgia — voting rights, immigration, criminal justice.',
 'Civil rights advocacy and litigation in Georgia.',
 (select id from categories where slug = 'legal'),
 'https://www.acluga.org', '(770) 303-8111',
 '410 Sandy Springs Pl NE Suite 105, Atlanta, GA 30328', 'Atlanta', 'GA', '30328',
 33.9252, -84.3789, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Georgia Asylum & Immigration Network (GAIN)',
 'Free legal help with asylum, U-visas, T-visas, and other humanitarian immigration cases.',
 'Free legal help with asylum and humanitarian visas.',
 (select id from categories where slug = 'legal'),
 'https://www.georgiaasylum.org', '(404) 600-1851',
 '410 Plasters Ave NE Suite 200, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8073, -84.3750, '{en,es,fr,ar}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Atlanta Volunteer Lawyers Foundation (AVLF)',
 'Pro bono legal help for low-income Atlantans — eviction defense, family law, and victim advocacy.',
 'Pro bono legal help for low-income Atlantans.',
 (select id from categories where slug = 'legal'),
 'https://www.avlf.org', '(404) 521-0790',
 '54 Ellis St NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7546, -84.3867, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Atlanta Bar Association — Lawyer Referral Service',
 'Connects people to vetted lawyers — first 30 minutes for $25, even free for some areas.',
 'Lawyer referral — affordable first consultations.',
 (select id from categories where slug = 'legal'),
 'https://www.atlantabar.org/page/LRIS', '(404) 521-0777',
 '400 International Tower 229 Peachtree St NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7587, -84.3878, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Georgia Public Defender Council',
 'State agency providing free criminal defense to people who cannot afford a private attorney.',
 'Free criminal defense for those who can''t afford a lawyer.',
 (select id from categories where slug = 'legal'),
 'https://www.gapubdef.org', '(404) 232-9700',
 '270 Washington St SW Suite 5198, Atlanta, GA 30334', 'Atlanta', 'GA', '30334',
 33.7488, -84.3884, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

-- ============== COMMUNITY (more) ==============
('Welcoming Atlanta',
 'City of Atlanta initiative connecting immigrants and refugees with services, language help, and civic engagement.',
 'City of Atlanta program for immigrants and refugees.',
 (select id from categories where slug = 'community'),
 'https://www.welcomingatlanta.com', '(404) 330-6720',
 '55 Trinity Ave SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7488, -84.3922, '{en,es,fr,ar,zh,vi,ko,am,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('World Relief Atlanta',
 'Refugee resettlement, employment services, and immigration legal help.',
 'Refugee resettlement and immigration legal help.',
 (select id from categories where slug = 'community'),
 'https://worldrelief.org/atlanta', '(404) 294-4352',
 '4151 Memorial Dr Suite 105, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7672, -84.2415, '{en,es,fr,ar,sw,fa,ps,my,am,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Coptic Orthodox Diocese of the Southern United States',
 'Coptic Orthodox parishes serving Egyptian and other Middle Eastern Christian communities across the Southeast.',
 'Coptic Orthodox parishes serving the Southeast.',
 (select id from categories where slug = 'community'),
 'https://suscopts.org', '(770) 414-1052',
 '7 Riverside Dr SE, Cartersville, GA 30121', 'Cartersville', 'GA', '30121',
 34.1656, -84.7965, '{en,ar}', true, true, 'Sunday liturgy + weekly programs',
 true, true, false, true, true, false),

('Korean American Coalition — Atlanta',
 'Civic engagement, leadership development, and advocacy for Korean Americans in Georgia.',
 'Civic and leadership programs for Korean Americans.',
 (select id from categories where slug = 'community'),
 'https://kacatlanta.org', '(770) 622-3346',
 '5901 Peachtree Industrial Blvd Suite C-1, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9389, -84.2123, '{en,ko}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== EMERGENCY (more) ==============
('211 — United Way of Greater Atlanta',
 'Free 24/7 referral line connecting people to housing, food, healthcare, mental health, and crisis resources.',
 'Free 24/7 referral line — dial 2-1-1.',
 (select id from categories where slug = 'emergency'),
 'https://211online.unitedwayatlanta.org', '211',
 'Phone & online — metro Atlanta', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('American Red Cross — Greater Atlanta',
 'Disaster response, blood drives, emergency shelters, and family reconnection services.',
 'Disaster response and emergency shelters.',
 (select id from categories where slug = 'emergency'),
 'https://www.redcross.org/local/georgia/about-us/locations/greater-atlanta', '(404) 876-3302',
 '1955 Monroe Dr NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8035, -84.3697, '{en,es}', true, true, '24/7 disaster response',
 true, true, true, true, true, false),

('Salvation Army Atlanta Area Command',
 'Emergency assistance, shelter, addiction recovery, food, and holiday programs.',
 'Emergency assistance, shelter, and food.',
 (select id from categories where slug = 'emergency'),
 'https://atlanta.salvationarmy.org', '(404) 486-2700',
 '1000 Center Pl, Norcross, GA 30093', 'Norcross', 'GA', '30093',
 33.9389, -84.2123, '{en,es}', true, true, 'Mon — Fri + emergencies',
 true, true, false, true, true, true),

('Georgia Crisis & Access Line (GCAL)',
 'Free 24/7 mental health and substance use crisis line for Georgians of all ages.',
 'Free 24/7 mental health crisis line for Georgia.',
 (select id from categories where slug = 'emergency'),
 'https://www.dbhdd.ga.gov/gcal', '(800) 715-4225',
 'Phone service — statewide Georgia', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('Georgia Emergency Management Agency (GEMA)',
 'State emergency management — disaster preparedness, response, recovery, and Ready Georgia program.',
 'State disaster preparedness and response.',
 (select id from categories where slug = 'emergency'),
 'https://gema.georgia.gov', '(404) 635-7200',
 '935 E Confederate Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7378, -84.3589, '{en,es}', true, true, '24/7 emergency operations',
 false, false, false, true, true, false),

-- ============== PARKS (more) ==============
('Grant Park (Atlanta)',
 'Historic 130-acre park on Atlanta''s east side — home to Zoo Atlanta, plus playgrounds and walking paths.',
 'Historic east-side park — home to Zoo Atlanta.',
 (select id from categories where slug = 'parks'),
 'https://www.atlantaga.gov/visitors/parks', '(404) 521-0938',
 '840 Cherokee Ave SE, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7330, -84.3717, '{en,es}', true, true, '6am — 11pm daily',
 true, true, true, false, true, false),

('Westside Park',
 'Atlanta''s largest park — 280 acres along the BeltLine''s westside, opened in 2021 with trails and lookouts.',
 'Atlanta''s largest park — 280 acres on the westside.',
 (select id from categories where slug = 'parks'),
 'https://beltline.org/places/westside-park', '(404) 477-3003',
 '1660 Johnson Rd NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7912, -84.4486, '{en,es}', true, true, '6am — 11pm daily',
 true, true, false, false, true, false),

('Historic Fourth Ward Park',
 'BeltLine-adjacent park with splash pad, playground, skate park, and amphitheater.',
 'BeltLine park with splash pad and skate park.',
 (select id from categories where slug = 'parks'),
 'https://h4wp.com', '(404) 875-7275',
 '680 Dallas St NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7672, -84.3689, '{en,es}', true, true, '6am — 11pm daily',
 true, true, true, false, true, false),

('Chastain Park',
 'Atlanta''s largest city park (268 acres) — golf, tennis, pool, horse park, walking paths, and amphitheater.',
 'Large Buckhead park with golf, tennis, and amphitheater.',
 (select id from categories where slug = 'parks'),
 'https://chastainpark.org', '(404) 252-4244',
 '4001 Powers Ferry Rd NW, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.8814, -84.3865, '{en}', true, true, '6am — 11pm daily',
 true, true, true, false, true, false),

('Center for Civil and Human Rights',
 'Museum and education center honoring the U.S. civil rights movement and global human rights movements.',
 'Civil and human rights museum downtown.',
 (select id from categories where slug = 'parks'),
 'https://www.civilandhumanrights.org', '(678) 999-8990',
 '100 Ivan Allen Jr Blvd, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7634, -84.3934, '{en,es}', false, true, 'Wed — Sun 12pm — 5pm',
 true, true, false, true, true, true),

('Martin Luther King Jr. National Historical Park',
 'Free National Park Service site honoring Dr. King — birth home, Ebenezer Baptist Church, and visitor center.',
 'Free national park honoring Dr. King.',
 (select id from categories where slug = 'parks'),
 'https://www.nps.gov/malu', '(404) 331-5190',
 '450 Auburn Ave NE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7563, -84.3727, '{en,es}', true, true, 'Daily 9am — 5pm',
 true, true, false, true, true, true),

('World of Coca-Cola',
 'Family attraction with Coca-Cola history, tastings of beverages from around the world, and bottling demos.',
 'Coca-Cola history and tasting room downtown.',
 (select id from categories where slug = 'parks'),
 'https://www.worldofcoca-cola.com', '(404) 676-5151',
 '121 Baker St NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7634, -84.3924, '{en,es}', false, true, 'Daily — see website',
 true, true, false, true, true, false),

('Atlanta History Center',
 'Museum, gardens, and historic houses — exhibits on the Civil War, Native American history, and the Atlanta Cyclorama.',
 'History museum with gardens and Cyclorama.',
 (select id from categories where slug = 'parks'),
 'https://www.atlantahistorycenter.com', '(404) 814-4000',
 '130 W Paces Ferry Rd NW, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8420, -84.3868, '{en,es}', false, true, 'Mon — Sun 10am — 5:30pm',
 true, true, false, true, true, false),

('College Football Hall of Fame',
 'Interactive museum honoring college football — 45-yard indoor field, exhibits, and team-specific content.',
 'Interactive college football museum downtown.',
 (select id from categories where slug = 'parks'),
 'https://www.cfbhall.com', '(404) 880-4800',
 '250 Marietta St NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7610, -84.3947, '{en,es}', false, true, 'Daily — see website',
 true, true, false, true, true, false),

('The Carter Center',
 'Founded by Jimmy & Rosalynn Carter — museum, library, and global health/peace programs. Free public lectures.',
 'Carter presidential library, museum, and gardens.',
 (select id from categories where slug = 'parks'),
 'https://www.cartercenter.org', '(404) 420-5100',
 '453 John Lewis Freedom Pkwy NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7686, -84.3522, '{en,es}', false, true, 'Mon — Sun 9am — 4:45pm',
 true, true, false, true, true, false),

('LEGOLAND Discovery Center Atlanta',
 'Indoor LEGO-themed family attraction at Phipps Plaza in Buckhead — rides, build zones, 4D theater.',
 'Indoor LEGO play and rides at Phipps Plaza.',
 (select id from categories where slug = 'parks'),
 'https://www.legolanddiscoverycenter.com/atlanta', '(404) 848-9252',
 '3500 Peachtree Rd NE, Atlanta, GA 30326', 'Atlanta', 'GA', '30326',
 33.8487, -84.3636, '{en,es}', false, true, 'Daily — see website',
 true, true, false, true, true, false),

('Tellus Science Museum',
 'Science museum north of Atlanta in Cartersville — fossils, gems, planetarium, and observatory.',
 'Science museum with fossils and planetarium.',
 (select id from categories where slug = 'parks'),
 'https://tellusmuseum.org', '(770) 386-0576',
 '100 Tellus Dr, Cartersville, GA 30120', 'Cartersville', 'GA', '30120',
 34.1908, -84.8275, '{en,es}', false, true, 'Daily 10am — 5pm',
 true, true, false, true, true, false),

('Red Top Mountain State Park',
 'State park on Lake Allatoona about 35 miles north of Atlanta — hiking, beach, boating, and camping.',
 'Lakefront state park with hiking and beach.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/RedTopMountain', '(770) 975-0055',
 '50 Lodge Rd SE, Cartersville, GA 30121', 'Cartersville', 'GA', '30121',
 34.1419, -84.7019, '{en}', false, true, '7am — 10pm daily',
 true, true, true, true, true, false),

-- ============== TRANSPORTATION (more) ==============
('Hartsfield-Jackson Atlanta International Airport',
 'World''s busiest airport — public airport information, ground transportation desk, and SkyTrain (free).',
 'Atlanta''s international airport with public info desks.',
 (select id from categories where slug = 'transportation'),
 'https://www.atl.com', '(800) 897-1910',
 '6000 N Terminal Pkwy, Atlanta, GA 30320', 'Atlanta', 'GA', '30320',
 33.6407, -84.4277, '{en,es,zh,vi,ko,ar,fr}', false, true, '24/7',
 true, true, true, true, true, false),

('Georgia Department of Transportation (GDOT)',
 'State transportation agency — road conditions, 511 traffic info, and Georgia Express Lanes Peach Pass program.',
 'State road info, 511 traffic, and Peach Pass.',
 (select id from categories where slug = 'transportation'),
 'https://www.dot.ga.gov', '(404) 631-1990',
 '600 W Peachtree St NW, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7715, -84.3857, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('The ATL — Atlanta-Region Transit Link Authority',
 'Regional transit coordination across 13 counties — plans long-term transit and runs Xpress Bus.',
 'Regional transit planning agency for metro Atlanta.',
 (select id from categories where slug = 'transportation'),
 'https://atltransit.ga.gov', '(404) 463-4782',
 '245 Peachtree Center Ave NE Suite 2200, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7587, -84.3858, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

-- ============== FOOD (more) ==============
('Sweet Auburn Curb Market',
 'Historic public market downtown — produce, butchers, fish, prepared foods, and an Atlanta tradition since 1924.',
 'Historic downtown public market with produce and food.',
 (select id from categories where slug = 'food'),
 'https://www.sweetauburncurbmarket.com', '(404) 659-1665',
 '209 Edgewood Ave SE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7546, -84.3795, '{en,es}', false, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Ponce City Market — Central Food Hall',
 'Massive food hall inside the historic Ponce City Market — 30+ vendors, including affordable options.',
 'Food hall with 30+ vendors at Ponce City Market.',
 (select id from categories where slug = 'food'),
 'https://poncecitymarket.com', '(770) 282-2228',
 '675 Ponce de Leon Ave NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7732, -84.3672, '{en,es}', false, true, 'Daily — see website',
 true, true, true, true, true, false),

('99 Ranch Market — Duluth',
 'Large Asian-American supermarket chain — fresh produce, seafood, and pan-Asian groceries.',
 'Asian-American supermarket with seafood and produce.',
 (select id from categories where slug = 'food'),
 'https://www.99ranch.com', '(770) 622-7888',
 '3275 Steve Reynolds Blvd, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 33.9692, -84.1372, '{en,zh,vi,ko}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, false),

('Sevananda Natural Foods Market',
 'Member-owned natural foods cooperative in Little Five Points — local and organic groceries, bulk foods.',
 'Natural foods co-op with bulk and local groceries.',
 (select id from categories where slug = 'food'),
 'https://sevananda.coop', '(404) 681-2831',
 '467 Moreland Ave NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7672, -84.3486, '{en,es}', false, true, 'Daily 8am — 9pm',
 true, true, true, true, true, false),

-- ============== EDUCATION (more) ==============
('Atlanta Public Schools',
 'Atlanta''s K–12 public school district — 60,000+ students, free enrollment for residents.',
 'Atlanta''s K–12 public school district.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us', '(404) 802-3500',
 '130 Trinity Ave SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7472, -84.3920, '{en,es,vi,ko,zh,am,so,ar}', true, true, 'Office Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('DeKalb County School District',
 'DeKalb County K–12 public school district — large refugee and immigrant student population, with newcomer support.',
 'DeKalb K–12 schools with newcomer programs.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org', '(678) 676-1200',
 '1701 Mountain Industrial Blvd, Stone Mountain, GA 30083', 'Stone Mountain', 'GA', '30083',
 33.8053, -84.1452, '{en,es,vi,ko,zh,am,so,ar,fr}', true, true, 'Office Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Atlanta Metropolitan State College',
 'Affordable two-year public college — open admission, transfer pathways, and adult education.',
 'Affordable public 2-year college with adult education.',
 (select id from categories where slug = 'education'),
 'https://www.atlm.edu', '(404) 756-4004',
 '1630 Metropolitan Pkwy SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7123, -84.4134, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 false, false, true, true, true, false)

on conflict do nothing;