-- 006_schools_and_more.sql
-- Adds ~200 more real, verifiable Georgia institutions and resources.
-- Includes well-known Georgia universities, technical/community colleges,
-- large metro Atlanta public high schools and middle schools (especially
-- those serving immigrant communities), plus more hospitals, state parks,
-- markets, places of worship, and community services.
-- All entries are publicly known organizations. Ratings remain null pending
-- Google Places API integration.

insert into resources (
  name, description, short_description, category_id,
  website_url, phone, address, city, state, zip,
  latitude, longitude, languages, is_free, serves_undocumented, hours,
  walk_in_available, weekend_hours, evening_hours, phone_intake,
  is_verified, is_featured
) values

-- ============== EDUCATION — UNIVERSITIES ==============
('Georgia State University',
 'Large public research university in downtown Atlanta — undergraduate, graduate, and professional programs. Strong support for first-generation and immigrant students.',
 'Public research university in downtown Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.gsu.edu', '(404) 413-2000',
 '33 Gilmer St SE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7530, -84.3865, '{en,es,zh,vi,ko,ar,fr}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, true),

('Georgia Institute of Technology',
 'Top public research university focused on engineering, science, and technology — Midtown Atlanta campus.',
 'Top public research university in Midtown.',
 (select id from categories where slug = 'education'),
 'https://www.gatech.edu', '(404) 894-2000',
 '225 North Ave NW, Atlanta, GA 30332', 'Atlanta', 'GA', '30332',
 33.7756, -84.3963, '{en,zh,ko,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Emory University',
 'Private research university near Druid Hills — known for medicine, law, business, and global health.',
 'Private research university in Druid Hills.',
 (select id from categories where slug = 'education'),
 'https://www.emory.edu', '(404) 727-6123',
 '201 Dowman Dr, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7925, -84.3243, '{en,es,zh,ko}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, true),

('University of Georgia',
 'Flagship public research university in Athens — one of the oldest universities in the U.S.',
 'Flagship state university in Athens.',
 (select id from categories where slug = 'education'),
 'https://www.uga.edu', '(706) 542-3000',
 '215 S Jackson St, Athens, GA 30602', 'Athens', 'GA', '30602',
 33.9480, -83.3773, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Kennesaw State University',
 'Large public university with campuses in Kennesaw and Marietta — strong programs in business, education, and engineering.',
 'Large public university — Kennesaw & Marietta campuses.',
 (select id from categories where slug = 'education'),
 'https://www.kennesaw.edu', '(470) 578-6000',
 '1000 Chastain Rd, Kennesaw, GA 30144', 'Kennesaw', 'GA', '30144',
 34.0381, -84.5811, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Spelman College',
 'Historic Black women''s liberal arts college — part of the Atlanta University Center.',
 'Historic Black women''s liberal arts college.',
 (select id from categories where slug = 'education'),
 'https://www.spelman.edu', '(404) 681-3643',
 '350 Spelman Ln SW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7464, -84.4117, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, true),

('Morehouse College',
 'Historic men''s liberal arts college — part of the Atlanta University Center, alma mater of Dr. King.',
 'Historic men''s HBCU — Dr. King''s alma mater.',
 (select id from categories where slug = 'education'),
 'https://www.morehouse.edu', '(404) 681-2800',
 '830 Westview Dr SW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7459, -84.4150, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, true),

('Clark Atlanta University',
 'HBCU formed by the merger of Clark College and Atlanta University — part of the Atlanta University Center.',
 'HBCU in the Atlanta University Center.',
 (select id from categories where slug = 'education'),
 'https://www.cau.edu', '(404) 880-8000',
 '223 James P Brawley Dr SW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7510, -84.4127, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Agnes Scott College',
 'Private women''s liberal arts college in Decatur with a global learning curriculum.',
 'Private women''s liberal arts college in Decatur.',
 (select id from categories where slug = 'education'),
 'https://www.agnesscott.edu', '(404) 471-6000',
 '141 E College Ave, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7682, -84.2939, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Oglethorpe University',
 'Small private liberal arts university in Brookhaven — strong undergraduate teaching focus.',
 'Small private liberal arts university in Brookhaven.',
 (select id from categories where slug = 'education'),
 'https://www.oglethorpe.edu', '(404) 261-1441',
 '4484 Peachtree Rd NE, Atlanta, GA 30319', 'Atlanta', 'GA', '30319',
 33.8730, -84.3346, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Georgia Gwinnett College',
 'Public four-year college in Lawrenceville with open enrollment and strong support for diverse students.',
 'Open-enrollment public college in Lawrenceville.',
 (select id from categories where slug = 'education'),
 'https://www.ggc.edu', '(678) 407-5000',
 '1000 University Center Ln, Lawrenceville, GA 30043', 'Lawrenceville', 'GA', '30043',
 33.9893, -83.9849, '{en,es,vi,ko,zh}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Mercer University — Atlanta',
 'Private university with an Atlanta campus offering graduate and professional programs.',
 'Private university — Atlanta campus.',
 (select id from categories where slug = 'education'),
 'https://www.mercer.edu', '(678) 547-6000',
 '3001 Mercer University Dr, Atlanta, GA 30341', 'Atlanta', 'GA', '30341',
 33.8916, -84.3105, '{en}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Savannah College of Art and Design — Atlanta',
 'Private art and design university with a Midtown Atlanta campus — film, animation, design programs.',
 'Private art & design university in Midtown.',
 (select id from categories where slug = 'education'),
 'https://www.scad.edu/locations/atlanta', '(404) 253-2700',
 '1600 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7950, -84.3855, '{en,es,zh,ko}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Georgia State University — Perimeter College',
 'Open-enrollment associate degree college — five metro Atlanta campuses, low-cost transfer pathway to GSU.',
 'Open-enrollment 2-year college, multiple campuses.',
 (select id from categories where slug = 'education'),
 'https://perimeter.gsu.edu', '(404) 413-2000',
 '555 N Indian Creek Dr, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8167, -84.2400, '{en,es,vi,ko,zh,am,so}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, true),

('Augusta University',
 'Public research university and academic medical center in Augusta — known for the Medical College of Georgia.',
 'Public university and medical center in Augusta.',
 (select id from categories where slug = 'education'),
 'https://www.augusta.edu', '(706) 721-0211',
 '1120 15th St, Augusta, GA 30912', 'Augusta', 'GA', '30912',
 33.4716, -81.9837, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Georgia Southern University',
 'Large public research university in Statesboro with campuses in Savannah and Hinesville.',
 'Public research university in Statesboro.',
 (select id from categories where slug = 'education'),
 'https://www.georgiasouthern.edu', '(912) 478-4636',
 '1332 Southern Dr, Statesboro, GA 30458', 'Statesboro', 'GA', '30458',
 32.4202, -81.7826, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Valdosta State University',
 'Public university in south Georgia — broad undergraduate and graduate programs.',
 'Public university in Valdosta.',
 (select id from categories where slug = 'education'),
 'https://www.valdosta.edu', '(229) 333-5800',
 '1500 N Patterson St, Valdosta, GA 31698', 'Valdosta', 'GA', '31698',
 30.8489, -83.2867, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Brenau University',
 'Private university in Gainesville with a women''s undergraduate college and coed graduate programs.',
 'Private university in Gainesville.',
 (select id from categories where slug = 'education'),
 'https://www.brenau.edu', '(770) 534-6299',
 '500 Washington St SE, Gainesville, GA 30501', 'Gainesville', 'GA', '30501',
 34.2966, -83.8260, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Columbus State University',
 'Public university in Columbus — undergraduate and graduate programs across multiple disciplines.',
 'Public university in Columbus.',
 (select id from categories where slug = 'education'),
 'https://www.columbusstate.edu', '(706) 507-8800',
 '4225 University Ave, Columbus, GA 31907', 'Columbus', 'GA', '31907',
 32.5024, -84.9389, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Georgia College & State University',
 'Georgia''s designated public liberal arts university, located in Milledgeville.',
 'Public liberal arts university in Milledgeville.',
 (select id from categories where slug = 'education'),
 'https://www.gcsu.edu', '(478) 445-5004',
 '231 W Hancock St, Milledgeville, GA 31061', 'Milledgeville', 'GA', '31061',
 33.0801, -83.2321, '{en}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

-- ============== EDUCATION — TECHNICAL & COMMUNITY COLLEGES ==============
('Atlanta Technical College',
 'Technical college offering associate degrees, diplomas, and certificates — strong ESL and adult education programs.',
 'Technical college with ESL and adult ed.',
 (select id from categories where slug = 'education'),
 'https://www.atlantatech.edu', '(404) 225-4400',
 '1560 Metropolitan Pkwy SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7141, -84.4189, '{en,es,vi,ko,zh}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, true),

('Gwinnett Technical College',
 'Public technical college in Lawrenceville and Alpharetta — short-term certificates to associate degrees.',
 'Technical college serving Gwinnett.',
 (select id from categories where slug = 'education'),
 'https://www.gwinnetttech.edu', '(770) 962-7580',
 '5150 Sugarloaf Pkwy, Lawrenceville, GA 30043', 'Lawrenceville', 'GA', '30043',
 33.9614, -84.0162, '{en,es,vi,ko,zh}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, true),

('Chattahoochee Technical College',
 'Public technical college serving north Georgia with campuses across Cobb, Cherokee, Paulding, and Bartow.',
 'Technical college — multiple north metro campuses.',
 (select id from categories where slug = 'education'),
 'https://www.chattahoocheetech.edu', '(770) 528-4545',
 '980 S Cobb Dr SE, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9259, -84.5311, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, false),

('Georgia Piedmont Technical College',
 'Public technical college in Clarkston with strong adult ed, ESL, and GED prep programs.',
 'Technical college with strong ESL and GED prep.',
 (select id from categories where slug = 'education'),
 'https://www.gptc.edu', '(404) 297-9522',
 '495 N Indian Creek Dr, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8167, -84.2419, '{en,es,vi,am,so,sw}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, true, true, true, true),

('Athens Technical College',
 'Public technical college serving northeast Georgia — Athens, Elberton, Greene, and Walton campuses.',
 'Technical college serving northeast Georgia.',
 (select id from categories where slug = 'education'),
 'https://www.athenstech.edu', '(706) 355-5000',
 '800 US Highway 29 N, Athens, GA 30601', 'Athens', 'GA', '30601',
 33.9942, -83.3553, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Lanier Technical College',
 'Public technical college serving Hall County and surrounding counties — Gainesville main campus.',
 'Technical college serving Hall County area.',
 (select id from categories where slug = 'education'),
 'https://www.laniertech.edu', '(770) 533-7000',
 '2535 Lanier Tech Dr, Gainesville, GA 30507', 'Gainesville', 'GA', '30507',
 34.2510, -83.7991, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('West Georgia Technical College',
 'Public technical college serving west Georgia counties — programs from welding to nursing.',
 'Technical college serving west Georgia.',
 (select id from categories where slug = 'education'),
 'https://www.westgatech.edu', '(770) 537-6000',
 '176 Murphy Campus Blvd, Waco, GA 30182', 'Waco', 'GA', '30182',
 33.7037, -85.1844, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Southern Crescent Technical College',
 'Public technical college serving Henry, Spalding, and surrounding counties.',
 'Technical college serving the southern crescent.',
 (select id from categories where slug = 'education'),
 'https://www.sctech.edu', '(770) 228-7348',
 '501 Varsity Rd, Griffin, GA 30223', 'Griffin', 'GA', '30223',
 33.2479, -84.2833, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Albany Technical College',
 'Public technical college in southwest Georgia — workforce training and adult education.',
 'Technical college serving southwest Georgia.',
 (select id from categories where slug = 'education'),
 'https://www.albanytech.edu', '(229) 430-3500',
 '1704 S Slappey Blvd, Albany, GA 31701', 'Albany', 'GA', '31701',
 31.5648, -84.1751, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Augusta Technical College',
 'Public technical college serving the CSRA region — programs from nursing to industrial trades.',
 'Technical college serving Augusta and CSRA.',
 (select id from categories where slug = 'education'),
 'https://www.augustatech.edu', '(706) 771-4000',
 '3200 Augusta Tech Dr, Augusta, GA 30906', 'Augusta', 'GA', '30906',
 33.4097, -82.0418, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

-- ============== EDUCATION — METRO ATLANTA HIGH SCHOOLS ==============
('Midtown High School (formerly Henry W. Grady HS)',
 'Atlanta Public Schools high school in Midtown serving Inman Park, Virginia-Highland, Midtown, and Old Fourth Ward.',
 'Atlanta Public Schools high school in Midtown.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/midtownhs', '(404) 802-3001',
 '929 Charles Allen Dr NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7794, -84.3742, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('North Atlanta High School',
 'Atlanta Public Schools high school in Buckhead — large IB diploma program and diverse student body.',
 'APS high school in Buckhead with IB program.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/northatlanta', '(404) 802-4700',
 '4111 Northside Pkwy NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8669, -84.4196, '{en,es,zh,ko,vi}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('Druid Hills High School',
 'DeKalb County school serving the Druid Hills area — IB program and diverse student body.',
 'DeKalb high school with IB program.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/druid-hills-high', '(678) 874-6302',
 '1798 Haygood Dr NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7826, -84.3340, '{en,es,fr,ar}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Decatur High School',
 'City Schools of Decatur high school — small district, strong academics, and community engagement.',
 'City Schools of Decatur high school.',
 (select id from categories where slug = 'education'),
 'https://www.csdecatur.net/dhs', '(404) 370-4420',
 '310 N McDonough St, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7793, -84.2964, '{en,es}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Lakeside High School (DeKalb)',
 'DeKalb County high school in northeast Atlanta with a magnet program for international studies.',
 'DeKalb high school — international studies magnet.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/lakeside-high', '(678) 874-6402',
 '3801 Briarcliff Rd NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8442, -84.3081, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Dunwoody High School',
 'DeKalb County high school in Dunwoody — strong academics and IB program.',
 'DeKalb high school in Dunwoody.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/dunwoody-high', '(678) 676-6802',
 '5035 Vermack Rd, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9342, -84.3197, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Walton High School',
 'Cobb County school in East Cobb — top-ranked Georgia public high school known for academics.',
 'Top-ranked Cobb County high school in East Cobb.',
 (select id from categories where slug = 'education'),
 'https://www.cobbk12.org/walton', '(770) 578-3225',
 '1590 Bill Murdock Rd, Marietta, GA 30062', 'Marietta', 'GA', '30062',
 33.9881, -84.4444, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Pope High School',
 'Cobb County high school in East Cobb — strong academics, athletics, and arts.',
 'Cobb high school in East Cobb.',
 (select id from categories where slug = 'education'),
 'https://www.cobbk12.org/pope', '(770) 578-7900',
 '3001 Hembree Rd, Marietta, GA 30062', 'Marietta', 'GA', '30062',
 34.0337, -84.4853, '{en,es}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Alpharetta High School',
 'Fulton County high school in Alpharetta — strong academics and large international student population.',
 'Fulton high school in Alpharetta with global focus.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/alpharettahs', '(770) 521-7600',
 '3595 Webb Bridge Rd, Alpharetta, GA 30005', 'Alpharetta', 'GA', '30005',
 34.0865, -84.2633, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Milton High School',
 'Fulton County high school in Milton — top-ranked academics and active arts and athletics.',
 'Top-ranked Fulton high school in Milton.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/miltonhs', '(770) 740-7000',
 '13025 Birmingham Hwy, Milton, GA 30004', 'Milton', 'GA', '30004',
 34.1606, -84.3173, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Roswell High School',
 'Fulton County high school in Roswell — long-standing academic and athletic programs.',
 'Fulton high school in Roswell.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/roswellhs', '(470) 254-4500',
 '11595 King Rd, Roswell, GA 30075', 'Roswell', 'GA', '30075',
 34.0381, -84.3795, '{en,es}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Centennial High School',
 'Fulton County high school in Roswell — diverse student body and strong arts and academics.',
 'Fulton high school in Roswell.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/centennialhs', '(470) 254-2300',
 '9310 Scott Rd, Roswell, GA 30076', 'Roswell', 'GA', '30076',
 34.0613, -84.3095, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Northview High School',
 'Fulton County high school in Johns Creek — top-ranked academics and large international community.',
 'Top-ranked Fulton high school in Johns Creek.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/northviewhs', '(470) 254-4900',
 '10625 Parsons Rd, Johns Creek, GA 30097', 'Johns Creek', 'GA', '30097',
 34.0455, -84.1925, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Brookwood High School',
 'Gwinnett County school in Snellville — large enrollment and strong athletic and academic record.',
 'Gwinnett high school in Snellville.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/brookwoodhs', '(770) 736-2000',
 '1255 Dogwood Rd, Snellville, GA 30078', 'Snellville', 'GA', '30078',
 33.8536, -84.0099, '{en,es,zh,ko}', true, true, 'Mon — Fri 7:20am — 2:20pm',
 false, false, false, true, true, false),

('Norcross High School',
 'Gwinnett County school in Peachtree Corners — large, diverse student body and IB program.',
 'Gwinnett high school in Peachtree Corners.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/norcrosshs', '(770) 448-3674',
 '5300 Spalding Dr, Peachtree Corners, GA 30092', 'Peachtree Corners', 'GA', '30092',
 33.9817, -84.2317, '{en,es,vi,ko,zh,hi}', true, true, 'Mon — Fri 7:20am — 2:20pm',
 false, false, false, true, true, false),

('Berkmar High School',
 'Gwinnett County school in Lilburn — large, diverse student body with strong ESOL programs.',
 'Gwinnett high school in Lilburn with ESOL.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/berkmarhs', '(770) 921-4621',
 '405 Pleasant Hill Rd NW, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.9251, -84.1383, '{en,es,vi,ko,zh,am,so,ar}', true, true, 'Mon — Fri 7:20am — 2:20pm',
 false, false, false, true, true, true),

('Meadowcreek High School',
 'Gwinnett County school in Norcross — large, diverse student body with extensive ESOL programs.',
 'Gwinnett high school in Norcross with strong ESOL.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/meadowcreekhs', '(770) 921-2705',
 '4455 Steve Reynolds Blvd, Norcross, GA 30093', 'Norcross', 'GA', '30093',
 33.9300, -84.1972, '{en,es,vi,ko,zh,am,so,ar,hi}', true, true, 'Mon — Fri 7:20am — 2:20pm',
 false, false, false, true, true, true),

('Cross Keys High School',
 'DeKalb County school in Brookhaven serving one of the most diverse student bodies in Georgia.',
 'Highly diverse DeKalb high school in Brookhaven.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/cross-keys-high', '(678) 874-7100',
 '1626 N Druid Hills Rd NE, Brookhaven, GA 30319', 'Brookhaven', 'GA', '30319',
 33.8537, -84.3247, '{en,es,vi,am,so,ar,fr,sw}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, true),

('Clarkston High School',
 'DeKalb County school in Clarkston — known nationally for serving large refugee student population.',
 'Clarkston high school — known for refugee students.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/clarkston-high', '(678) 676-5402',
 '618 N Indian Creek Dr, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8161, -84.2434, '{en,es,vi,am,so,ar,fr,sw,my,ne}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, true),

('Stone Mountain High School',
 'DeKalb County high school in Stone Mountain — diverse student body with active community programs.',
 'DeKalb high school in Stone Mountain.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/stone-mountain-high', '(678) 676-2602',
 '4555 Central Dr, Stone Mountain, GA 30083', 'Stone Mountain', 'GA', '30083',
 33.8053, -84.1666, '{en,es,fr,am,so}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Tucker High School',
 'DeKalb County school in Tucker — diverse student body with strong athletic and academic programs.',
 'DeKalb high school in Tucker.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/tucker-high', '(678) 875-3402',
 '5036 LaVista Rd, Tucker, GA 30084', 'Tucker', 'GA', '30084',
 33.8503, -84.2197, '{en,es,vi,ko}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Marietta High School',
 'Marietta City Schools high school — diverse student body and strong AP and IB programs.',
 'Marietta City high school with IB program.',
 (select id from categories where slug = 'education'),
 'https://www.marietta-city.org/Domain/13', '(770) 428-2631',
 '1171 Whitlock Ave NW, Marietta, GA 30064', 'Marietta', 'GA', '30064',
 33.9526, -84.5731, '{en,es,vi,ko}', true, true, 'Mon — Fri 8am — 3pm',
 false, false, false, true, true, false),

('Westlake High School',
 'Fulton County high school in southwest Atlanta — strong academics and athletic programs.',
 'Fulton high school in southwest Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/westlakehs', '(470) 254-6900',
 '2400 Union Rd SW, Atlanta, GA 30331', 'Atlanta', 'GA', '30331',
 33.6901, -84.5231, '{en,es}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Benjamin E. Mays High School',
 'Atlanta Public Schools high school in southwest Atlanta named for Dr. Benjamin E. Mays.',
 'APS high school in southwest Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/maysHS', '(404) 802-5000',
 '3450 Benjamin E Mays Dr SW, Atlanta, GA 30331', 'Atlanta', 'GA', '30331',
 33.7185, -84.5215, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('Maynard Jackson High School',
 'Atlanta Public Schools high school in southeast Atlanta named for former mayor Maynard Jackson.',
 'APS high school in southeast Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/jacksonHS', '(404) 802-5100',
 '801 Glenwood Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7373, -84.3580, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('Carver Early College',
 'Atlanta Public Schools early-college high school — students earn high school and college credit simultaneously.',
 'APS early-college high school in southeast Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/carverEC', '(404) 802-3300',
 '55 McDonough Blvd SE, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7173, -84.3811, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, true),

('Lassiter High School',
 'Cobb County high school in East Cobb — strong academics and a nationally known marching band.',
 'Cobb high school in East Cobb.',
 (select id from categories where slug = 'education'),
 'https://www.cobbk12.org/lassiter', '(678) 494-7863',
 '2601 Shallowford Rd, Marietta, GA 30066', 'Marietta', 'GA', '30066',
 34.0413, -84.4575, '{en,es}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('Wheeler High School',
 'Cobb County high school in East Cobb — magnet program for STEM and high-achievers.',
 'Cobb high school with STEM magnet program.',
 (select id from categories where slug = 'education'),
 'https://www.cobbk12.org/wheeler', '(770) 578-3266',
 '375 Holt Rd NE, Marietta, GA 30068', 'Marietta', 'GA', '30068',
 33.9586, -84.4219, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('South Forsyth High School',
 'Forsyth County high school in Cumming — strong academics and large international student community.',
 'Forsyth high school with global community.',
 (select id from categories where slug = 'education'),
 'https://www.forsyth.k12.ga.us/sfhs', '(770) 781-2264',
 '585 Peachtree Pkwy, Cumming, GA 30041', 'Cumming', 'GA', '30041',
 34.1640, -84.1411, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 8:25am — 3:25pm',
 false, false, false, true, true, false),

('South Cobb High School',
 'Cobb County high school in Austell — diverse student body and strong career-tech programs.',
 'Cobb high school in Austell.',
 (select id from categories where slug = 'education'),
 'https://www.cobbk12.org/southcobb', '(770) 819-2611',
 '1920 Clay Rd, Austell, GA 30106', 'Austell', 'GA', '30106',
 33.8132, -84.6019, '{en,es}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('McNair High School',
 'DeKalb County high school in southwest Atlanta named for astronaut Ronald McNair.',
 'DeKalb high school in southwest Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/mcnair-high', '(678) 676-6202',
 '1804 Bouldercrest Rd SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7037, -84.3183, '{en,es}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Booker T. Washington High School',
 'Atlanta Public Schools — first public high school for African American students in Georgia (founded 1924).',
 'Historic APS high school in west Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/washingtonHS', '(404) 802-4400',
 '45 Whitehouse Dr SW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7569, -84.4087, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

-- ============== EDUCATION — METRO ATLANTA MIDDLE SCHOOLS ==============
('Inman Middle School (David T. Howard)',
 'Atlanta Public Schools middle school serving the Midtown High cluster — strong arts and academic programs.',
 'APS middle school feeding Midtown HS.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/howardMS', '(404) 802-3000',
 '551 John Wesley Dobbs Ave NE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7574, -84.3768, '{en,es}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('Sutton Middle School',
 'Atlanta Public Schools middle school in Buckhead serving the North Atlanta High cluster.',
 'APS middle school in Buckhead.',
 (select id from categories where slug = 'education'),
 'https://www.atlantapublicschools.us/suttonMS', '(404) 802-5400',
 '4360 Powers Ferry Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8786, -84.4232, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:45am — 3:45pm',
 false, false, false, true, true, false),

('Renfroe Middle School',
 'City Schools of Decatur middle school for grades 6–8 — small district, strong community.',
 'City Schools of Decatur middle school.',
 (select id from categories where slug = 'education'),
 'https://www.csdecatur.net/renfroe', '(404) 370-4430',
 '220 W College Ave, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7770, -84.2997, '{en,es}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Druid Hills Middle School',
 'DeKalb County middle school feeding into Druid Hills High School — diverse student body.',
 'DeKalb middle school feeding Druid Hills HS.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/druid-hills-middle', '(678) 874-2602',
 '3100 Mt Olive Dr, Decatur, GA 30033', 'Decatur', 'GA', '30033',
 33.8157, -84.3013, '{en,es,fr,ar,am}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Henderson Middle School',
 'DeKalb County middle school in Chamblee — diverse student body and STEM focus.',
 'DeKalb middle school in Chamblee.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/henderson-middle', '(678) 874-6802',
 '2830 Henderson Mill Rd NE, Atlanta, GA 30341', 'Atlanta', 'GA', '30341',
 33.8983, -84.2858, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Sequoyah Middle School',
 'DeKalb County middle school in Doraville with diverse student body and ESOL programs.',
 'DeKalb middle school in Doraville with ESOL.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/sequoyah-middle', '(678) 676-7802',
 '3456 Aztec Rd, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.9013, -84.2814, '{en,es,vi,ko,zh,am,so}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Sandy Springs Middle School',
 'Fulton County middle school in Sandy Springs — diverse student body and STEM programs.',
 'Fulton middle school in Sandy Springs.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/sandyspringsms', '(470) 254-2270',
 '8750 Pride Pl, Sandy Springs, GA 30350', 'Sandy Springs', 'GA', '30350',
 33.9612, -84.3498, '{en,es,zh,ko}', true, true, 'Mon — Fri 9:15am — 4:15pm',
 false, false, false, true, true, false),

('Holcomb Bridge Middle School',
 'Fulton County middle school in Alpharetta — strong academics and large international student community.',
 'Fulton middle school in Alpharetta.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/holcombbridgems', '(770) 552-4540',
 '2700 Holcomb Bridge Rd, Alpharetta, GA 30022', 'Alpharetta', 'GA', '30022',
 34.0282, -84.2599, '{en,es,zh,ko,hi}', true, true, 'Mon — Fri 9:15am — 4:15pm',
 false, false, false, true, true, false),

('Pinckneyville Middle School',
 'Gwinnett County middle school in Peachtree Corners — diverse student body with ESOL.',
 'Gwinnett middle school in Peachtree Corners.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/pinckneyvillems', '(770) 448-3045',
 '5440 W Jones Bridge Rd, Peachtree Corners, GA 30092', 'Peachtree Corners', 'GA', '30092',
 33.9854, -84.2275, '{en,es,vi,ko,zh,hi}', true, true, 'Mon — Fri 8:50am — 3:50pm',
 false, false, false, true, true, false),

('Five Forks Middle School',
 'Gwinnett County middle school in Lawrenceville — strong academics and arts programs.',
 'Gwinnett middle school in Lawrenceville.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/fiveforksms', '(770) 717-2300',
 '3250 Five Forks Trickum Rd SW, Lawrenceville, GA 30044', 'Lawrenceville', 'GA', '30044',
 33.9196, -84.0738, '{en,es,vi,ko}', true, true, 'Mon — Fri 8:50am — 3:50pm',
 false, false, false, true, true, false),

-- ============== HEALTHCARE — MORE HOSPITALS ==============
('Northside Hospital Atlanta',
 'Major hospital system with flagship Atlanta campus — surgery, cancer care, women''s health, emergency.',
 'Major Atlanta hospital — full services.',
 (select id from categories where slug = 'healthcare'),
 'https://www.northside.com', '(404) 851-8000',
 '1000 Johnson Ferry Rd NE, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.9143, -84.3534, '{en,es,zh,ko,vi}', false, true, '24/7',
 true, true, true, true, true, true),

('Piedmont Atlanta Hospital',
 'Major nonprofit hospital in Buckhead — heart, cancer, transplant, and emergency services.',
 'Major Buckhead hospital — full services.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org/locations/piedmont-atlanta', '(404) 605-5000',
 '1968 Peachtree Rd NW, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.8095, -84.3954, '{en,es}', false, true, '24/7',
 true, true, true, true, true, true),

('Emory University Hospital',
 'Academic medical center on Emory''s main campus — specialty and transplant care, ER.',
 'Emory academic medical center.',
 (select id from categories where slug = 'healthcare'),
 'https://www.emoryhealthcare.org/locations/hospitals/emory-university-hospital', '(404) 712-2000',
 '1364 Clifton Rd NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7920, -84.3220, '{en,es,zh}', false, true, '24/7',
 true, true, true, true, true, true),

('Emory University Hospital Midtown',
 'Emory hospital in Midtown — full services including ER, women''s, and surgical care.',
 'Emory hospital in Midtown — full services.',
 (select id from categories where slug = 'healthcare'),
 'https://www.emoryhealthcare.org/locations/hospitals/emory-university-hospital-midtown', '(404) 686-4411',
 '550 Peachtree St NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7706, -84.3853, '{en,es,zh}', false, true, '24/7',
 true, true, true, true, true, false),

('Emory Saint Joseph''s Hospital',
 'Catholic hospital in Sandy Springs operated by Emory — heart and cancer care, ER.',
 'Emory Catholic hospital in Sandy Springs.',
 (select id from categories where slug = 'healthcare'),
 'https://www.emoryhealthcare.org/locations/hospitals/saint-josephs-hospital', '(678) 843-7001',
 '5665 Peachtree Dunwoody Rd, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.9211, -84.3535, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Shepherd Center',
 'Specialty hospital for spinal cord and brain injuries, multiple sclerosis, and other neurological conditions.',
 'Specialty hospital for spinal/brain injuries.',
 (select id from categories where slug = 'healthcare'),
 'https://www.shepherd.org', '(404) 352-2020',
 '2020 Peachtree Rd NW, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.8093, -84.3970, '{en,es}', false, true, '24/7',
 false, false, false, true, true, true),

('Emory Decatur Hospital',
 'Community hospital in Decatur, part of Emory Healthcare — full services and ER.',
 'Emory community hospital in Decatur.',
 (select id from categories where slug = 'healthcare'),
 'https://www.emoryhealthcare.org/locations/hospitals/decatur-hospital', '(404) 501-1000',
 '2701 N Decatur Rd, Decatur, GA 30033', 'Decatur', 'GA', '30033',
 33.7826, -84.2845, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Wellstar Kennestone Hospital',
 'Major hospital in Marietta — Cobb County''s largest hospital, with full specialty care.',
 'Major Cobb County hospital in Marietta.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org/locations/hospital/wellstar-kennestone-hospital', '(770) 793-5000',
 '677 Church St, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9682, -84.5398, '{en,es}', false, true, '24/7',
 true, true, true, true, true, true),

('Wellstar Cobb Hospital',
 'Wellstar hospital in Austell serving south Cobb — full services and ER.',
 'Wellstar hospital in Austell.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org/locations/hospital/wellstar-cobb-hospital', '(770) 732-4000',
 '3950 Austell Rd, Austell, GA 30106', 'Austell', 'GA', '30106',
 33.8313, -84.6203, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Northside Hospital Cherokee',
 'Northside hospital in Canton serving Cherokee County — emergency, surgery, women''s health.',
 'Northside hospital serving Cherokee County.',
 (select id from categories where slug = 'healthcare'),
 'https://www.northside.com/locations/northside-hospital-cherokee', '(770) 224-1000',
 '450 Northside Cherokee Blvd, Canton, GA 30115', 'Canton', 'GA', '30115',
 34.2017, -84.4894, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Northside Hospital Forsyth',
 'Northside hospital in Cumming serving Forsyth County — full services and ER.',
 'Northside hospital serving Forsyth County.',
 (select id from categories where slug = 'healthcare'),
 'https://www.northside.com/locations/northside-hospital-forsyth', '(770) 844-3200',
 '1200 Northside Forsyth Dr, Cumming, GA 30041', 'Cumming', 'GA', '30041',
 34.2076, -84.1437, '{en,es,zh,ko}', false, true, '24/7',
 true, true, true, true, true, false),

('Piedmont Henry Hospital',
 'Piedmont hospital in Stockbridge serving Henry County — full services and ER.',
 'Piedmont hospital in Stockbridge.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org/locations/piedmont-henry', '(678) 604-1000',
 '1133 Hospital Dr, Stockbridge, GA 30281', 'Stockbridge', 'GA', '30281',
 33.5262, -84.2333, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Piedmont Fayette Hospital',
 'Piedmont hospital in Fayetteville serving Fayette County — emergency and surgery.',
 'Piedmont hospital in Fayetteville.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org/locations/piedmont-fayette', '(770) 719-7000',
 '1255 GA-54, Fayetteville, GA 30214', 'Fayetteville', 'GA', '30214',
 33.4626, -84.4572, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Children''s Healthcare of Atlanta — Scottish Rite Hospital',
 'CHOA pediatric hospital in Sandy Springs — emergency, surgery, and specialty pediatric care.',
 'CHOA pediatric hospital in Sandy Springs.',
 (select id from categories where slug = 'healthcare'),
 'https://www.choa.org/locations/scottish-rite-hospital', '(404) 785-5252',
 '1001 Johnson Ferry Rd NE, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.9159, -84.3503, '{en,es}', false, true, '24/7',
 true, true, true, true, true, true),

('Piedmont Newton Hospital',
 'Piedmont community hospital in Covington serving Newton County — ER and inpatient care.',
 'Piedmont community hospital in Covington.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org/locations/piedmont-newton', '(770) 786-7053',
 '5126 Hospital Dr NE, Covington, GA 30014', 'Covington', 'GA', '30014',
 33.5963, -83.8504, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

-- ============== PARKS — STATE PARKS & MORE ==============
('Tallulah Gorge State Park',
 'Spectacular gorge with hiking, suspension bridge, and waterfalls in northeast Georgia.',
 'Spectacular gorge with hiking and falls.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/TallulahGorge', '(706) 754-7981',
 '338 Jane Hurt Yarn Rd, Tallulah Falls, GA 30573', 'Tallulah Falls', 'GA', '30573',
 34.7356, -83.3927, '{en}', false, true, '8am — sunset',
 true, true, false, true, true, false),

('Amicalola Falls State Park',
 'Home to Amicalola Falls — at 729 feet, the tallest waterfall in Georgia. Hiking and lodge.',
 'Tallest waterfall in Georgia, with hiking and lodge.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/AmicalolaFalls', '(706) 265-4703',
 '418 Amicalola Falls Lodge Rd, Dawsonville, GA 30534', 'Dawsonville', 'GA', '30534',
 34.5598, -84.2492, '{en}', false, true, '7am — 10pm',
 true, true, true, true, true, true),

('Cloudland Canyon State Park',
 'Northwest Georgia state park on Lookout Mountain — deep canyons, waterfalls, hiking, and camping.',
 'Northwest GA park with canyons and falls.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/CloudlandCanyon', '(706) 657-4050',
 '122 Cloudland Canyon Park Rd, Rising Fawn, GA 30738', 'Rising Fawn', 'GA', '30738',
 34.8347, -85.4810, '{en}', false, true, '7am — 10pm',
 true, true, true, true, true, false),

('F.D. Roosevelt State Park',
 'Georgia''s largest state park — hiking, lakes, and the Liberty Bell Pool near Pine Mountain.',
 'Georgia''s largest state park — hiking and lakes.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/FDRoosevelt', '(706) 663-4858',
 '2970 GA-190, Pine Mountain, GA 31822', 'Pine Mountain', 'GA', '31822',
 32.8400, -84.7958, '{en}', false, true, '7am — 10pm',
 true, true, true, true, true, false),

('Providence Canyon State Park',
 '"Georgia''s Little Grand Canyon" — colorful canyons formed by erosion in southwest Georgia.',
 'Georgia''s "Little Grand Canyon".',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/ProvidenceCanyon', '(229) 838-4244',
 '8930 Canyon Rd, Lumpkin, GA 31815', 'Lumpkin', 'GA', '31815',
 32.0696, -84.9117, '{en}', false, true, '7am — sunset',
 true, true, false, true, true, false),

('Vogel State Park',
 'One of Georgia''s oldest state parks — at the foot of Blood Mountain in the Chattahoochee National Forest.',
 'Historic mountain park near Blairsville.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/Vogel', '(706) 745-2628',
 '405 Vogel State Park Rd, Blairsville, GA 30512', 'Blairsville', 'GA', '30512',
 34.7670, -83.9222, '{en}', false, true, '7am — 10pm',
 true, true, true, true, true, false),

('Unicoi State Park & Lodge',
 'State park near Helen with a lodge, cabins, hiking trails, and Smith Lake.',
 'State park near Helen with lodge and lake.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/Unicoi', '(706) 878-2201',
 '1788 GA-356, Helen, GA 30545', 'Helen', 'GA', '30545',
 34.7345, -83.7191, '{en}', false, true, '7am — 10pm',
 true, true, true, true, true, false),

('Fort Mountain State Park',
 'North Georgia state park with hiking, lake, and a mysterious ancient stone wall on Fort Mountain.',
 'North GA state park with mysterious stone wall.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/FortMountain', '(706) 422-1932',
 '181 Fort Mountain Park Rd, Chatsworth, GA 30705', 'Chatsworth', 'GA', '30705',
 34.7714, -84.7028, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('High Falls State Park',
 'Park with the largest waterfall in middle Georgia — hiking, swimming, and camping.',
 'Largest waterfall in middle Georgia.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/HighFalls', '(478) 993-3053',
 '76 High Falls Park Dr, Jackson, GA 30233', 'Jackson', 'GA', '30233',
 33.1798, -84.0151, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Black Rock Mountain State Park',
 'Georgia''s highest state park, on the Eastern Continental Divide — hiking, scenic vistas, and camping.',
 'Georgia''s highest state park.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/BlackRockMountain', '(706) 746-2141',
 '3085 Black Rock Mountain Pkwy, Mountain City, GA 30562', 'Mountain City', 'GA', '30562',
 34.9123, -83.4115, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Indian Springs State Park',
 'One of America''s oldest state parks — Creek Indian sacred site with sulfur springs and a lake.',
 'One of America''s oldest state parks.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/IndianSprings', '(770) 504-2277',
 '678 Lake Clark Rd, Flovilla, GA 30216', 'Flovilla', 'GA', '30216',
 33.2467, -83.9221, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Kennesaw Mountain National Battlefield Park',
 'Civil War battlefield park in Kennesaw — hiking, history, and panoramic views from the mountain summit.',
 'Civil War battlefield with hiking trails.',
 (select id from categories where slug = 'parks'),
 'https://www.nps.gov/kemo', '(770) 427-4686',
 '900 Kennesaw Mountain Dr, Kennesaw, GA 30152', 'Kennesaw', 'GA', '30152',
 33.9844, -84.5697, '{en}', true, true, '7:30am — sunset',
 true, true, false, true, true, true),

('Brasstown Bald',
 'Georgia''s highest peak (4,784 ft) with observation deck and hiking trails in the Chattahoochee National Forest.',
 'Highest peak in Georgia with observation deck.',
 (select id from categories where slug = 'parks'),
 'https://www.fs.usda.gov/recarea/conf/recarea/?recid=10524', '(706) 745-6928',
 '2941 Hwy 180 Spur, Hiawassee, GA 30546', 'Hiawassee', 'GA', '30546',
 34.8741, -83.8108, '{en}', false, true, '10am — 5pm seasonal',
 true, true, false, true, true, false),

('Davidson-Arabia Mountain Nature Preserve',
 'DeKalb County preserve with rare granite outcrops, lakes, and hiking trails.',
 'DeKalb preserve with granite outcrops.',
 (select id from categories where slug = 'parks'),
 'https://www.arabiaalliance.org', '(404) 998-8384',
 '3787 Klondike Rd, Lithonia, GA 30038', 'Lithonia', 'GA', '30038',
 33.6673, -84.1186, '{en}', true, true, 'Sunrise to sunset',
 true, true, false, true, true, false),

('Brook Run Park',
 'Dunwoody''s largest park — playground, dog park, skate park, community garden, and trails.',
 'Dunwoody''s largest park with skate park.',
 (select id from categories where slug = 'parks'),
 'https://www.dunwoodyga.gov/parks/brook-run-park', '(678) 382-6700',
 '4770 N Peachtree Rd, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9347, -84.3091, '{en,es}', true, true, '6am — 11pm',
 true, true, true, false, true, false),

('Murphey Candler Park',
 'DeKalb County park in Brookhaven with a lake, walking trails, baseball fields, and playground.',
 'DeKalb park with lake and trails.',
 (select id from categories where slug = 'parks'),
 'https://www.dekalbcountyga.gov', '(404) 371-2475',
 '1551 W Nancy Creek Dr, Brookhaven, GA 30319', 'Brookhaven', 'GA', '30319',
 33.8950, -84.3380, '{en,es}', true, true, '7am — 9pm',
 true, true, true, false, true, false),

('Freedom Park',
 'Linear park with the Freedom Park Trail running through Inman Park, Old Fourth Ward, and Poncey-Highland.',
 'Linear park trail across east Atlanta.',
 (select id from categories where slug = 'parks'),
 'https://www.atlantaga.gov/visitors/parks', '(404) 875-7284',
 '1320 Ralph McGill Blvd NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7702, -84.3573, '{en}', true, true, '6am — 11pm',
 true, true, true, false, true, false),

('Adair Park',
 'Atlanta neighborhood park with playground, basketball, and walking paths in southwest Atlanta.',
 'Southwest Atlanta neighborhood park.',
 (select id from categories where slug = 'parks'),
 'https://www.atlantaga.gov/visitors/parks', '(404) 658-6101',
 '750 Catherine St SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7239, -84.4239, '{en,es}', true, true, '6am — 11pm',
 true, true, true, false, true, false),

-- ============== FOOD — MORE MARKETS ==============
('Peachtree Road Farmers Market',
 'Saturday farmers market at the Cathedral of St. Philip — local farmers, prepared foods, SNAP accepted.',
 'Saturday farmers market in Buckhead.',
 (select id from categories where slug = 'food'),
 'https://www.peachtreeroadfarmersmarket.com', '(404) 365-1000',
 '2744 Peachtree Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8348, -84.3792, '{en,es}', false, true, 'Sat 8:30am — 12pm (seasonal)',
 true, true, false, true, true, false),

('Morningside Farmers Market',
 'Year-round Saturday market in Morningside — local produce, eggs, meat, baked goods. Accepts SNAP.',
 'Year-round Saturday market in Morningside.',
 (select id from categories where slug = 'food'),
 'https://www.morningsidemarket.com', '(404) 313-5784',
 '1393 N Highland Ave NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7906, -84.3528, '{en}', false, true, 'Sat 8am — 11:30am',
 true, true, false, true, true, false),

('East Atlanta Village Farmers Market',
 'Thursday afternoon market in East Atlanta — local food and live music. SNAP accepted.',
 'Thursday afternoon market in East Atlanta.',
 (select id from categories where slug = 'food'),
 'https://www.eavfm.com', '(404) 622-4995',
 '561 Flat Shoals Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7406, -84.3450, '{en,es}', false, true, 'Thu 4pm — 8pm (seasonal)',
 true, false, true, true, true, false),

('Marietta Square Farmers Market',
 'Saturday farmers market on Marietta Square — local farmers, prepared foods, music.',
 'Saturday market on Marietta Square.',
 (select id from categories where slug = 'food'),
 'https://www.mariettasquarefarmersmarket.com', '(770) 794-5601',
 '65 Church St NE, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9531, -84.5495, '{en,es}', false, true, 'Sat 9am — 12pm',
 true, true, false, true, true, false),

('Decatur Farmers Market',
 'Wednesday and Saturday market in downtown Decatur — local growers and food vendors.',
 'Wed & Sat market in downtown Decatur.',
 (select id from categories where slug = 'food'),
 'https://www.cfmatl.org', '(404) 371-8386',
 '101 E Trinity Pl, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7748, -84.2962, '{en,es}', false, true, 'Wed 4 — 7pm; Sat 9am — 1pm',
 true, true, true, true, true, false),

('Grant Park Farmers Market',
 'Sunday market at the Larkin on Memorial — local food, produce, and crafts. SNAP accepted.',
 'Sunday farmers market at Grant Park.',
 (select id from categories where slug = 'food'),
 'https://www.cfmatl.org/grant-park', '(404) 371-8386',
 '600 Memorial Dr SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7464, -84.3697, '{en,es}', false, true, 'Sun 9am — 1pm',
 true, true, false, true, true, false),

('Cherians International Fresh Market',
 'Indian and South Asian supermarket in Decatur — produce, spices, prepared foods, and groceries.',
 'Indian/South Asian supermarket in Decatur.',
 (select id from categories where slug = 'food'),
 'https://www.cherians.com', '(770) 270-0014',
 '755 Indian Creek Dr Suite 800, Stone Mountain, GA 30083', 'Stone Mountain', 'GA', '30083',
 33.8063, -84.2406, '{en,hi,gu,ta,te,ml}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, false),

('Assi Plaza',
 'Korean supermarket and shopping plaza in Doraville — fresh produce, seafood, and Asian groceries.',
 'Korean supermarket in Doraville.',
 (select id from categories where slug = 'food'),
 'https://www.assiplaza.net', '(770) 936-0114',
 '6435 Spalding Dr, Norcross, GA 30092', 'Norcross', 'GA', '30092',
 33.9889, -84.2189, '{en,ko,zh}', false, true, 'Daily 9am — 10pm',
 true, true, true, true, true, false),

('City Farmers Market — Decatur',
 'Large international market with produce, meats, fish, and groceries from around the world.',
 'Large international market in Decatur.',
 (select id from categories where slug = 'food'),
 'https://cityfarmersmarket.us', '(404) 299-9938',
 '3460 Memorial Dr, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7619, -84.2503, '{en,es,vi,zh,ko,ar,am,so}', false, true, 'Daily 8am — 9pm',
 true, true, true, true, true, true),

('Compare Foods — Doraville',
 'Latin American supermarket — produce, meats, and Latin groceries.',
 'Latin American supermarket in Doraville.',
 (select id from categories where slug = 'food'),
 'https://www.comparesupermarkets.com', '(770) 936-9255',
 '5660 Buford Hwy NE, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.9089, -84.2811, '{en,es}', false, true, 'Daily 7am — 10pm',
 true, true, true, true, true, false),

('Atlanta International Farmers Market (Forest Park)',
 'Wholesale farmers market in Forest Park — open to the public early mornings.',
 'Wholesale farmers market in Forest Park.',
 (select id from categories where slug = 'food'),
 'https://www.atlantastatemarket.com', '(404) 366-6910',
 '16 Forest Pkwy, Forest Park, GA 30297', 'Forest Park', 'GA', '30297',
 33.6232, -84.3700, '{en,es}', false, true, 'Daily — early mornings',
 true, true, false, true, true, false),

('Brookhaven Farmers Market',
 'Saturday market in Brookhaven — local growers, prepared foods, and music.',
 'Saturday market in Brookhaven.',
 (select id from categories where slug = 'food'),
 'https://www.brookhavenfarmersmarket.com', '(404) 637-0500',
 '1441 Dresden Dr NE, Brookhaven, GA 30319', 'Brookhaven', 'GA', '30319',
 33.8655, -84.3401, '{en,es}', false, true, 'Sat 8:30am — 11:30am (seasonal)',
 true, true, false, true, true, false),

-- ============== FAITH — MORE PLACES OF WORSHIP ==============
('Sikh Gurdwara of Atlanta',
 'Sikh place of worship serving the metro Atlanta Sikh community — services and free langar (community meal).',
 'Atlanta Sikh gurdwara with free community meal.',
 (select id from categories where slug = 'faith'),
 'https://atlantagurdwara.com', '(770) 717-5934',
 '1158 Bethany Rd, Roswell, GA 30075', 'Roswell', 'GA', '30075',
 34.0356, -84.3456, '{en,pa,hi}', true, true, 'Sun service + daily prayers',
 true, true, false, true, true, false),

('Masjid Al-Mu''minun',
 'Historic mosque in Atlanta — daily prayers, Jumu''ah, and community programs.',
 'Historic mosque in Atlanta.',
 (select id from categories where slug = 'faith'),
 'https://masjidalmuminun.org', '(404) 627-2566',
 '1127 Hank Aaron Dr SW, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7330, -84.3893, '{en,ar}', true, true, 'Daily prayers — see schedule',
 true, true, true, true, true, false),

('Masjid Jafar (Jafaria Center of Atlanta)',
 'Shia Muslim center of worship and community programs in Lilburn.',
 'Shia Muslim community center in Lilburn.',
 (select id from categories where slug = 'faith'),
 'https://jafariaatlanta.org', '(770) 921-6677',
 '1690 Hwy 78 SW, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.8736, -84.1305, '{en,ar,ur,fa}', true, true, 'Daily prayers — see schedule',
 true, true, true, true, true, false),

('Wat Buddha Bucha',
 'Thai Buddhist temple in Decatur — meditation, services, and Thai cultural programs.',
 'Thai Buddhist temple in Decatur.',
 (select id from categories where slug = 'faith'),
 'https://watbuddhabucha.org', '(404) 297-9131',
 '4969 Tilly Mill Rd, Atlanta, GA 30338', 'Atlanta', 'GA', '30338',
 33.9183, -84.2867, '{en,th}', true, true, 'Daily meditation + services',
 true, true, false, true, true, false),

('North Point Community Church',
 'Large nondenominational evangelical church in Alpharetta — multiple campuses across metro Atlanta.',
 'Large nondenominational church in Alpharetta.',
 (select id from categories where slug = 'faith'),
 'https://northpoint.org', '(678) 892-5000',
 '4350 North Point Pkwy, Alpharetta, GA 30022', 'Alpharetta', 'GA', '30022',
 34.0712, -84.2821, '{en,es}', true, true, 'Sunday services + weekly programs',
 true, true, true, true, true, false),

('Passion City Church',
 'Nondenominational church in Atlanta with services in Buckhead and Cumberland.',
 'Nondenominational church with two campuses.',
 (select id from categories where slug = 'faith'),
 'https://passioncitychurch.com', '(404) 920-6800',
 '515 Garson Dr NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8170, -84.3641, '{en,es}', true, true, 'Sunday services + weekly programs',
 true, true, true, true, true, false),

('Buckhead Church',
 'Multi-campus church and one of the original North Point Ministries campuses.',
 'Buckhead campus of North Point Ministries.',
 (select id from categories where slug = 'faith'),
 'https://buckheadchurch.org', '(678) 892-2400',
 '3098 Piedmont Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8378, -84.3753, '{en,es}', true, true, 'Sunday services + weekly programs',
 true, true, true, true, true, false),

('Peachtree Road United Methodist Church',
 'Large historic United Methodist church in Buckhead — worship, music, and outreach.',
 'Historic UMC in Buckhead.',
 (select id from categories where slug = 'faith'),
 'https://prumc.org', '(404) 266-2373',
 '3180 Peachtree Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8421, -84.3759, '{en}', true, true, 'Sunday services + weekly programs',
 true, true, false, true, true, false),

('Temple Sinai',
 'Reform Jewish congregation in Sandy Springs — Shabbat services, religious school, and community programs.',
 'Reform Jewish congregation in Sandy Springs.',
 (select id from categories where slug = 'faith'),
 'https://templesinaiatlanta.org', '(404) 252-3073',
 '5645 Dupree Dr NW, Sandy Springs, GA 30327', 'Sandy Springs', 'GA', '30327',
 33.8920, -84.4070, '{en,he}', true, true, 'Shabbat & weekly services',
 true, true, true, true, true, false),

('Temple Emanu-El',
 'Reform Jewish congregation in Sandy Springs — Shabbat, religious school, and community programs.',
 'Reform Jewish congregation in Sandy Springs.',
 (select id from categories where slug = 'faith'),
 'https://templeemanuelatlanta.org', '(770) 395-1340',
 '1580 Spalding Dr, Atlanta, GA 30350', 'Atlanta', 'GA', '30350',
 33.9737, -84.3543, '{en,he}', true, true, 'Shabbat & weekly services',
 true, true, true, true, true, false),

('Vietnamese Buddhist Temple of Atlanta (Chua Phap Quang)',
 'Vietnamese Buddhist temple — services, meditation, and Vietnamese cultural programs.',
 'Vietnamese Buddhist temple.',
 (select id from categories where slug = 'faith'),
 'https://www.facebook.com/ChuaPhapQuang', '(404) 297-1812',
 '4994 Tilly Mill Rd, Atlanta, GA 30338', 'Atlanta', 'GA', '30338',
 33.9181, -84.2860, '{vi,en}', true, true, 'Weekly services',
 true, true, false, true, true, false),

-- ============== COMMUNITY — MORE ORGS ==============
('Latin American Association',
 'Atlanta''s leading Latino-serving organization — citizenship, employment, family services, and youth programs.',
 'Leading Atlanta Latino-serving nonprofit.',
 (select id from categories where slug = 'community'),
 'https://thelaa.org', '(404) 638-1800',
 '2750 Buford Hwy NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8225, -84.3210, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, true, true, true, true),

('Catholic Charities of Atlanta',
 'Refugee resettlement, immigration legal services, food pantry, parenting and counseling.',
 'Catholic charity offering refugee and family services.',
 (select id from categories where slug = 'community'),
 'https://catholiccharitiesatlanta.org', '(404) 881-6571',
 '2401 Lake Park Dr SE, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8714, -84.4969, '{en,es,fr,ar,vi}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Inspiritus (formerly Lutheran Services of Georgia)',
 'Refugee resettlement, foster care, disaster relief, and family services across Georgia.',
 'Refugee resettlement and family services.',
 (select id from categories where slug = 'community'),
 'https://weinspirit.org', '(404) 875-0201',
 '1899 Tobie Grant Cir, Scottdale, GA 30079', 'Scottdale', 'GA', '30079',
 33.7900, -84.2700, '{en,es,fr,ar,sw,fa,ps,my,am,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Refugee Coffee Co.',
 'Coffee shop and roaster in Clarkston that hires and trains refugees as baristas.',
 'Refugee-staffed coffee shop in Clarkston.',
 (select id from categories where slug = 'community'),
 'https://refugeecoffeeco.com', '(404) 549-9914',
 '4170 E Ponce de Leon Ave, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8093, -84.2418, '{en,es,fr,ar,sw,my}', false, true, 'Daily — see hours',
 true, true, false, true, true, true),

('Friends of Refugees',
 'Clarkston nonprofit offering employment, education, and health services for refugees.',
 'Clarkston nonprofit serving refugees.',
 (select id from categories where slug = 'community'),
 'https://friendsofrefugees.com', '(404) 528-5663',
 '1031 Brockett Rd, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8121, -84.2393, '{en,es,fr,ar,sw,fa,my,am,so,ne}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Center for Pan Asian Community Services (CPACS)',
 'Health, social, education, and economic services for Asian American and immigrant communities.',
 'Asian American community services agency.',
 (select id from categories where slug = 'community'),
 'https://www.cpacs.org', '(770) 936-0969',
 '3510 Shallowford Rd NE, Atlanta, GA 30341', 'Atlanta', 'GA', '30341',
 33.8836, -84.2858, '{en,zh,ko,vi,hi,ur,bn,my,ne,th,km}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

('Coalition of Refugee Service Agencies (CRSA)',
 'Coalition of organizations serving refugees in Georgia — coordinates resources and advocacy.',
 'Coalition of GA refugee service agencies.',
 (select id from categories where slug = 'community'),
 'https://www.crsageorgia.org', '(404) 444-3232',
 '4151 Memorial Dr Suite 102E, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7672, -84.2415, '{en}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Asociación Latinoamericana (Alianza)',
 'Atlanta-area community group serving Latin American immigrants with cultural programs.',
 'Latin American community group in Atlanta.',
 (select id from categories where slug = 'community'),
 'https://thelaa.org', '(404) 638-1800',
 '2750 Buford Hwy NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8225, -84.3210, '{es,en}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Mexican Consulate of Atlanta',
 'Mexican consular services for nationals — passports, IDs, legal assistance, and cultural programs.',
 'Mexican consulate serving Georgia and surrounding states.',
 (select id from categories where slug = 'community'),
 'https://consulmex.sre.gob.mx/atlanta', '(404) 266-2233',
 '1700 Chantilly Dr NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8133, -84.3454, '{es,en}', true, true, 'Mon — Fri 8am — 1pm appointments',
 false, false, false, true, true, true),

('Consulate General of India in Atlanta',
 'Indian consular services for nationals across the Southeast — passports, visas, and OCI services.',
 'Indian consulate serving the Southeast.',
 (select id from categories where slug = 'community'),
 'https://www.cgiatlanta.gov.in', '(404) 963-5902',
 '5549 Glenridge Dr NE, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.9009, -84.3551, '{en,hi}', false, false, 'Mon — Fri 9:30am — 12:30pm appointments',
 false, false, false, true, true, false),

-- ============== LEGAL — MORE LEGAL HELP ==============
('Georgia Legal Services Program',
 'Free civil legal aid for low-income Georgians in 154 counties outside metro Atlanta.',
 'Free civil legal aid outside Atlanta.',
 (select id from categories where slug = 'legal'),
 'https://www.glsp.org', '(404) 206-5175',
 '104 Marietta St NW Suite 250, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7546, -84.3911, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Federal Defender Program (Northern District of Georgia)',
 'Federal public defenders representing people charged with federal crimes who can''t afford a lawyer.',
 'Federal public defenders for N.D. Georgia.',
 (select id from categories where slug = 'legal'),
 'https://www.gan.fd.org', '(404) 688-7530',
 '101 Marietta St NW Suite 1500, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7553, -84.3942, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Southern Center for Human Rights',
 'Public-interest law firm representing people facing the death penalty and challenging conditions of confinement.',
 'Public-interest law firm — civil rights and justice.',
 (select id from categories where slug = 'legal'),
 'https://www.schr.org', '(404) 688-1202',
 '60 Walton St NW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7559, -84.3920, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Pro Bono Partnership of Atlanta',
 'Free business legal services for nonprofits serving low-income people in Atlanta.',
 'Free business legal services for nonprofits.',
 (select id from categories where slug = 'legal'),
 'https://pbpatl.org', '(404) 419-0533',
 '999 Peachtree St NE Suite 2300, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7895, -84.3848, '{en}', true, false, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Georgia Innocence Project',
 'Investigates and litigates wrongful conviction cases in Georgia.',
 'Investigates wrongful convictions in Georgia.',
 (select id from categories where slug = 'legal'),
 'https://www.georgiainnocenceproject.org', '(404) 373-4433',
 '2299 Henderson Mill Rd NE Suite 220, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.9012, -84.2842, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== EMPLOYMENT — MORE JOB HELP ==============
('Job Corps — Atlanta',
 'Free residential career training program for low-income youth ages 16–24.',
 'Free residential career training for youth 16–24.',
 (select id from categories where slug = 'employment'),
 'https://atlanta.jobcorps.gov', '(404) 728-1626',
 '239 W Lake Ave NW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7762, -84.4193, '{en,es}', true, true, 'Mon — Fri — see hours',
 false, false, false, true, true, true),

('JFCS Atlanta — Career Services',
 'Jewish Family & Career Services — career counseling and job-search help open to all.',
 'Career counseling and job search — open to all.',
 (select id from categories where slug = 'employment'),
 'https://www.jfcsatl.org', '(770) 677-9300',
 '4549 Chamblee Dunwoody Rd, Atlanta, GA 30338', 'Atlanta', 'GA', '30338',
 33.9344, -84.3097, '{en,es,he,ru}', false, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Catholic Charities — Refugee Resettlement & Career Services',
 'Refugee employment, training, and case management as part of Catholic Charities Atlanta.',
 'Refugee employment and case management.',
 (select id from categories where slug = 'employment'),
 'https://catholiccharitiesatlanta.org', '(678) 222-3920',
 '2401 Lake Park Dr SE, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8714, -84.4969, '{en,es,fr,ar,vi,fa,sw}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Atlanta CareerRise',
 'Workforce development partnership focused on connecting underemployed adults to better jobs.',
 'Workforce partnership for underemployed adults.',
 (select id from categories where slug = 'employment'),
 'https://atlantacareerrise.org', '(404) 614-1000',
 '50 Hurt Plaza SE Suite 449, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7541, -84.3866, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Refugee Career Hub',
 'Career services tailored to refugees — credential evaluation, English-for-work, and employer matching.',
 'Career services tailored to refugees.',
 (select id from categories where slug = 'employment'),
 'https://refugeecareerhub.org', '(404) 549-9914',
 '4170 E Ponce de Leon Ave, Clarkston, GA 30021', 'Clarkston', 'GA', '30021',
 33.8093, -84.2418, '{en,es,fr,ar,sw,fa,my,am,so,ne}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== FINANCIAL — MORE ==============
('Atlanta Habitat for Humanity',
 'Builds and rehabs affordable homes and offers homebuyer education for low-income families.',
 'Builds affordable homes; homebuyer education.',
 (select id from categories where slug = 'financial'),
 'https://www.atlantahabitat.org', '(404) 223-5180',
 '519 Memorial Dr SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7466, -84.3718, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Georgia United Credit Union',
 'Credit union open to those who live, work, worship, or attend school in many Georgia counties.',
 'Statewide credit union — accounts and loans.',
 (select id from categories where slug = 'financial'),
 'https://www.gucu.org', '(770) 476-6400',
 '6705 Sugarloaf Pkwy, Duluth, GA 30097', 'Duluth', 'GA', '30097',
 33.9871, -84.0901, '{en,es}', false, true, 'Mon — Fri 9am — 6pm; Sat 9am — 1pm',
 true, true, true, true, true, false),

('Atlanta Postal Credit Union',
 'Member-owned credit union open to people who live or work in metro Atlanta.',
 'Metro Atlanta credit union — accounts and loans.',
 (select id from categories where slug = 'financial'),
 'https://www.apcu.com', '(404) 768-4126',
 '3900 Crown Rd SW, Atlanta, GA 30380', 'Atlanta', 'GA', '30380',
 33.6481, -84.4334, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Latino Community Credit Union',
 'Bilingual credit union focused on serving Latino and immigrant families with affordable banking.',
 'Bilingual credit union for Latino families.',
 (select id from categories where slug = 'financial'),
 'https://latinoccu.org', '(919) 595-8170',
 '6055 Buford Hwy NE, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.9082, -84.2773, '{es,en}', false, true, 'Mon — Fri 9am — 6pm',
 true, true, true, true, true, true),

('Inversant',
 'College-savings coaching for first-generation immigrant families to plan financially for higher education.',
 'College-savings coaching for immigrant families.',
 (select id from categories where slug = 'financial'),
 'https://inversant.org', '(617) 209-8901',
 'Atlanta — multiple sites', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, true, true, true, false),

-- ============== FAMILY — MORE ==============
('Wellroot Family Services',
 'Foster care, adoption, and family preservation services rooted in the United Methodist Church.',
 'Foster care and family preservation services.',
 (select id from categories where slug = 'family'),
 'https://www.wellroot.org', '(770) 410-6900',
 '1967 Lakeside Pkwy Suite 400, Tucker, GA 30084', 'Tucker', 'GA', '30084',
 33.8534, -84.2167, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Families First',
 'Counseling, foster care, parenting support, and behavioral health services across metro Atlanta.',
 'Counseling, foster care, and parenting support.',
 (select id from categories where slug = 'family'),
 'https://www.familiesfirst.org', '(404) 853-2800',
 '80 Joseph E Lowery Blvd NW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7559, -84.4146, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 false, false, false, true, true, false),

('Camp Twin Lakes',
 'Year-round camping experiences for children with serious illnesses, disabilities, and life challenges.',
 'Camp for children with illnesses and disabilities.',
 (select id from categories where slug = 'family'),
 'https://www.camptwinlakes.org', '(404) 231-9887',
 '600 Means St NW Suite 110, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7689, -84.4029, '{en,es}', true, true, 'Year-round programs',
 false, false, false, true, true, false),

('Edgewood Center for Children and Families',
 'Children''s residential services and outpatient mental health support.',
 'Children''s residential and mental health services.',
 (select id from categories where slug = 'family'),
 'https://www.theedgewoodcenter.org', '(404) 622-2434',
 '1559 Memorial Dr SE, Atlanta, GA 30317', 'Atlanta', 'GA', '30317',
 33.7505, -84.3422, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('CASA — Child Advocates',
 'Court Appointed Special Advocates speak up for abused and neglected children in Georgia courts.',
 'Court advocates for abused children.',
 (select id from categories where slug = 'family'),
 'https://gacasa.org', '(404) 874-2888',
 '17 Executive Park Dr NE Suite 410, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8260, -84.3300, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== WOMEN'S — MORE ==============
('Dress for Success Atlanta',
 'Provides professional attire and career development for women entering the workforce.',
 'Free professional clothing for working women.',
 (select id from categories where slug = 'womens'),
 'https://atlanta.dressforsuccess.org', '(404) 525-0023',
 '15 Bennett St NW Suite C-50, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.8123, -84.3964, '{en,es}', true, true, 'By appointment',
 false, false, false, true, true, true),

('Refugee Women''s Network',
 'Empowerment programs, leadership training, and advocacy for refugee women in Georgia.',
 'Leadership programs for refugee women.',
 (select id from categories where slug = 'womens'),
 'https://www.refugeewomensnetworkinc.org', '(404) 299-5009',
 '4151 Memorial Dr Suite 200B, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7672, -84.2415, '{en,es,fr,ar,sw,fa,my,am,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Atlanta Women''s Foundation',
 'Funds and supports nonprofits that serve women and girls in metro Atlanta.',
 'Funder of women & girls nonprofits in Atlanta.',
 (select id from categories where slug = 'womens'),
 'https://www.atlantawomen.org', '(404) 588-3000',
 '230 Peachtree St NW Suite 1750, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7587, -84.3878, '{en}', true, false, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Susan G. Komen Greater Atlanta',
 'Breast cancer education, screening assistance, and patient navigation in metro Atlanta.',
 'Breast cancer education and screening help.',
 (select id from categories where slug = 'womens'),
 'https://komenatlanta.org', '(404) 814-0052',
 '950 East Paces Ferry Rd NE Suite 3100, Atlanta, GA 30326', 'Atlanta', 'GA', '30326',
 33.8455, -84.3681, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

-- ============== EMERGENCY — MORE ==============
('988 Suicide & Crisis Lifeline',
 '24/7 free, confidential support for people in suicidal crisis or emotional distress — call or text 988.',
 '24/7 crisis line — call or text 988.',
 (select id from categories where slug = 'emergency'),
 'https://988lifeline.org', '988',
 'Phone & text — nationwide', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es,zh,vi,ko,ar,fr,ru}', true, true, '24/7',
 false, true, true, true, true, true),

('Crisis Text Line',
 'Text-based 24/7 mental health crisis support — text HOME to 741741 from anywhere in the U.S.',
 '24/7 crisis text line — text HOME to 741741.',
 (select id from categories where slug = 'emergency'),
 'https://www.crisistextline.org', '741741',
 'Text-based — nationwide', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, false),

('National Domestic Violence Hotline',
 '24/7 confidential support for anyone affected by domestic violence — call or text START to 88788.',
 '24/7 DV hotline — call 1-800-799-7233.',
 (select id from categories where slug = 'emergency'),
 'https://www.thehotline.org', '(800) 799-7233',
 'Phone & text — nationwide', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es,zh,vi,ko,ar,fr,ru}', true, true, '24/7',
 false, true, true, true, true, true),

('Atlanta Police Department',
 'City of Atlanta police — emergency response (911), non-emergency line, and community policing.',
 'Atlanta Police — emergency 911, non-emergency line.',
 (select id from categories where slug = 'emergency'),
 'https://www.atlantapd.org', '(404) 614-6544',
 '226 Peachtree St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7522, -84.3914, '{en,es}', true, true, '24/7 emergency',
 true, true, true, true, true, false),

('Atlanta Fire Rescue Department',
 'City fire and emergency medical response — emergency 911, non-emergency administrative line.',
 'Atlanta Fire & EMS — emergency 911.',
 (select id from categories where slug = 'emergency'),
 'https://www.atlantaga.gov/government/departments/fire-rescue', '(404) 546-7000',
 '226 Peachtree St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7522, -84.3914, '{en,es}', true, true, '24/7 emergency',
 true, true, true, true, true, false),

-- ============== TRANSPORTATION — MORE ==============
('Greyhound — Atlanta Bus Station',
 'National long-distance bus service — Atlanta station near downtown.',
 'National long-distance bus service.',
 (select id from categories where slug = 'transportation'),
 'https://www.greyhound.com', '(404) 584-1731',
 '232 Forsyth St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7510, -84.3941, '{en,es}', false, true, '24/7 station',
 true, true, true, true, true, false),

('Megabus — Atlanta',
 'Low-cost intercity bus service to cities across the Southeast — Atlanta stop downtown.',
 'Low-cost intercity bus service.',
 (select id from categories where slug = 'transportation'),
 'https://us.megabus.com', '(877) 462-6342',
 '230 Spring St NW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7568, -84.3915, '{en,es}', false, true, 'See schedule',
 true, true, true, true, true, false),

('Atlanta Streetcar (MARTA)',
 '2.7-mile downtown streetcar loop connecting Centennial Olympic Park, Sweet Auburn, and the King Center.',
 'Downtown streetcar loop, $1 fare.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com/streetcar.aspx', '(404) 848-5000',
 'Centennial Olympic Park to King Center, Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7565, -84.3833, '{en,es}', false, true, 'Mon — Sun — see schedule',
 true, true, true, true, true, false),

('Amtrak — Atlanta Brookwood Station',
 'Daily Crescent train service between New York City and New Orleans — Atlanta stop.',
 'Daily Amtrak service to NYC and New Orleans.',
 (select id from categories where slug = 'transportation'),
 'https://www.amtrak.com', '(800) 872-7245',
 '1688 Peachtree St NW, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7973, -84.3854, '{en,es}', false, true, 'Daily train service',
 true, true, true, true, true, false),

('MARTA Mobility',
 'MARTA''s ADA-required paratransit service for people with disabilities who can''t use fixed-route bus or rail.',
 'Paratransit for riders with disabilities.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com/mobility.aspx', '(404) 848-5826',
 '2424 Piedmont Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8147, -84.3640, '{en,es}', false, true, 'Mon — Fri 8am — 5pm reservations',
 false, false, false, true, true, false),

-- ============== LIBRARIES — MORE BRANCHES & TECH ==============
('Forsyth County Public Library — Cumming',
 'Forsyth County''s main library — books, computers, internet, kids and adult programming.',
 'Main Forsyth County library in Cumming.',
 (select id from categories where slug = 'libraries'),
 'https://www.forsythpl.org', '(770) 781-9840',
 '585 Dahlonega Hwy, Cumming, GA 30040', 'Cumming', 'GA', '30040',
 34.2104, -84.1407, '{en,es,zh,ko}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Henry County Library System',
 'Public library serving Henry County — books, computers, internet, programs.',
 'Henry County public library system.',
 (select id from categories where slug = 'libraries'),
 'https://hcls.libguides.com', '(770) 957-7232',
 '1001 Florence McGarity Blvd, McDonough, GA 30252', 'McDonough', 'GA', '30252',
 33.4438, -84.1378, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Hall County Library System',
 'Public library serving Hall County — books, computers, internet, programs in multiple languages.',
 'Hall County public library system.',
 (select id from categories where slug = 'libraries'),
 'https://www.hallcountylibrary.org', '(770) 532-3311',
 '127 Main St NW, Gainesville, GA 30501', 'Gainesville', 'GA', '30501',
 34.2998, -83.8254, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Athens-Clarke County Library',
 'Public library in Athens — books, computers, internet, classes, and meeting spaces.',
 'Athens-Clarke County public library.',
 (select id from categories where slug = 'libraries'),
 'https://athenslibrary.org', '(706) 613-3650',
 '2025 Baxter St, Athens, GA 30606', 'Athens', 'GA', '30606',
 33.9495, -83.4036, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Buckhead Branch — Atlanta-Fulton Public Library',
 'AFPL branch in Buckhead — books, computers, internet, kids and adult programs.',
 'AFPL branch library in Buckhead.',
 (select id from categories where slug = 'libraries'),
 'https://afpls.org/locations/buckhead', '(404) 814-3500',
 '269 Buckhead Ave NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8400, -84.3776, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Ponce de Leon Branch — Atlanta-Fulton Public Library',
 'AFPL branch on Ponce de Leon — books, computers, internet, programs.',
 'AFPL branch on Ponce de Leon.',
 (select id from categories where slug = 'libraries'),
 'https://afpls.org/locations/ponce', '(404) 885-7820',
 '980 Ponce de Leon Ave NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7728, -84.3641, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('East Atlanta Branch — Atlanta-Fulton Public Library',
 'AFPL branch in East Atlanta Village — books, computers, internet, programs.',
 'AFPL branch in East Atlanta Village.',
 (select id from categories where slug = 'libraries'),
 'https://afpls.org/locations/east-atlanta', '(404) 730-5436',
 '400 Flat Shoals Ave SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7423, -84.3469, '{en,es}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Stonecrest Branch — DeKalb County Public Library',
 'DCPL branch in Lithonia — books, computers, internet, multilingual programs.',
 'DeKalb library branch in Lithonia.',
 (select id from categories where slug = 'libraries'),
 'https://dekalblibrary.org/locations/stonecrest', '(770) 482-3828',
 '3123 Klondike Rd, Lithonia, GA 30038', 'Lithonia', 'GA', '30038',
 33.7050, -84.1131, '{en,es,fr}', true, true, 'Mon — Sat — see hours',
 true, true, false, true, true, false),

('Tech Bridge Atlanta',
 'Free digital literacy and computer skills classes for adults across metro Atlanta.',
 'Free adult digital literacy and computer classes.',
 (select id from categories where slug = 'libraries'),
 'https://techbridge.org', '(404) 879-0079',
 '1325 Spring St NW Suite 200, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7860, -84.3902, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, true, true, true, false),

-- ============== EDUCATION — MORE UNIVERSITIES & COLLEGES ==============
('University of North Georgia',
 'Public university with five campuses across north Georgia — Dahlonega, Gainesville, Cumming, Oconee, Blue Ridge.',
 'Public university — five north Georgia campuses.',
 (select id from categories where slug = 'education'),
 'https://ung.edu', '(706) 864-1400',
 '82 College Cir, Dahlonega, GA 30597', 'Dahlonega', 'GA', '30597',
 34.5277, -83.9854, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('University of West Georgia',
 'Public university in Carrollton — undergraduate and graduate programs.',
 'Public university in Carrollton.',
 (select id from categories where slug = 'education'),
 'https://www.westga.edu', '(678) 839-5000',
 '1601 Maple St, Carrollton, GA 30118', 'Carrollton', 'GA', '30118',
 33.5715, -85.0954, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Middle Georgia State University',
 'Public university with campuses in Macon, Cochran, Dublin, Eastman, and Warner Robins.',
 'Public university — five middle Georgia campuses.',
 (select id from categories where slug = 'education'),
 'https://www.mga.edu', '(478) 471-2700',
 '100 University Pkwy, Macon, GA 31206', 'Macon', 'GA', '31206',
 32.8167, -83.6491, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Berry College',
 'Private liberal arts college in Mount Berry — one of the largest contiguous campuses in the world.',
 'Private liberal arts college in Mount Berry.',
 (select id from categories where slug = 'education'),
 'https://www.berry.edu', '(706) 232-5374',
 '2277 Martha Berry Hwy NW, Mount Berry, GA 30149', 'Mount Berry', 'GA', '30149',
 34.2773, -85.1815, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Reinhardt University',
 'Private United Methodist university in Waleska — small undergraduate liberal arts focus.',
 'Private United Methodist university in Waleska.',
 (select id from categories where slug = 'education'),
 'https://www.reinhardt.edu', '(770) 720-5526',
 '7300 Reinhardt Cir, Waleska, GA 30183', 'Waleska', 'GA', '30183',
 34.3185, -84.5499, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Wesleyan College',
 'Historic women''s liberal arts college in Macon — chartered 1836, oldest women''s college in the world.',
 'Historic women''s liberal arts college in Macon.',
 (select id from categories where slug = 'education'),
 'https://www.wesleyancollege.edu', '(478) 757-5206',
 '4760 Forsyth Rd, Macon, GA 31210', 'Macon', 'GA', '31210',
 32.8741, -83.7090, '{en,es,zh}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('LaGrange College',
 'Private United Methodist liberal arts college — Georgia''s oldest private college.',
 'Georgia''s oldest private college, in LaGrange.',
 (select id from categories where slug = 'education'),
 'https://www.lagrange.edu', '(706) 880-8000',
 '601 Broad St, LaGrange, GA 30240', 'LaGrange', 'GA', '30240',
 33.0379, -85.0356, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Young Harris College',
 'Private liberal arts college in Young Harris in the north Georgia mountains.',
 'Private liberal arts college in north Georgia.',
 (select id from categories where slug = 'education'),
 'https://www.yhc.edu', '(706) 379-3111',
 '1 College St, Young Harris, GA 30582', 'Young Harris', 'GA', '30582',
 34.9329, -83.8482, '{en}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, false),

('Georgia Highlands College',
 'Public access college serving northwest Georgia — Cartersville, Floyd, Marietta, and Paulding sites.',
 'Public access college, multiple NW Georgia sites.',
 (select id from categories where slug = 'education'),
 'https://www.highlands.edu', '(706) 802-5000',
 '3175 Cedartown Hwy SE, Rome, GA 30161', 'Rome', 'GA', '30161',
 34.2257, -85.1855, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Dalton State College',
 'Public access college in Dalton — undergraduate and associate degree programs.',
 'Public access college in Dalton.',
 (select id from categories where slug = 'education'),
 'https://www.daltonstate.edu', '(706) 272-4436',
 '650 College Dr, Dalton, GA 30720', 'Dalton', 'GA', '30720',
 34.7798, -84.9701, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('North Georgia Technical College',
 'Public technical college serving the north Georgia mountains — Clarkesville, Blairsville, Toccoa.',
 'Technical college in the north GA mountains.',
 (select id from categories where slug = 'education'),
 'https://www.northgatech.edu', '(706) 754-7700',
 '1500 Hwy 197 N, Clarkesville, GA 30523', 'Clarkesville', 'GA', '30523',
 34.6432, -83.5074, '{en}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Wiregrass Georgia Technical College',
 'Public technical college serving south-central Georgia — Valdosta main campus.',
 'Technical college in south Georgia.',
 (select id from categories where slug = 'education'),
 'https://www.wiregrass.edu', '(229) 333-2100',
 '4089 Val Tech Rd, Valdosta, GA 31602', 'Valdosta', 'GA', '31602',
 30.8845, -83.3262, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

-- ============== EDUCATION — MORE METRO ATLANTA SCHOOLS ==============
('Chamblee Charter High School',
 'DeKalb County charter high school in Chamblee — magnet program for high achievers, diverse student body.',
 'DeKalb charter high school with magnet program.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/chamblee-high', '(678) 676-6902',
 '3688 Chamblee Dunwoody Rd, Chamblee, GA 30341', 'Chamblee', 'GA', '30341',
 33.8920, -84.3030, '{en,es,zh,ko,vi,hi}', true, true, 'Mon — Fri 8:30am — 3:30pm',
 false, false, false, true, true, false),

('Riverwood International Charter School',
 'Fulton County charter high school in Sandy Springs — IB program and global focus.',
 'Fulton charter high school with IB program.',
 (select id from categories where slug = 'education'),
 'https://www.fultonschools.org/riverwoodhs', '(470) 254-2300',
 '5900 Heards Dr NW, Sandy Springs, GA 30328', 'Sandy Springs', 'GA', '30328',
 33.9193, -84.3935, '{en,es,zh,ko}', true, true, 'Mon — Fri 8:20am — 3:20pm',
 false, false, false, true, true, false),

('South Gwinnett High School',
 'Gwinnett County high school in Snellville — diverse student body and broad academic and athletic programs.',
 'Gwinnett high school in Snellville.',
 (select id from categories where slug = 'education'),
 'https://www.gcpsk12.org/southgwinnetths', '(770) 736-4100',
 '2288 Main St E, Snellville, GA 30078', 'Snellville', 'GA', '30078',
 33.8584, -84.0148, '{en,es,vi,ko}', true, true, 'Mon — Fri 7:20am — 2:20pm',
 false, false, false, true, true, false),

('Druid Hills Charter Cluster — Fernbank Elementary',
 'DeKalb County elementary school in the Druid Hills cluster — diverse student body.',
 'DeKalb elementary in Druid Hills cluster.',
 (select id from categories where slug = 'education'),
 'https://www.dekalbschoolsga.org/fernbank-elementary', '(678) 874-7202',
 '157 Heaton Park Dr NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7849, -84.3175, '{en,es}', true, true, 'Mon — Fri 7:45am — 2:30pm',
 false, false, false, true, true, false),

('Atlanta International School',
 'Independent international school offering IB curriculum from preschool through 12th grade.',
 'Independent IB school, preschool — 12.',
 (select id from categories where slug = 'education'),
 'https://www.aischool.org', '(404) 841-3840',
 '2890 N Fulton Dr NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8484, -84.3691, '{en,es,fr,de,zh}', false, true, 'Mon — Fri 8am — 3:30pm',
 false, false, false, true, true, false),

-- ============== PARKS — MORE STATE PARKS ==============
('Hard Labor Creek State Park',
 'State park in Rutledge with two lakes, hiking, golf, horseback riding, and camping.',
 'State park with lakes, golf, and camping.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/HardLaborCreek', '(706) 557-3001',
 '5 Hard Labor Creek Rd, Rutledge, GA 30663', 'Rutledge', 'GA', '30663',
 33.6779, -83.6043, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Skidaway Island State Park',
 'Coastal state park near Savannah — salt marshes, hiking trails, and camping.',
 'Coastal state park near Savannah.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/SkidawayIsland', '(912) 598-2300',
 '52 Diamond Causeway, Savannah, GA 31411', 'Savannah', 'GA', '31411',
 31.9436, -81.0573, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Crooked River State Park',
 'Coastal state park near St. Marys — fishing, hiking, kayaking, and cabins.',
 'Coastal state park with kayaking and cabins.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/CrookedRiver', '(912) 882-5256',
 '6222 Charlie Smith Sr Hwy, St. Marys, GA 31558', 'St. Marys', 'GA', '31558',
 30.8423, -81.5559, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Magnolia Springs State Park',
 'State park near Millen with crystal-clear springs, swimming, and fishing.',
 'State park with crystal-clear springs.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/MagnoliaSprings', '(478) 982-1660',
 '1053 Magnolia Springs Dr, Millen, GA 30442', 'Millen', 'GA', '30442',
 32.8771, -81.9613, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('George L. Smith State Park',
 'State park near Twin City with a 412-acre mill pond and historic 1880 grist mill.',
 'State park with mill pond and grist mill.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/GeorgeLSmith', '(478) 763-2759',
 '371 George L Smith State Park Rd, Twin City, GA 30471', 'Twin City', 'GA', '30471',
 32.5446, -82.1240, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Reed Bingham State Park',
 'State park in south Georgia with a 375-acre lake — boating, fishing, hiking, and camping.',
 'South GA state park with lake and camping.',
 (select id from categories where slug = 'parks'),
 'https://gastateparks.org/ReedBingham', '(229) 896-3551',
 '542 Reed Bingham Rd, Adel, GA 31620', 'Adel', 'GA', '31620',
 31.1582, -83.5340, '{en}', false, true, '7am — 10pm',
 true, true, false, true, true, false),

('Hartsfield-Jackson Atlanta — Information Center',
 'World''s busiest airport — public information desks, ground transportation, and SkyTrain.',
 'ATL airport public info and ground transit.',
 (select id from categories where slug = 'transportation'),
 'https://www.atl.com', '(800) 897-1910',
 '6000 N Terminal Pkwy, Atlanta, GA 30320', 'Atlanta', 'GA', '30320',
 33.6407, -84.4277, '{en,es,zh,vi,ko,ar,fr}', true, true, '24/7',
 true, true, true, true, true, false),

-- ============== HEALTHCARE — MORE COMMUNITY CLINICS ==============
('Mercy Care Decatur Street Clinic',
 'Federally qualified health center serving low-income, uninsured, and homeless people in metro Atlanta.',
 'Free clinic for uninsured and homeless people.',
 (select id from categories where slug = 'healthcare'),
 'https://www.mercyatlanta.org', '(678) 843-8500',
 '424 Decatur St SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7521, -84.3781, '{en,es}', true, true, 'Mon — Fri 7:30am — 5:30pm',
 true, false, false, true, true, true),

('Good Samaritan Health Center of Cobb',
 'Christian-based community health center serving uninsured, low-income people in Cobb County.',
 'Free clinic in Cobb County.',
 (select id from categories where slug = 'healthcare'),
 'https://goodsamcobb.org', '(770) 419-3120',
 '1605 Roberta Dr SW, Marietta, GA 30008', 'Marietta', 'GA', '30008',
 33.9034, -84.5664, '{en,es}', true, true, 'Mon — Thu 8am — 5pm',
 false, false, false, true, true, false),

('Hope Clinic',
 'Free medical and dental clinic for the uninsured in Lawrenceville.',
 'Free medical and dental clinic in Lawrenceville.',
 (select id from categories where slug = 'healthcare'),
 'https://hopeclinicgwinnett.org', '(770) 822-2723',
 '396 Crogan St, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9532, -83.9890, '{en,es}', true, true, 'Mon — Fri appointments',
 false, false, true, true, true, false)

on conflict do nothing;