-- 007_popular_resources.sql
-- Adds ~200 popular, highly-recognized, top-ranking Georgia resources.
-- Focus: household-name organizations people already know and choose —
-- major grocery chains, top private schools, megachurches, well-known
-- cultural institutions, large banks/credit unions, and the busiest
-- libraries, hospitals, and community orgs in metro Atlanta.
-- All entries are publicly known organizations. Ratings remain null
-- pending Google Places API integration.

insert into resources (
  name, description, short_description, category_id,
  website_url, phone, address, city, state, zip,
  latitude, longitude, languages, is_free, serves_undocumented, hours,
  walk_in_available, weekend_hours, evening_hours, phone_intake,
  is_verified, is_featured
) values

-- ============== FOOD — MAJOR GROCERY CHAINS ==============
('Kroger — Ponce de Leon',
 'One of the busiest Kroger supermarkets in Atlanta — full grocery, pharmacy, deli, and money services.',
 'Large Kroger with pharmacy and money services.',
 (select id from categories where slug = 'food'),
 'https://www.kroger.com', '(404) 875-2271',
 '725 Ponce De Leon Ave NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7727, -84.3651, '{en,es}', false, true, 'Daily 6am — 1am',
 true, true, true, true, true, true),

('Publix Super Market — Buckhead',
 'Top-rated Southeastern grocery chain known for clean stores, deli subs, and pharmacy services.',
 'Top-rated Southern grocery chain.',
 (select id from categories where slug = 'food'),
 'https://www.publix.com', '(404) 467-9700',
 '2625 Piedmont Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8235, -84.3719, '{en,es}', false, true, 'Daily 7am — 10pm',
 true, true, true, true, true, true),

('Publix Super Market — Toco Hills',
 'Popular Publix serving the Toco Hills area near Emory — kosher department, deli, and pharmacy.',
 'Publix near Emory with kosher department.',
 (select id from categories where slug = 'food'),
 'https://www.publix.com', '(404) 248-9090',
 '2969 N Druid Hills Rd NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8191, -84.3201, '{en,es}', false, true, 'Daily 7am — 10pm',
 true, true, true, true, true, false),

('Walmart Supercenter — Stone Mountain',
 'Full Walmart with grocery, pharmacy, MoneyGram, photo, and auto care.',
 'Walmart Supercenter with grocery and money services.',
 (select id from categories where slug = 'food'),
 'https://www.walmart.com', '(770) 879-5400',
 '1825 Rockbridge Rd SW, Stone Mountain, GA 30087', 'Stone Mountain', 'GA', '30087',
 33.8112, -84.1709, '{en,es}', false, true, 'Daily 6am — 11pm',
 true, true, true, true, true, false),

('Walmart Supercenter — Lilburn',
 'Full Walmart with grocery, pharmacy, MoneyGram wire transfer, and auto care.',
 'Walmart Supercenter in Lilburn.',
 (select id from categories where slug = 'food'),
 'https://www.walmart.com', '(770) 638-4133',
 '4004 Lawrenceville Hwy NW, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.8779, -84.1444, '{en,es}', false, true, 'Daily 6am — 11pm',
 true, true, true, true, true, false),

('ALDI — Buford Highway',
 'Low-cost grocery store known for affordable produce, dairy, and pantry staples.',
 'Affordable grocery store with low prices.',
 (select id from categories where slug = 'food'),
 'https://www.aldi.us', '(800) 325-7894',
 '4166 Buford Hwy NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8585, -84.2924, '{en,es}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, true),

('ALDI — Decatur',
 'Low-cost grocery chain with affordable produce, meat, and pantry items.',
 'Affordable grocery store in Decatur.',
 (select id from categories where slug = 'food'),
 'https://www.aldi.us', '(800) 325-7894',
 '3705 Memorial Dr, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7682, -84.2469, '{en,es}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, false),

('Costco Wholesale — Brookhaven',
 'Membership warehouse club with bulk groceries, pharmacy, gas, optical, and tires.',
 'Bulk warehouse club with groceries and pharmacy.',
 (select id from categories where slug = 'food'),
 'https://www.costco.com', '(404) 568-2300',
 '500 Town Blvd NE, Brookhaven, GA 30319', 'Brookhaven', 'GA', '30319',
 33.8639, -84.3376, '{en,es,zh,ko}', false, true, 'Mon — Fri 10am — 8:30pm, Sat 9:30am — 6pm, Sun 10am — 6pm',
 true, true, true, true, true, true),

('Sam''s Club — Morrow',
 'Membership warehouse with bulk groceries, pharmacy, gas, and optical.',
 'Bulk warehouse club with groceries.',
 (select id from categories where slug = 'food'),
 'https://www.samsclub.com', '(770) 968-7900',
 '6065 Jonesboro Rd, Morrow, GA 30260', 'Morrow', 'GA', '30260',
 33.5754, -84.3287, '{en,es}', false, true, 'Mon — Fri 10am — 8pm, Sat 9am — 8pm, Sun 10am — 6pm',
 true, true, true, true, true, false),

('Whole Foods Market — Buckhead',
 'Premium organic and natural grocery store — produce, prepared foods, and wellness.',
 'Premium organic grocery store.',
 (select id from categories where slug = 'food'),
 'https://www.wholefoodsmarket.com', '(404) 760-6500',
 '77 W Paces Ferry Rd NW, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8412, -84.3854, '{en,es}', false, true, 'Daily 8am — 10pm',
 true, true, true, true, true, false),

('Trader Joe''s — Midtown',
 'Specialty grocery store with affordable signature snacks, frozen meals, and wines.',
 'Affordable specialty grocery store.',
 (select id from categories where slug = 'food'),
 'https://www.traderjoes.com', '(404) 815-9210',
 '931 Monroe Dr NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7825, -84.3756, '{en,es}', false, true, 'Daily 8am — 9pm',
 true, true, true, true, true, false),

('H Mart — Suwanee',
 'Large Korean and pan-Asian supermarket — fresh produce, seafood, banchan, and bakery.',
 'Large Korean and Asian supermarket.',
 (select id from categories where slug = 'food'),
 'https://www.hmart.com', '(770) 614-9991',
 '2700 Lawrenceville-Suwanee Rd, Suwanee, GA 30024', 'Suwanee', 'GA', '30024',
 34.0512, -84.0729, '{en,ko,zh,vi}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, true),

('H Mart — Duluth',
 'Korean and pan-Asian supermarket with fresh produce, seafood, kimchi, and food court.',
 'Korean and Asian supermarket in Duluth.',
 (select id from categories where slug = 'food'),
 'https://www.hmart.com', '(678) 957-1000',
 '2550 Pleasant Hill Rd, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 33.9799, -84.1452, '{en,ko,zh,vi}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, false),

('Lotte Plaza Market — Duluth',
 'Korean supermarket chain with extensive Asian groceries, banchan, and a food court.',
 'Korean supermarket with food court.',
 (select id from categories where slug = 'food'),
 'https://lotteplaza.com', '(770) 623-2900',
 '3505 Old Norcross Rd, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 33.9885, -84.1427, '{en,ko,zh}', false, true, 'Daily 8am — 10pm',
 true, true, true, true, true, false),

('Patel Brothers — Suwanee',
 'Largest Indian-American grocery chain — spices, lentils, fresh Indian produce, and frozen foods.',
 'Indian grocery store in Suwanee.',
 (select id from categories where slug = 'food'),
 'https://www.patelbros.com', '(770) 866-9090',
 '1707 Lawrenceville-Suwanee Rd, Suwanee, GA 30024', 'Suwanee', 'GA', '30024',
 34.0429, -84.0750, '{en,hi,gu,ta,bn,ur}', false, true, 'Daily 9am — 9pm',
 true, true, true, true, true, true),

('Buford Highway International Mall',
 'Multi-cultural mall on Buford Highway with Korean, Chinese, Vietnamese, and Latin American shops.',
 'Multicultural mall on Buford Highway.',
 (select id from categories where slug = 'food'),
 'https://www.buford-hwy.com', null,
 '5150 Buford Hwy NE, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.8930, -84.2828, '{en,es,zh,ko,vi}', false, true, 'Mon — Sun 10am — 9pm',
 true, true, true, false, true, false),

('Mediterranean Grill & Grocery',
 'Halal Middle Eastern grocery with butcher, fresh pita, olives, and Middle Eastern pantry.',
 'Halal Middle Eastern grocery and butcher.',
 (select id from categories where slug = 'food'),
 'https://mediterraneangrillatl.com', '(404) 320-0101',
 '2257 Cheshire Bridge Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8158, -84.3492, '{en,ar,fa,tr}', false, true, 'Mon — Sat 10am — 9pm, Sun 11am — 7pm',
 true, true, true, false, true, false),

('Walmart Supercenter — Riverdale',
 'Full Walmart with grocery, pharmacy, MoneyGram, and Walmart.com pickup.',
 'Walmart Supercenter in Riverdale.',
 (select id from categories where slug = 'food'),
 'https://www.walmart.com', '(770) 994-2079',
 '7050 Highway 85, Riverdale, GA 30274', 'Riverdale', 'GA', '30274',
 33.5660, -84.4116, '{en,es}', false, true, 'Daily 6am — 11pm',
 true, true, true, true, true, false),

('Kroger — Edgewood Retail District',
 'Large Kroger with pharmacy, deli, and Money Services for wire transfers and check cashing.',
 'Large Kroger with money services.',
 (select id from categories where slug = 'food'),
 'https://www.kroger.com', '(404) 525-4347',
 '1225 Caroline St NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7634, -84.3523, '{en,es}', false, true, 'Daily 6am — 1am',
 true, true, true, true, true, false),

-- ============== HEALTHCARE — MAJOR HOSPITALS & SYSTEMS ==============
('Children''s Healthcare of Atlanta — Egleston',
 'Top-ranked pediatric hospital on the Emory campus — emergency, surgery, and specialty pediatric care.',
 'Top pediatric hospital on Emory campus.',
 (select id from categories where slug = 'healthcare'),
 'https://www.choa.org', '(404) 785-6000',
 '1405 Clifton Rd NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7920, -84.3215, '{en,es,zh,ko,vi,ar}', false, true, '24/7',
 true, true, true, true, true, true),

('Children''s Healthcare of Atlanta — Hughes Spalding',
 'Pediatric hospital downtown serving Grady''s patient population — pediatric primary, urgent, and specialty care.',
 'Pediatric hospital downtown.',
 (select id from categories where slug = 'healthcare'),
 'https://www.choa.org', '(404) 785-9930',
 '35 Jesse Hill Jr Dr SE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7507, -84.3818, '{en,es}', false, true, '24/7',
 true, true, true, true, true, true),

('Children''s Healthcare of Atlanta — Arthur M. Blank Hospital',
 'New flagship pediatric hospital in North Druid Hills — emergency, surgery, and specialty care.',
 'New flagship pediatric hospital.',
 (select id from categories where slug = 'healthcare'),
 'https://www.choa.org', '(404) 785-6000',
 '2220 N Druid Hills Rd NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.8189, -84.3158, '{en,es,zh,ko,vi,ar}', false, true, '24/7',
 true, true, true, true, true, true),

('Northeast Georgia Medical Center — Gainesville',
 'Largest hospital in Northeast Georgia — Level II trauma center, heart and stroke care.',
 'Largest hospital in Northeast Georgia.',
 (select id from categories where slug = 'healthcare'),
 'https://www.nghs.com', '(770) 219-9000',
 '743 Spring St NE, Gainesville, GA 30501', 'Gainesville', 'GA', '30501',
 34.3071, -83.8167, '{en,es,vi,ko}', false, true, '24/7',
 true, true, true, true, true, true),

('Wellstar Atlanta Medical Center South',
 'Wellstar community hospital in East Point — emergency, surgery, and inpatient care.',
 'Wellstar community hospital in East Point.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org', '(404) 466-1170',
 '1170 Cleveland Ave, East Point, GA 30344', 'East Point', 'GA', '30344',
 33.6713, -84.4477, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Wellstar North Fulton Hospital',
 'Wellstar community hospital in Roswell — emergency, surgery, maternity, and cancer care.',
 'Wellstar hospital in Roswell.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org', '(770) 751-2500',
 '3000 Hospital Blvd, Roswell, GA 30076', 'Roswell', 'GA', '30076',
 34.0479, -84.3267, '{en,es,ko,zh}', false, true, '24/7',
 true, true, true, true, true, true),

('Wellstar Douglas Hospital',
 'Wellstar community hospital in Douglasville — emergency and inpatient services.',
 'Wellstar hospital in Douglasville.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org', '(770) 920-6100',
 '8954 Hospital Dr, Douglasville, GA 30134', 'Douglasville', 'GA', '30134',
 33.7547, -84.7551, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Wellstar Paulding Hospital',
 'Wellstar community hospital in Hiram — emergency, surgery, and inpatient care.',
 'Wellstar hospital in Hiram.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org', '(470) 644-7000',
 '2518 Jimmy Lee Smith Pkwy, Hiram, GA 30141', 'Hiram', 'GA', '30141',
 33.8665, -84.7658, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Wellstar Spalding Medical Center',
 'Wellstar community hospital in Griffin — Level III trauma, emergency, and inpatient care.',
 'Wellstar hospital in Griffin.',
 (select id from categories where slug = 'healthcare'),
 'https://www.wellstar.org', '(770) 228-2721',
 '601 S 8th St, Griffin, GA 30224', 'Griffin', 'GA', '30224',
 33.2398, -84.2666, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Northside Hospital Gwinnett',
 'Large Northside hospital in Lawrenceville — emergency, surgery, oncology, and maternity.',
 'Northside hospital in Lawrenceville.',
 (select id from categories where slug = 'healthcare'),
 'https://www.northside.com', '(678) 312-1000',
 '1000 Medical Center Blvd, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9460, -83.9974, '{en,es,vi,ko}', false, true, '24/7',
 true, true, true, true, true, true),

('Northside Hospital Duluth',
 'Northside community hospital in Duluth — emergency, surgery, and inpatient services.',
 'Northside hospital in Duluth.',
 (select id from categories where slug = 'healthcare'),
 'https://www.northside.com', '(678) 312-6800',
 '3620 Howell Ferry Rd, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 33.9912, -84.1378, '{en,es,zh,ko,vi}', false, true, '24/7',
 true, true, true, true, true, false),

('Piedmont Eastside Medical Center',
 'Piedmont community hospital in Snellville — emergency, surgery, and inpatient care.',
 'Piedmont hospital in Snellville.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org', '(770) 979-0200',
 '1700 Medical Way, Snellville, GA 30078', 'Snellville', 'GA', '30078',
 33.8651, -84.0007, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Piedmont Mountainside Hospital',
 'Piedmont community hospital in Jasper — emergency, inpatient, and specialty care.',
 'Piedmont hospital in Jasper.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org', '(706) 692-2441',
 '1266 Highway 515 S, Jasper, GA 30143', 'Jasper', 'GA', '30143',
 34.4582, -84.4344, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('Piedmont Rockdale Hospital',
 'Piedmont community hospital in Conyers — emergency, surgery, and inpatient services.',
 'Piedmont hospital in Conyers.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org', '(770) 918-3000',
 '1412 Milstead Ave NE, Conyers, GA 30012', 'Conyers', 'GA', '30012',
 33.6809, -84.0067, '{en,es}', false, true, '24/7',
 true, true, true, true, true, false),

('CVS MinuteClinic — Decatur',
 'Walk-in retail clinic for minor illness, vaccinations, physicals, and TB tests — sliding fees.',
 'Walk-in retail clinic for minor care.',
 (select id from categories where slug = 'healthcare'),
 'https://www.cvs.com/minuteclinic', '(404) 297-1330',
 '2480 N Decatur Rd, Decatur, GA 30033', 'Decatur', 'GA', '30033',
 33.7728, -84.2882, '{en,es}', false, true, 'Mon — Fri 8:30am — 7:30pm, Sat — Sun 9am — 5pm',
 true, true, true, true, true, false),

('Walgreens Healthcare Clinic — Lawrenceville',
 'Walk-in clinic inside Walgreens for minor illness, vaccines, physicals, and travel health.',
 'Walk-in clinic inside Walgreens.',
 (select id from categories where slug = 'healthcare'),
 'https://www.walgreens.com', '(770) 277-7333',
 '585 Old Norcross Rd, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9551, -83.9973, '{en,es}', false, true, 'Mon — Fri 8am — 8pm, Sat — Sun 9am — 5pm',
 true, true, true, true, true, false),

-- ============== EDUCATION — TOP PRIVATE & MAGNET SCHOOLS ==============
('The Westminster Schools',
 'Top-ranked independent K — 12 Christian school in Buckhead — academically among the strongest in Georgia.',
 'Top independent K-12 school in Buckhead.',
 (select id from categories where slug = 'education'),
 'https://www.westminster.net', '(404) 355-8673',
 '1424 W Paces Ferry Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8407, -84.4179, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, true),

('Pace Academy',
 'Top independent K — 12 college-preparatory school in Buckhead — known for academics, arts, and athletics.',
 'Top independent K-12 school in Buckhead.',
 (select id from categories where slug = 'education'),
 'https://www.paceacademy.org', '(404) 262-1345',
 '966 W Paces Ferry Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8443, -84.4068, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, true),

('The Lovett School',
 'Independent K — 12 college-preparatory school on a wooded campus along the Chattahoochee River.',
 'Top independent K-12 school in Buckhead.',
 (select id from categories where slug = 'education'),
 'https://www.lovett.org', '(404) 262-3032',
 '4075 Paces Ferry Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8617, -84.4546, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, true),

('Marist School',
 'Top Catholic independent 7 — 12 school in Brookhaven — academic and athletic excellence.',
 'Top Catholic 7-12 school in Brookhaven.',
 (select id from categories where slug = 'education'),
 'https://www.marist.com', '(770) 457-7201',
 '3790 Ashford Dunwoody Rd NE, Atlanta, GA 30319', 'Atlanta', 'GA', '30319',
 33.8941, -84.3382, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Holy Innocents'' Episcopal School',
 'Independent K — 12 Episcopal school in Sandy Springs — strong academics and arts.',
 'Top independent K-12 Episcopal school.',
 (select id from categories where slug = 'education'),
 'https://www.hies.org', '(404) 255-4026',
 '805 Mt Vernon Hwy NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.9197, -84.4132, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Greater Atlanta Christian School',
 'Independent K — 12 Christian school in Norcross — large multicultural student body.',
 'Independent K-12 Christian school.',
 (select id from categories where slug = 'education'),
 'https://www.greateratlantachristian.org', '(770) 243-2000',
 '1575 Indian Trail Rd NW, Norcross, GA 30093', 'Norcross', 'GA', '30093',
 33.9479, -84.1899, '{en,ko,es}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Wesleyan School',
 'Independent K — 12 Christian school in Peachtree Corners — known for academics and athletics.',
 'Independent K-12 Christian school.',
 (select id from categories where slug = 'education'),
 'https://www.wesleyanschool.org', '(770) 448-7640',
 '5405 Spalding Dr, Peachtree Corners, GA 30092', 'Peachtree Corners', 'GA', '30092',
 33.9839, -84.2245, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Mount Vernon School',
 'Independent K — 12 college-prep school in Sandy Springs known for design-thinking curriculum.',
 'Independent K-12 with design-thinking focus.',
 (select id from categories where slug = 'education'),
 'https://www.mountvernonschool.org', '(404) 252-3448',
 '510 Mt Vernon Hwy NE, Sandy Springs, GA 30328', 'Sandy Springs', 'GA', '30328',
 33.9282, -84.3796, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('St. Pius X Catholic High School',
 'Top Catholic high school in Atlanta — strong academics and large Latino student body.',
 'Top Catholic high school in Atlanta.',
 (select id from categories where slug = 'education'),
 'https://www.spx.org', '(404) 636-3023',
 '2674 Johnson Rd NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8519, -84.3074, '{en,es}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Blessed Trinity Catholic High School',
 'Catholic high school in Roswell — strong academics, athletics, and faith formation.',
 'Catholic high school in Roswell.',
 (select id from categories where slug = 'education'),
 'https://www.btcatholic.org', '(678) 452-4500',
 '11320 Woodstock Rd, Roswell, GA 30075', 'Roswell', 'GA', '30075',
 34.0573, -84.4006, '{en,es}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('The Galloway School',
 'Progressive K — 12 independent school in Buckhead known for individualized learning.',
 'Progressive K-12 independent school.',
 (select id from categories where slug = 'education'),
 'https://www.gallowayschool.org', '(404) 252-8389',
 '215 W Wieuca Rd NW, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.8829, -84.3756, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Atlanta Girls'' School',
 'All-girls 6 — 12 independent school focused on leadership and STEAM.',
 'All-girls 6-12 independent school.',
 (select id from categories where slug = 'education'),
 'https://www.atlantagirlsschool.org', '(404) 845-0900',
 '3254 Northside Pkwy NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8499, -84.4339, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Notre Dame Academy — Duluth',
 'Catholic Pre-K through 12 school in Duluth — strong academics and faith formation.',
 'Catholic Pre-K to 12 school in Duluth.',
 (select id from categories where slug = 'education'),
 'https://www.ndacademy.org', '(770) 814-4244',
 '4635 River Green Pkwy, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 34.0058, -84.1244, '{en,es,ko}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Mount Pisgah Christian School',
 'Independent K — 12 Christian school in Johns Creek — strong academics and athletics.',
 'Independent K-12 Christian school.',
 (select id from categories where slug = 'education'),
 'https://www.mountpisgahschool.org', '(678) 336-3300',
 '9820 Nesbit Ferry Rd, Johns Creek, GA 30022', 'Johns Creek', 'GA', '30022',
 34.0286, -84.2476, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('King''s Ridge Christian School',
 'Independent K — 12 Christian school in Alpharetta — academic and athletic programs.',
 'Independent K-12 Christian school.',
 (select id from categories where slug = 'education'),
 'https://www.kingsridgecs.org', '(770) 754-5738',
 '2765 Bethany Bend, Milton, GA 30004', 'Milton', 'GA', '30004',
 34.1012, -84.3128, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('The Paideia School',
 'Independent K — 12 progressive school near Druid Hills — small classes, project-based learning.',
 'Progressive K-12 independent school.',
 (select id from categories where slug = 'education'),
 'https://www.paideiaschool.org', '(404) 377-3491',
 '1509 Ponce de Leon Ave NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7726, -84.3329, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Atlanta International School (AIS)',
 'IB Pre-K to 12 international school with multilingual education in French, Spanish, German, and Mandarin.',
 'IB Pre-K to 12 multilingual school.',
 (select id from categories where slug = 'education'),
 'https://www.aischool.org', '(404) 841-3840',
 '2890 N Fulton Dr NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8388, -84.3658, '{en,es,fr,de,zh}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Woodward Academy',
 'Largest independent school in the continental U.S. — Pre-K to 12 in College Park.',
 'Largest independent school in continental US.',
 (select id from categories where slug = 'education'),
 'https://www.woodward.edu', '(404) 765-8200',
 '1662 Rugby Ave, College Park, GA 30337', 'College Park', 'GA', '30337',
 33.6606, -84.4502, '{en,es,zh,ko}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

('Mill Springs Academy',
 'Independent K — 12 school in Alpharetta for students with learning differences.',
 'Independent K-12 school for learning differences.',
 (select id from categories where slug = 'education'),
 'https://www.millsprings.org', '(770) 360-1336',
 '13660 New Providence Rd, Alpharetta, GA 30004', 'Alpharetta', 'GA', '30004',
 34.1311, -84.3169, '{en}', false, true, 'Mon — Fri 8am — 4pm',
 true, false, false, true, true, false),

-- ============== FAITH — POPULAR PLACES OF WORSHIP ==============
('12Stone Church — Lawrenceville',
 'Large multi-site evangelical megachurch with kids, student, and Spanish-language ministries.',
 'Large multi-site evangelical megachurch.',
 (select id from categories where slug = 'faith'),
 'https://www.12stone.com', '(770) 282-6940',
 '1322 Buford Dr, Lawrenceville, GA 30043', 'Lawrenceville', 'GA', '30043',
 34.0014, -83.9748, '{en,es,ko}', true, true, 'Sun services — see website',
 true, true, true, true, true, true),

('Free Chapel — Gainesville',
 'Large multi-site nondenominational megachurch led by Pastor Jentezen Franklin — kids and youth ministries.',
 'Large multi-site nondenominational megachurch.',
 (select id from categories where slug = 'faith'),
 'https://www.freechapel.org', '(678) 677-1010',
 '3001 McEver Rd, Gainesville, GA 30504', 'Gainesville', 'GA', '30504',
 34.2582, -83.8775, '{en,es}', true, true, 'Sun services — see website',
 true, true, true, true, true, true),

('Mount Paran Church',
 'Large nondenominational church in Buckhead with strong music, youth, and missions ministries.',
 'Large nondenominational church in Buckhead.',
 (select id from categories where slug = 'faith'),
 'https://www.mtparan.com', '(404) 261-0720',
 '2055 Mount Paran Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8625, -84.4316, '{en,es}', true, true, 'Sun services — see website',
 true, true, true, true, true, false),

('First Baptist Church Atlanta',
 'Historic Southern Baptist megachurch in Dunwoody led by Charles Stanley — broadcasts globally.',
 'Historic Southern Baptist megachurch.',
 (select id from categories where slug = 'faith'),
 'https://fba.org', '(770) 234-2300',
 '4400 N Peachtree Rd, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9302, -84.3192, '{en}', true, true, 'Sun services — see website',
 true, true, false, true, true, false),

('New Birth Missionary Baptist Church',
 'Large historically Black Baptist megachurch in Lithonia — strong community outreach and youth programs.',
 'Large Black Baptist megachurch in Lithonia.',
 (select id from categories where slug = 'faith'),
 'https://www.newbirth.org', '(770) 696-9600',
 '6400 Woodrow Rd, Lithonia, GA 30038', 'Lithonia', 'GA', '30038',
 33.6912, -84.0844, '{en}', true, true, 'Sun services — see website',
 true, true, true, true, true, true),

('Andy Stanley''s Buckhead Church',
 'North Point Ministries campus in Buckhead — known for accessible weekend services.',
 'North Point campus in Buckhead.',
 (select id from categories where slug = 'faith'),
 'https://buckheadchurch.org', '(404) 240-0100',
 '3098 Piedmont Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8385, -84.3702, '{en}', true, true, 'Sun services 9am, 11am',
 true, true, false, true, true, false),

('Browns Bridge Church',
 'North Point Ministries campus in Cumming — modern weekend services and family ministries.',
 'North Point campus in Cumming.',
 (select id from categories where slug = 'faith'),
 'https://brownsbridge.org', '(770) 887-7995',
 '3000 Browns Bridge Rd, Cumming, GA 30041', 'Cumming', 'GA', '30041',
 34.1893, -84.1075, '{en}', true, true, 'Sun services 9am, 11am',
 true, true, false, true, true, false),

('Peachtree City United Methodist Church',
 'Large United Methodist congregation south of Atlanta with strong youth and music programs.',
 'Large UMC congregation south of Atlanta.',
 (select id from categories where slug = 'faith'),
 'https://www.ptcumc.org', '(770) 487-7215',
 '203 W Newnan Rd, Peachtree City, GA 30269', 'Peachtree City', 'GA', '30269',
 33.3912, -84.5957, '{en}', true, true, 'Sun services — see website',
 true, true, false, true, true, false),

('Wieuca Road Baptist Church',
 'Historic Buckhead Baptist church with diverse congregation and missions emphasis.',
 'Historic Buckhead Baptist church.',
 (select id from categories where slug = 'faith'),
 'https://wieuca.org', '(404) 252-1657',
 '3626 Peachtree Rd NE, Atlanta, GA 30326', 'Atlanta', 'GA', '30326',
 33.8649, -84.3631, '{en}', true, true, 'Sun services — see website',
 true, true, false, true, true, false),

('Big Bethel AME Church',
 'Historic African Methodist Episcopal church on Auburn Avenue — civil-rights heritage.',
 'Historic AME church on Auburn Avenue.',
 (select id from categories where slug = 'faith'),
 'https://www.bigbethelame.org', '(404) 659-0248',
 '220 Auburn Ave NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7556, -84.3837, '{en}', true, true, 'Sun services 7:45am, 11am',
 true, true, false, true, true, false),

('Saint Joseph Catholic Church — Marietta',
 'Active Catholic parish in Marietta with English, Spanish, and Vietnamese masses.',
 'Catholic parish with multilingual masses.',
 (select id from categories where slug = 'faith'),
 'https://www.stjosephcc.org', '(770) 428-9971',
 '87 Atlanta St NE, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9534, -84.5466, '{en,es,vi}', true, true, 'Daily mass — see website',
 true, true, true, true, true, false),

('Misión Catolica Nuestra Señora de las Américas',
 'Spanish-language Catholic mission in Doraville serving Latino immigrants — Spanish masses and sacraments.',
 'Spanish-language Catholic mission.',
 (select id from categories where slug = 'faith'),
 'https://www.missionofourlady.org', '(770) 936-9024',
 '4814 Buford Hwy NE, Chamblee, GA 30341', 'Chamblee', 'GA', '30341',
 33.8895, -84.2941, '{es,en}', true, true, 'Daily mass — see website',
 true, true, true, true, true, true),

('Saint Thomas More Catholic Church',
 'Catholic parish in Decatur known for diverse congregation and active ministries.',
 'Catholic parish in Decatur.',
 (select id from categories where slug = 'faith'),
 'https://www.stmga.org', '(404) 378-4588',
 '636 W Ponce de Leon Ave, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7775, -84.3027, '{en,es}', true, true, 'Daily mass — see website',
 true, true, true, true, true, false),

('Mosque Al-Furqan',
 'Sunni mosque in Marietta serving the Cobb County Muslim community — five daily prayers and Friday Jumu''ah.',
 'Sunni mosque in Marietta.',
 (select id from categories where slug = 'faith'),
 'https://www.alfurqanmasjid.org', '(770) 425-5757',
 '1001 Powder Springs St SW, Marietta, GA 30064', 'Marietta', 'GA', '30064',
 33.9444, -84.5611, '{en,ar,ur}', true, true, 'Daily prayers — Jumu''ah Fri',
 true, true, true, false, true, false),

('Masjid Al-Hedaya — Norcross',
 'Sunni mosque in Norcross with weekend Islamic school and community programs.',
 'Sunni mosque in Norcross.',
 (select id from categories where slug = 'faith'),
 'https://alhedaya.org', '(770) 921-9356',
 '6225 Crescent Dr, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9542, -84.2065, '{en,ar,ur,bn}', true, true, 'Daily prayers — Jumu''ah Fri',
 true, true, true, false, true, false),

('Atlanta Muslim Community Center (Suwanee)',
 'Sunni mosque and community center serving Suwanee and North Gwinnett — weekend school and youth.',
 'Sunni mosque and community center in Suwanee.',
 (select id from categories where slug = 'faith'),
 'https://www.atlantamcc.org', '(770) 822-6464',
 '755 Dean Dr NW, Suwanee, GA 30024', 'Suwanee', 'GA', '30024',
 34.0594, -84.0817, '{en,ar,ur}', true, true, 'Daily prayers — Jumu''ah Fri',
 true, true, true, false, true, false),

('Hindu Temple of Atlanta — Riverdale',
 'Hindu temple complex in Riverdale dedicated to Lord Venkateswara — daily pujas and major festivals.',
 'Hindu temple in Riverdale.',
 (select id from categories where slug = 'faith'),
 'https://www.hindutempleofatlanta.org', '(770) 907-7102',
 '5851 Highway 85, Riverdale, GA 30274', 'Riverdale', 'GA', '30274',
 33.5614, -84.3756, '{en,hi,te,ta}', true, true, 'Daily 9am — 12pm, 5pm — 9pm',
 true, true, true, false, true, true),

('BAPS Hindu Mandir — Lilburn',
 'Large traditionally carved Hindu temple in Lilburn — daily darshan, cultural programs, classes.',
 'Large Hindu temple in Lilburn.',
 (select id from categories where slug = 'faith'),
 'https://www.baps.org/Atlanta', '(678) 906-2277',
 '460 Rockbridge Rd NW, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.8831, -84.1418, '{en,hi,gu,ta}', true, true, 'Daily 9am — 12pm, 4pm — 8:30pm',
 true, true, true, false, true, true),

('Sikh Religious Society of Georgia',
 'Sikh gurdwara in Norcross with daily services, langar, and Punjabi school.',
 'Sikh gurdwara in Norcross.',
 (select id from categories where slug = 'faith'),
 'https://www.gurdwaraatlanta.org', '(770) 248-1055',
 '6655 Mason Rd, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9737, -84.2049, '{en,pa,hi}', true, true, 'Daily — Sun major service 11am',
 true, true, true, false, true, false),

-- ============== COMMUNITY & CULTURE — TOP CULTURAL INSTITUTIONS ==============
('Fox Theatre',
 'Historic 1920s theatre and Atlanta landmark — Broadway tours, concerts, and films.',
 'Historic 1920s theatre and concert venue.',
 (select id from categories where slug = 'community'),
 'https://www.foxtheatre.org', '(855) 285-8499',
 '660 Peachtree St NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7724, -84.3856, '{en,es}', false, true, 'Box office Mon — Fri 10am — 5pm',
 true, true, true, true, true, true),

('Atlanta Symphony Orchestra',
 'Grammy-winning orchestra performing at the Woodruff Arts Center in Midtown — classical, pops, films.',
 'Grammy-winning Atlanta orchestra.',
 (select id from categories where slug = 'community'),
 'https://www.aso.org', '(404) 733-4900',
 '1280 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7891, -84.3853, '{en}', false, true, 'Concert calendar — see website',
 true, true, true, true, true, true),

('Alliance Theatre',
 'Tony Award-winning regional theatre at the Woodruff Arts Center — new works, classics, family series.',
 'Tony Award-winning regional theatre.',
 (select id from categories where slug = 'community'),
 'https://www.alliancetheatre.org', '(404) 733-5000',
 '1280 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7891, -84.3853, '{en}', false, true, 'See season schedule',
 true, true, true, true, true, true),

('Center for Puppetry Arts',
 'Largest puppetry organization in North America — performances, museum, and family workshops.',
 'Largest puppetry org in North America.',
 (select id from categories where slug = 'community'),
 'https://www.puppet.org', '(404) 873-3391',
 '1404 Spring St NW, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7919, -84.3893, '{en}', false, true, 'Tue — Sun 9am — 5pm',
 true, true, false, true, true, true),

('Michael C. Carlos Museum',
 'Emory University museum with Egyptian, Greek, Roman, and African art collections — free admission.',
 'Free Emory museum with global art.',
 (select id from categories where slug = 'community'),
 'https://carlos.emory.edu', '(404) 727-4282',
 '571 S Kilgo Cir NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7945, -84.3236, '{en}', true, true, 'Tue — Sun 10am — 5pm',
 true, true, false, false, true, true),

('Atlanta Contemporary',
 'Free contemporary art center in West Midtown — exhibitions, studios, and education programs.',
 'Free contemporary art center.',
 (select id from categories where slug = 'community'),
 'https://atlantacontemporary.org', '(404) 688-1970',
 '535 Means St NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7716, -84.4124, '{en}', true, true, 'Tue — Sat 11am — 7pm',
 true, true, true, false, true, false),

('Museum of Design Atlanta (MODA)',
 'Design museum in Midtown — exhibitions on architecture, fashion, and graphic design.',
 'Design museum in Midtown.',
 (select id from categories where slug = 'community'),
 'https://www.museumofdesign.org', '(404) 979-6455',
 '1315 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7868, -84.3849, '{en}', false, true, 'Tue — Sat 11am — 6pm',
 true, true, false, true, true, false),

('Atlanta Opera',
 'Major regional opera company performing at Cobb Energy Performing Arts Centre and other venues.',
 'Major regional opera company.',
 (select id from categories where slug = 'community'),
 'https://www.atlantaopera.org', '(404) 881-8885',
 '2800 Cobb Galleria Pkwy, Atlanta, GA 30339', 'Atlanta', 'GA', '30339',
 33.8843, -84.4660, '{en,it}', false, true, 'Season schedule — see website',
 true, true, true, true, true, false),

('Cobb Energy Performing Arts Centre',
 'Premier 2,750-seat performing arts venue in Cobb County — Broadway, ballet, opera, and concerts.',
 'Premier performing arts venue in Cobb.',
 (select id from categories where slug = 'community'),
 'https://www.cobbenergycentre.com', '(770) 916-2800',
 '2800 Cobb Galleria Pkwy, Atlanta, GA 30339', 'Atlanta', 'GA', '30339',
 33.8843, -84.4660, '{en}', false, true, 'Box office Mon — Fri 10am — 6pm',
 true, true, true, true, true, false),

('Margaret Mitchell House',
 'Atlanta History Center site — restored apartment where Mitchell wrote ''Gone with the Wind.''',
 'Restored home of Margaret Mitchell.',
 (select id from categories where slug = 'community'),
 'https://www.atlantahistorycenter.com', '(404) 814-4100',
 '979 Crescent Ave NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7822, -84.3829, '{en}', false, true, 'See AHC schedule',
 true, true, false, true, true, false),

('The Wren''s Nest',
 'Historic home of Joel Chandler Harris and storytelling museum in West End — guided tours and events.',
 'Historic home and storytelling museum.',
 (select id from categories where slug = 'community'),
 'https://www.wrensnest.org', '(404) 753-7735',
 '1050 Ralph David Abernathy Blvd SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7438, -84.4221, '{en}', false, true, 'Thu — Sat 10am — 2pm',
 true, true, false, true, true, false),

('Apex Museum',
 'African American Panoramic Experience — Black history museum on Auburn Avenue.',
 'African American history museum.',
 (select id from categories where slug = 'community'),
 'https://www.apexmuseum.org', '(404) 523-2739',
 '135 Auburn Ave NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7559, -84.3865, '{en}', false, true, 'Tue — Sat 10am — 5pm',
 true, true, false, true, true, false),

('Booth Western Art Museum',
 'Smithsonian-affiliated museum in Cartersville with Western American art and photography.',
 'Western American art museum in Cartersville.',
 (select id from categories where slug = 'community'),
 'https://boothmuseum.org', '(770) 387-1300',
 '501 Museum Dr, Cartersville, GA 30120', 'Cartersville', 'GA', '30120',
 34.1668, -84.7986, '{en}', false, true, 'Tue — Sat 10am — 5pm, Sun 1pm — 5pm',
 true, true, false, true, true, false),

('Tubman Museum',
 'African American art, history, and culture museum in Macon — exhibitions and programs.',
 'African American history museum in Macon.',
 (select id from categories where slug = 'community'),
 'https://www.tubmanmuseum.com', '(478) 743-8544',
 '310 Cherry St, Macon, GA 31201', 'Macon', 'GA', '31201',
 32.8407, -83.6325, '{en}', false, true, 'Tue — Fri 9am — 5pm, Sat 11am — 5pm',
 true, true, false, true, true, false),

('Center for Civil and Human Rights — Education Programs',
 'Downtown Atlanta museum with civil-rights and global human-rights exhibits — school and group tours.',
 'Civil and human rights museum downtown.',
 (select id from categories where slug = 'community'),
 'https://www.civilandhumanrights.org', '(678) 999-8990',
 '100 Ivan Allen Jr Blvd NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7634, -84.3934, '{en,es}', false, true, 'Wed — Sun 12pm — 5pm',
 true, true, false, true, true, true),

-- ============== COMMUNITY & CULTURE — DIASPORA & HERITAGE ORGS ==============
('Korean American Association of Greater Atlanta',
 'Umbrella org for Korean-Americans in Atlanta — civic engagement, cultural events, language classes.',
 'Korean-American umbrella org.',
 (select id from categories where slug = 'community'),
 'https://www.koreanatlanta.org', '(770) 451-7777',
 '5900 Brook Hollow Pkwy, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9461, -84.2189, '{en,ko}', true, true, 'Mon — Fri 9am — 6pm',
 true, false, false, true, true, true),

('Vietnamese American Community of Georgia',
 'Cultural and civic organization for Vietnamese-Americans — Tet festival, language school, community advocacy.',
 'Vietnamese-American community org.',
 (select id from categories where slug = 'community'),
 'https://www.vacga.org', '(770) 451-1818',
 '4153 Flat Shoals Pkwy, Decatur, GA 30034', 'Decatur', 'GA', '30034',
 33.7142, -84.2257, '{en,vi}', true, true, 'See website for events',
 true, true, false, false, true, false),

('Filipino American Association of Greater Atlanta',
 'Cultural and social organization for Filipino-Americans in Georgia — Independence Day, scholarships.',
 'Filipino-American cultural org.',
 (select id from categories where slug = 'community'),
 'https://faagainc.com', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,tl}', true, true, 'See website for events',
 false, true, false, false, true, false),

('Japan-America Society of Georgia',
 'Cultural exchange and business networking organization promoting U.S.-Japan relations.',
 'Japan-America cultural exchange org.',
 (select id from categories where slug = 'community'),
 'https://www.jasgeorgia.org', '(404) 842-1400',
 '600 Peachtree St NE Suite 4250, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7700, -84.3863, '{en,ja}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Chinese Community Center of Atlanta (CCCA)',
 'Cultural organization promoting Chinese language, arts, and community for the Atlanta Chinese community.',
 'Chinese cultural community org.',
 (select id from categories where slug = 'community'),
 'https://www.atlantaccca.org', '(770) 936-9090',
 '5377 New Peachtree Rd, Chamblee, GA 30341', 'Chamblee', 'GA', '30341',
 33.8851, -84.2960, '{en,zh}', true, true, 'See website',
 true, true, false, false, true, false),

('India American Cultural Association (IACA)',
 'Premier cultural organization for the Atlanta Indian community — festivals, dance, language classes.',
 'Indian-American cultural organization.',
 (select id from categories where slug = 'community'),
 'https://www.iaca.org', '(770) 962-0006',
 '1281 Cooper Lake Rd SE, Smyrna, GA 30082', 'Smyrna', 'GA', '30082',
 33.8443, -84.5183, '{en,hi,gu,ta,te,bn,pa}', true, true, 'See website',
 true, true, false, true, true, true),

('Jewish Federation of Greater Atlanta',
 'Central Jewish community organization — philanthropy, youth, refugee resettlement, and cultural programs.',
 'Central Jewish community organization.',
 (select id from categories where slug = 'community'),
 'https://www.jewishatlanta.org', '(404) 873-1661',
 '1440 Spring St NW, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7960, -84.3899, '{en,he,ru,es}', true, true, 'Mon — Thu 8:30am — 5pm, Fri 8:30am — 3pm',
 false, false, false, true, true, true),

('Marcus Jewish Community Center of Atlanta (MJCCA)',
 'Large Jewish community center in Dunwoody — fitness, summer camps, arts, early childhood programs.',
 'Large Jewish community center.',
 (select id from categories where slug = 'community'),
 'https://www.atlantajcc.org', '(678) 812-4000',
 '5342 Tilly Mill Rd, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9351, -84.3010, '{en,he,ru}', false, true, 'Mon — Thu 5:30am — 9pm, Fri 5:30am — 6pm',
 true, true, true, true, true, false),

('African American Heritage Cultural Society of Stone Mountain',
 'Local cultural society preserving African American heritage in DeKalb County — programs and events.',
 'African American heritage society.',
 (select id from categories where slug = 'community'),
 'https://www.africanamericanculturalsociety.org', null,
 'Stone Mountain, GA', 'Stone Mountain', 'GA', '30087',
 33.8081, -84.1701, '{en}', true, true, 'See website',
 false, true, false, false, true, false),

('Caribbean American Cultural Arts Foundation',
 'Cultural foundation celebrating Caribbean heritage in Atlanta — annual carnival and cultural events.',
 'Caribbean cultural foundation.',
 (select id from categories where slug = 'community'),
 'https://www.atlantacarnival.org', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,ht}', true, true, 'See website for events',
 false, true, true, false, true, false),

('Ethiopian Community Association in Georgia',
 'Cultural and mutual-aid org serving the Ethiopian community in metro Atlanta — language classes, holidays.',
 'Ethiopian community organization.',
 (select id from categories where slug = 'community'),
 'https://www.ecagainc.org', '(404) 478-9933',
 '4651 Memorial Dr, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7728, -84.2671, '{en,am}', true, true, 'See website',
 true, true, false, true, true, false),

('Somali Community Center of Atlanta',
 'Community center serving Somali refugees and immigrants — case management, English classes, youth.',
 'Somali community center.',
 (select id from categories where slug = 'community'),
 'https://www.somalicenter-atl.org', '(770) 458-0017',
 '4151 Memorial Dr, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,so,ar}', true, true, 'Mon — Fri 9am — 5pm',
 true, true, false, true, true, false),

('Eritrean Community Center of Atlanta',
 'Cultural and mutual-aid organization for the Eritrean community — events, language classes, support.',
 'Eritrean community organization.',
 (select id from categories where slug = 'community'),
 'https://www.eritreancc-atl.org', null,
 'Stone Mountain, GA', 'Stone Mountain', 'GA', '30083',
 33.8081, -84.1701, '{en,ti}', true, true, 'See website',
 false, true, false, false, true, false),

('Bhutanese Nepali Community of Atlanta',
 'Community organization serving Bhutanese-Nepali refugees in Clarkston and metro Atlanta.',
 'Bhutanese-Nepali community org.',
 (select id from categories where slug = 'community'),
 'https://bnca.org', null,
 'Clarkston, GA', 'Clarkston', 'GA', '30021',
 33.8112, -84.2393, '{en,ne}', true, true, 'See website',
 false, true, false, false, true, false),

('Burmese Community Center of Atlanta',
 'Community organization for Burmese refugees and immigrants in Clarkston — case management and youth.',
 'Burmese community center.',
 (select id from categories where slug = 'community'),
 'https://www.bcca-atl.org', null,
 'Clarkston, GA', 'Clarkston', 'GA', '30021',
 33.8112, -84.2393, '{en,my}', true, true, 'See website',
 false, true, false, false, true, false),

-- ============== FINANCIAL — TRUSTED BANKS, TAX HELP, EDUCATION ==============
('Wells Fargo Bank — Buford Highway',
 'Major national bank with multilingual services — checking, savings, ITIN-friendly mortgage options.',
 'Major national bank — multilingual.',
 (select id from categories where slug = 'financial'),
 'https://www.wellsfargo.com', '(404) 633-4081',
 '4920 Buford Hwy NE, Chamblee, GA 30341', 'Chamblee', 'GA', '30341',
 33.8945, -84.2944, '{en,es,zh,ko,vi}', false, true, 'Mon — Fri 9am — 5pm, Sat 9am — 1pm',
 true, true, false, true, true, false),

('Bank of America — Decatur',
 'Major national bank with bilingual services — checking, savings, credit cards, mortgages.',
 'Major national bank — bilingual.',
 (select id from categories where slug = 'financial'),
 'https://www.bankofamerica.com', '(404) 370-3580',
 '300 E Ponce de Leon Ave, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7745, -84.2950, '{en,es}', false, true, 'Mon — Fri 9am — 5pm, Sat 9am — 12pm',
 true, true, false, true, true, false),

('Chase Bank — Buckhead',
 'Major national bank with broad branch network — checking, savings, business banking, ITIN options.',
 'Major national bank — broad services.',
 (select id from categories where slug = 'financial'),
 'https://www.chase.com', '(404) 814-2901',
 '3232 Peachtree Rd NE, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8458, -84.3722, '{en,es,zh}', false, true, 'Mon — Fri 9am — 5pm, Sat 9am — 2pm',
 true, true, false, true, true, false),

('Truist Bank — Downtown Atlanta',
 'Major Southeastern bank (formerly SunTrust/BB&T) — checking, savings, mortgage, business banking.',
 'Major Southeastern bank — formerly SunTrust.',
 (select id from categories where slug = 'financial'),
 'https://www.truist.com', '(404) 588-7711',
 '303 Peachtree St NE, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7607, -84.3870, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Regions Bank — Midtown',
 'Southeastern regional bank with bilingual staff — checking, savings, ITIN-friendly products.',
 'Southeastern regional bank — bilingual.',
 (select id from categories where slug = 'financial'),
 'https://www.regions.com', '(404) 732-8980',
 '1100 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7855, -84.3851, '{en,es}', false, true, 'Mon — Fri 9am — 5pm, Sat 9am — 12pm',
 true, true, false, true, true, false),

('Delta Community Credit Union — Atlanta',
 'Largest credit union in Georgia — open to all metro Atlanta residents — low-fee accounts and loans.',
 'Largest credit union in Georgia.',
 (select id from categories where slug = 'financial'),
 'https://www.deltacommunitycu.com', '(800) 544-3328',
 '1025 Virginia Ave, Atlanta, GA 30354', 'Atlanta', 'GA', '30354',
 33.6649, -84.4124, '{en,es}', false, true, 'Mon — Fri 9am — 5pm, Sat 9am — 1pm',
 true, true, false, true, true, true),

('Self-Help Credit Union — Atlanta',
 'Mission-driven credit union — affordable banking, ITIN-friendly mortgages, small business loans.',
 'Mission-driven ITIN-friendly credit union.',
 (select id from categories where slug = 'financial'),
 'https://www.self-help.org', '(404) 577-3178',
 '270 Peachtree St NW Suite 1700, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7585, -84.3879, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 true, true, false, true, true, true),

('Atlanta Federal Credit Union',
 'Member-owned credit union open to many Atlanta employer groups — loans and accounts with low fees.',
 'Member-owned Atlanta credit union.',
 (select id from categories where slug = 'financial'),
 'https://www.atlfcu.org', '(404) 658-6465',
 '67 Centennial Olympic Park Dr SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7600, -84.3942, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('AARP Tax-Aide — United Way Atlanta',
 'Free tax preparation for low-to-moderate income people — IRS-certified volunteers, multiple sites.',
 'Free tax prep for low-income people.',
 (select id from categories where slug = 'financial'),
 'https://www.aarp.org/money/taxes/aarp_taxaide', '(888) 227-7669',
 '40 Courtland St NE, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7574, -84.3856, '{en,es}', true, true, 'Tax season Feb — Apr',
 true, true, false, true, true, true),

('Refund Advantage — IRS Volunteer Tax Help',
 'IRS partner offering free tax filing for households earning under $79,000 — multilingual.',
 'Free IRS tax filing for low-income.',
 (select id from categories where slug = 'financial'),
 'https://www.irs.gov/individuals/free-tax-return-preparation-for-qualifying-taxpayers', '(800) 829-1040',
 '401 W Peachtree St NW, Atlanta, GA 30308', 'Atlanta', 'GA', '30308',
 33.7711, -84.3877, '{en,es,zh,vi,ko}', true, true, 'Tax season Feb — Apr',
 true, true, false, true, true, false),

('Federal Reserve Bank of Atlanta — Money Museum',
 'Free financial education museum at the Atlanta Fed — exhibits, classes, and youth programs.',
 'Free financial education museum.',
 (select id from categories where slug = 'financial'),
 'https://www.atlantafed.org/about/tours-and-museum', '(404) 498-8500',
 '1000 Peachtree St NE, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.7820, -84.3855, '{en}', true, true, 'Mon — Fri 9am — 4pm',
 true, false, false, true, true, false),

('Money Management International — Atlanta',
 'Nonprofit credit counseling and debt management — free initial consultations.',
 'Nonprofit credit counseling agency.',
 (select id from categories where slug = 'financial'),
 'https://www.moneymanagement.org', '(866) 232-9080',
 '5825 Glenridge Dr Suite 101, Atlanta, GA 30328', 'Atlanta', 'GA', '30328',
 33.9229, -84.3733, '{en,es}', true, true, 'Mon — Fri 8am — 8pm',
 false, false, true, true, true, false),

('GreenPath Financial Wellness — Atlanta',
 'Nonprofit credit counseling, debt management, and student loan counseling — free or low cost.',
 'Nonprofit credit counseling agency.',
 (select id from categories where slug = 'financial'),
 'https://www.greenpath.com', '(800) 550-1961',
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Mon — Fri 8am — 11pm, Sat 9am — 7pm',
 false, true, true, true, true, false),

('On The Rise Financial Center',
 'Nonprofit financial coaching and counseling for working families on Atlanta''s Westside.',
 'Nonprofit financial coaching.',
 (select id from categories where slug = 'financial'),
 'https://ontherisefinancial.org', '(678) 940-1881',
 '1190 Joseph E Lowery Blvd NW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7659, -84.4189, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

-- ============== PARKS — POPULAR REGIONAL & NEIGHBORHOOD PARKS ==============
('Atlanta BeltLine — Westside Trail',
 'Popular paved 3-mile trail along the western side of the BeltLine loop — public art and parks.',
 'Popular paved trail on the Westside.',
 (select id from categories where slug = 'parks'),
 'https://beltline.org/visit/the-atlanta-beltline-trails/westside-trail', null,
 'Lena St SW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7517, -84.4225, '{en}', true, true, 'Daily 6am — 11pm',
 true, true, true, false, true, true),

('Atlanta BeltLine — Northside Trail',
 'Wooded section of the BeltLine connecting Tanyard Creek Park to Bobby Jones Golf Course.',
 'Wooded BeltLine trail on the Northside.',
 (select id from categories where slug = 'parks'),
 'https://beltline.org', null,
 'Tanyard Creek Park, Atlanta, GA 30309', 'Atlanta', 'GA', '30309',
 33.8093, -84.4053, '{en}', true, true, 'Daily 6am — 11pm',
 true, true, true, false, true, false),

('Atlanta BeltLine — Southside Trail',
 'Section of the BeltLine connecting West End to Boulevard Crossing Park — running and biking.',
 'BeltLine trail on the Southside.',
 (select id from categories where slug = 'parks'),
 'https://beltline.org', null,
 'University Ave SW, Atlanta, GA 30310', 'Atlanta', 'GA', '30310',
 33.7281, -84.3990, '{en}', true, true, 'Daily 6am — 11pm',
 true, true, true, false, true, false),

('Olmsted Linear Park (Druid Hills)',
 'Historic linear park designed by Frederick Law Olmsted — series of green spaces along Ponce.',
 'Historic linear park along Ponce.',
 (select id from categories where slug = 'parks'),
 'https://atlantaolmstedpark.org', null,
 'Ponce de Leon Ave NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7726, -84.3300, '{en}', true, true, 'Dawn — dusk',
 true, true, false, false, true, false),

('Bobby Jones Golf Course & Park',
 'Public 9-hole reversible golf course and park in Buckhead — driving range, walking trails.',
 'Public golf course and park in Buckhead.',
 (select id from categories where slug = 'parks'),
 'https://www.bobbyjonesgc.com', '(404) 355-1009',
 '384 Woodward Way NW, Atlanta, GA 30305', 'Atlanta', 'GA', '30305',
 33.8128, -84.4051, '{en}', false, true, 'Dawn — dusk',
 true, true, true, true, true, false),

('Mason Mill Park',
 'Wooded DeKalb park with playground, tennis, walking trails, and South Peachtree Creek access.',
 'DeKalb park with trails and playground.',
 (select id from categories where slug = 'parks'),
 'https://www.dekalbcountyga.gov', '(404) 371-2631',
 '1340 McConnell Dr, Decatur, GA 30033', 'Decatur', 'GA', '30033',
 33.8095, -84.3034, '{en}', true, true, 'Dawn — dusk',
 true, true, true, true, true, false),

('East Lake Park',
 'Atlanta neighborhood park with playground, walking paths, and community gardens.',
 'Neighborhood park in East Lake.',
 (select id from categories where slug = 'parks'),
 'https://www.atlantaga.gov/government/departments/parks-recreation', '(404) 546-6788',
 '375 East Lake Dr SE, Atlanta, GA 30317', 'Atlanta', 'GA', '30317',
 33.7378, -84.3093, '{en}', true, true, 'Dawn — dusk',
 true, true, true, true, true, false),

('Brook Run Trail (Dunwoody)',
 'Paved 1.4-mile loop trail through wooded Brook Run Park — popular for runners and families.',
 'Popular paved trail in Brook Run Park.',
 (select id from categories where slug = 'parks'),
 'https://www.dunwoodyga.gov/government/departments/parks-recreation', '(678) 382-6700',
 '4770 N Peachtree Rd, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9444, -84.3155, '{en}', true, true, 'Daily 7am — 9pm',
 true, true, true, true, true, false),

('Lullwater Park (Emory)',
 'Wooded 154-acre park on the Emory campus with creek, trails, and historic Lullwater House.',
 'Wooded Emory park with trails.',
 (select id from categories where slug = 'parks'),
 'https://emoryreports.emory.edu/lullwater-preserve.html', null,
 '1463 Clifton Rd NE, Atlanta, GA 30322', 'Atlanta', 'GA', '30322',
 33.7965, -84.3203, '{en}', true, true, 'Dawn — dusk',
 true, true, false, false, true, false),

('Lake Lanier (Buford Dam)',
 'Massive recreational reservoir north of Atlanta — fishing, boating, beaches, and parks.',
 'Massive recreational reservoir.',
 (select id from categories where slug = 'parks'),
 'https://www.sam.usace.army.mil/Missions/Recreation/Lake-Sidney-Lanier', '(770) 945-9531',
 '1050 Buford Dam Rd, Buford, GA 30518', 'Buford', 'GA', '30518',
 34.1670, -84.0775, '{en,es}', true, true, 'Dawn — dusk',
 true, true, true, true, true, true),

-- ============== EMERGENCY — POPULAR HOTLINES & SERVICES ==============
('Crisis Line of Cobb County',
 'Free 24/7 crisis hotline for Cobb County residents — mental health, suicide, and domestic violence.',
 'Free 24/7 crisis hotline for Cobb County.',
 (select id from categories where slug = 'emergency'),
 'https://www.cobbcsb.com/crisis', '(770) 422-0202',
 'Marietta, GA', 'Marietta', 'GA', '30060',
 33.9526, -84.5499, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('National Sexual Assault Hotline (RAINN)',
 'Free confidential 24/7 hotline for survivors of sexual assault — referrals to local services.',
 'Free 24/7 sexual assault hotline.',
 (select id from categories where slug = 'emergency'),
 'https://www.rainn.org', '1-800-656-4673',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('Childhelp National Child Abuse Hotline',
 'Free confidential 24/7 hotline for child abuse — counselors in 170+ languages.',
 'Free 24/7 child abuse hotline.',
 (select id from categories where slug = 'emergency'),
 'https://www.childhelp.org', '1-800-422-4453',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('Trans Lifeline',
 'Peer-support hotline by and for trans people — confidential, no police contact without consent.',
 'Trans peer support hotline.',
 (select id from categories where slug = 'emergency'),
 'https://translifeline.org', '1-877-565-8860',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Daily 1pm — 9am',
 false, true, true, true, true, false),

('Trevor Project (LGBTQ Youth)',
 'Free confidential 24/7 crisis support for LGBTQ youth under 25 — phone, text, and chat.',
 'Free 24/7 LGBTQ youth crisis support.',
 (select id from categories where slug = 'emergency'),
 'https://www.thetrevorproject.org', '1-866-488-7386',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('Veterans Crisis Line',
 'Free confidential 24/7 crisis hotline for veterans and their families — call, text 838255, or chat.',
 'Free 24/7 veterans crisis hotline.',
 (select id from categories where slug = 'emergency'),
 'https://www.veteranscrisisline.net', '988 then press 1',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, '24/7',
 false, true, true, true, true, false),

('Disaster Distress Helpline (SAMHSA)',
 'Free confidential 24/7 hotline for emotional distress after disasters — multilingual support.',
 'Free 24/7 disaster distress hotline.',
 (select id from categories where slug = 'emergency'),
 'https://www.samhsa.gov/find-help/disaster-distress-helpline', '1-800-985-5990',
 'National Hotline', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es,zh,vi,ko,ar}', true, true, '24/7',
 false, true, true, true, true, false),

('Poison Control Center — Georgia',
 'Free 24/7 hotline for poison emergencies — chemical, medication, plant, and bite exposures.',
 'Free 24/7 poison control hotline.',
 (select id from categories where slug = 'emergency'),
 'https://www.poison.org', '1-800-222-1222',
 '50 Hurt Plaza Suite 600, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7563, -84.3895, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('Atlanta Mission — Day Resource Center',
 'Day shelter and resource center for adults experiencing homelessness — meals, showers, case management.',
 'Day shelter and resource center.',
 (select id from categories where slug = 'emergency'),
 'https://atlantamission.org', '(404) 367-2429',
 '156 Walker St SW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7530, -84.3974, '{en,es}', true, true, 'Daily 6am — 6pm',
 true, true, false, true, true, true),

('Covenant House Georgia',
 'Emergency shelter, transitional housing, and youth services for young adults 18 — 24 facing homelessness.',
 'Emergency shelter for young adults 18-24.',
 (select id from categories where slug = 'emergency'),
 'https://www.covenanthousega.org', '(404) 589-0163',
 '1559 Johnson Rd NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7796, -84.4198, '{en,es}', true, true, '24/7',
 true, true, true, true, true, true),

-- ============== EMPLOYMENT — POPULAR JOB & TRAINING SERVICES ==============
('Goodwill of North Georgia — Norcross Career Center',
 'Free job training, resume help, computer access, and career coaching — known for fast placement.',
 'Free Goodwill career center.',
 (select id from categories where slug = 'employment'),
 'https://goodwillng.org', '(770) 416-9099',
 '1995 Beaver Ruin Rd, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9395, -84.1985, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

('Goodwill of North Georgia — DeKalb Career Center',
 'Free job training, resume help, computer access, and one-on-one career coaching.',
 'Free Goodwill career center in DeKalb.',
 (select id from categories where slug = 'employment'),
 'https://goodwillng.org', '(404) 486-8400',
 '4151 Memorial Dr, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,es,fr,am}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Year Up Atlanta',
 'Free year-long career training program for young adults 18 — 26 — IT, finance, business with paid internships.',
 'Year-long free career training for young adults.',
 (select id from categories where slug = 'employment'),
 'https://www.yearup.org/locations/atlanta', '(404) 254-3950',
 '5775 Peachtree Dunwoody Rd Suite C-200, Atlanta, GA 30342', 'Atlanta', 'GA', '30342',
 33.9226, -84.3534, '{en,es}', true, false, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('Per Scholas — Atlanta',
 'Free 15-week IT training (cybersecurity, cloud, IT support) with job placement support.',
 'Free 15-week IT training with placement.',
 (select id from categories where slug = 'employment'),
 'https://perscholas.org/locations/atlanta', '(404) 800-3993',
 '675 Pulliam St SW, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7384, -84.3917, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('CareerSource Atlanta Region',
 'Workforce development board with free job search, training vouchers, and employer connections.',
 'Free job search and training services.',
 (select id from categories where slug = 'employment'),
 'https://atlantaregional.org', '(404) 463-3100',
 '229 Peachtree St NE Suite 100, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7593, -84.3865, '{en,es}', true, true, 'Mon — Fri 8:30am — 5:30pm',
 true, false, false, true, true, false),

('Refugee Career Hub — Atlanta',
 'Workforce program connecting refugees and immigrants to skilled-trades jobs and credential recognition.',
 'Workforce program for refugees.',
 (select id from categories where slug = 'employment'),
 'https://refugeecareerhub.org', '(404) 939-9888',
 '4151 Memorial Dr Suite 103E, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,es,ar,fa,sw,ne}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('GoodCity Mentors — Atlanta',
 'Career mentorship program connecting professionals with people seeking new careers.',
 'Free career mentorship program.',
 (select id from categories where slug = 'employment'),
 'https://goodcitymentors.org', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Online — see website',
 false, false, true, false, true, false),

('Skillpath Atlanta — IRC Career Pathways',
 'IRC career-pathways program for refugees in Atlanta — credential recognition and skilled jobs.',
 'IRC career pathways for refugees.',
 (select id from categories where slug = 'employment'),
 'https://www.rescue.org/united-states/atlanta-ga', '(678) 636-5900',
 '4151 Memorial Dr Suite 201, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,ar,fa,sw,am,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Goodwill Helms College — Macon',
 'Tuition-free trades training (medical assistant, culinary, IT) operated by Goodwill — Macon campus.',
 'Tuition-free trades training college.',
 (select id from categories where slug = 'employment'),
 'https://www.helms.edu', '(478) 314-7177',
 '3186 Riverside Dr, Macon, GA 31210', 'Macon', 'GA', '31210',
 32.8669, -83.6671, '{en,es}', true, false, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('LinkedIn Local Atlanta — Career Networking',
 'Professional networking community in Atlanta with monthly free events for job seekers.',
 'Free career networking community.',
 (select id from categories where slug = 'employment'),
 'https://www.linkedin.com', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Monthly events',
 false, false, true, false, true, false),

-- ============== LIBRARIES — POPULAR BRANCHES ==============
('Sandy Springs Branch — Atlanta-Fulton Public Library',
 'Modern library branch in Sandy Springs with computers, programs, and language collections.',
 'Modern Fulton library branch.',
 (select id from categories where slug = 'libraries'),
 'https://www.fulcolibrary.org', '(404) 303-6130',
 '395 Mt Vernon Hwy NE, Sandy Springs, GA 30328', 'Sandy Springs', 'GA', '30328',
 33.9282, -84.3796, '{en,es,zh,ko}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Alpharetta Branch — Atlanta-Fulton Public Library',
 'Active Fulton library branch in Alpharetta with maker space, kids programs, and ESL resources.',
 'Active Fulton library in Alpharetta.',
 (select id from categories where slug = 'libraries'),
 'https://www.fulcolibrary.org', '(404) 612-4646',
 '10 Park Plaza, Alpharetta, GA 30009', 'Alpharetta', 'GA', '30009',
 34.0759, -84.2926, '{en,es,zh,ko,hi}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Roswell Branch — Atlanta-Fulton Public Library',
 'Roswell library branch with kids programs, computers, and language collections.',
 'Roswell library branch.',
 (select id from categories where slug = 'libraries'),
 'https://www.fulcolibrary.org', '(404) 612-9700',
 '115 Norcross St, Roswell, GA 30075', 'Roswell', 'GA', '30075',
 34.0231, -84.3617, '{en,es,zh,ko}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Smyrna Public Library',
 'Cobb County library branch in downtown Smyrna — free Wi-Fi, computers, and kids programs.',
 'Cobb library branch in downtown Smyrna.',
 (select id from categories where slug = 'libraries'),
 'https://cobbcat.org', '(770) 431-2860',
 '100 Village Green Cir SE, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8821, -84.5142, '{en,es}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Marietta Library — Switzer Branch',
 'Cobb County library''s busy Marietta branch — children''s programs, free Wi-Fi, ESL classes.',
 'Cobb library in Marietta.',
 (select id from categories where slug = 'libraries'),
 'https://cobbcat.org', '(770) 528-2320',
 '266 Roswell St NE, Marietta, GA 30060', 'Marietta', 'GA', '30060',
 33.9554, -84.5435, '{en,es}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Norcross Branch — Gwinnett County Public Library',
 'Busy Gwinnett library branch with multilingual collections and ESL resources.',
 'Busy Gwinnett library in Norcross.',
 (select id from categories where slug = 'libraries'),
 'https://www.gwinnettpl.org', '(770) 448-4830',
 '6025 Buford Hwy, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9357, -84.2117, '{en,es,zh,ko,vi}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, true),

('Suwanee Branch — Gwinnett County Public Library',
 'Modern Gwinnett library branch in Suwanee with tech help, language classes, and kids programs.',
 'Modern Gwinnett library in Suwanee.',
 (select id from categories where slug = 'libraries'),
 'https://www.gwinnettpl.org', '(770) 978-5154',
 '361 Main St, Suwanee, GA 30024', 'Suwanee', 'GA', '30024',
 34.0512, -84.0719, '{en,es,zh,ko}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Duluth Branch — Gwinnett County Public Library',
 'Gwinnett library branch in Duluth with Korean and Spanish collections.',
 'Gwinnett library in Duluth.',
 (select id from categories where slug = 'libraries'),
 'https://www.gwinnettpl.org', '(770) 978-5154',
 '3180 Main St, Duluth, GA 30096', 'Duluth', 'GA', '30096',
 34.0023, -84.1442, '{en,es,zh,ko}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Lilburn Branch — Gwinnett County Public Library',
 'Newest Gwinnett library branch — modern facility with tech help and kids programs.',
 'Newest Gwinnett library branch.',
 (select id from categories where slug = 'libraries'),
 'https://www.gwinnettpl.org', '(770) 978-5154',
 '4817 Church St, Lilburn, GA 30047', 'Lilburn', 'GA', '30047',
 33.8881, -84.1413, '{en,es,zh,ko}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

('Brookhaven Branch — DeKalb County Public Library',
 'DeKalb library branch in Brookhaven — kids programs, ESL resources, and computer access.',
 'DeKalb library in Brookhaven.',
 (select id from categories where slug = 'libraries'),
 'https://www.dekalblibrary.org', '(404) 848-7140',
 '1242 N Druid Hills Rd NE, Brookhaven, GA 30319', 'Brookhaven', 'GA', '30319',
 33.8650, -84.3275, '{en,es,zh}', true, true, 'Mon — Sat — see website',
 true, true, true, true, true, false),

-- ============== TRANSPORTATION — POPULAR SERVICES ==============
('MARTA — Five Points Station',
 'Central transfer station in downtown Atlanta where all four MARTA rail lines connect.',
 'Central downtown MARTA transfer station.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '30 Alabama St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7540, -84.3915, '{en,es}', false, true, 'Daily 5am — 1am',
 true, true, true, true, true, true),

('MARTA — Lindbergh Center Station',
 'MARTA hub in Buckhead with rail and bus connections — TOD development above.',
 'MARTA hub station in Buckhead.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '2424 Piedmont Rd NE, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8233, -84.3691, '{en,es}', false, true, 'Daily 5am — 1am',
 true, true, true, true, true, false),

('MARTA — Doraville Station',
 'Northeast end of the gold MARTA line — major bus connections to Buford Highway.',
 'Northeast end of MARTA gold line.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '6006 New Peachtree Rd, Doraville, GA 30340', 'Doraville', 'GA', '30340',
 33.9020, -84.2818, '{en,es,zh,ko,vi}', false, true, 'Daily 5am — 1am',
 true, true, true, true, true, true),

('MARTA — Indian Creek Station',
 'East end of the MARTA blue line — bus transfers to DeKalb communities including Clarkston.',
 'East end of MARTA blue line.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '901 Durham Park Dr, Stone Mountain, GA 30083', 'Stone Mountain', 'GA', '30083',
 33.7655, -84.2238, '{en,es,fr,am,so,ne}', false, true, 'Daily 5am — 1am',
 true, true, true, true, true, true),

('MARTA — College Park Station',
 'MARTA stop near Hartsfield-Jackson Airport — convenient for airport workers and travelers.',
 'MARTA stop near the airport.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com', '(404) 848-5000',
 '3800 Main St, College Park, GA 30337', 'College Park', 'GA', '30337',
 33.6515, -84.4474, '{en,es}', false, true, 'Daily 5am — 1am',
 true, true, true, true, true, false),

('Lyft — Atlanta',
 'Rideshare service available throughout metro Atlanta — app-based rides with discount passes.',
 'Rideshare service throughout metro Atlanta.',
 (select id from categories where slug = 'transportation'),
 'https://www.lyft.com', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', false, true, '24/7',
 false, true, true, false, true, false),

('Uber — Atlanta',
 'Rideshare service available throughout metro Atlanta — app-based rides and Uber Eats delivery.',
 'Rideshare service throughout metro Atlanta.',
 (select id from categories where slug = 'transportation'),
 'https://www.uber.com', null,
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', false, true, '24/7',
 false, true, true, false, true, false),

('Atlanta Streetcar — Sweet Auburn',
 'Free downtown streetcar loop connecting Centennial Park to the MLK National Historical Park.',
 'Free downtown streetcar loop.',
 (select id from categories where slug = 'transportation'),
 'https://www.itsmarta.com/streetcar', '(404) 848-5000',
 '90 Centennial Olympic Park Dr NW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7616, -84.3938, '{en,es}', true, true, 'Mon — Thu 5am — 11pm, Fri — Sat 5am — 1am, Sun 9am — 11pm',
 true, true, true, false, true, false),

('Department of Driver Services — Norcross',
 'Georgia DDS office for road tests, license renewals, and ID cards — popular Norcross location.',
 'Georgia DDS license office.',
 (select id from categories where slug = 'transportation'),
 'https://dds.georgia.gov', '(678) 413-8400',
 '6420 Crescent Dr Suite C, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9497, -84.2089, '{en,es}', false, true, 'Tue — Fri 7:30am — 6pm, Sat 7:30am — 12pm',
 true, true, true, false, true, false),

('Department of Driver Services — Conyers',
 'Georgia DDS office for road tests, license renewals, and ID cards.',
 'Georgia DDS license office in Conyers.',
 (select id from categories where slug = 'transportation'),
 'https://dds.georgia.gov', '(678) 413-8400',
 '1135 Iris Dr SW Suite F, Conyers, GA 30094', 'Conyers', 'GA', '30094',
 33.6614, -84.0166, '{en,es}', false, true, 'Tue — Fri 7:30am — 6pm, Sat 7:30am — 12pm',
 true, true, true, false, true, false),

-- ============== FAMILY — POPULAR YOUTH & FAMILY ORGS ==============
('YMCA — Carl E. Sanders Family YMCA',
 'Top YMCA in Buckhead with pool, fitness center, kids programs, and youth sports.',
 'Top YMCA in Buckhead.',
 (select id from categories where slug = 'family'),
 'https://www.ymcaatlanta.org', '(404) 261-3111',
 '1160 Moores Mill Rd NW, Atlanta, GA 30327', 'Atlanta', 'GA', '30327',
 33.8294, -84.4361, '{en,es}', false, true, 'Mon — Fri 5am — 9pm, Sat — Sun 7am — 6pm',
 true, true, true, true, true, true),

('YMCA — Decatur Family YMCA',
 'Decatur YMCA with pool, gym, after-school programs, and summer camp.',
 'Decatur YMCA family branch.',
 (select id from categories where slug = 'family'),
 'https://www.ymcaatlanta.org', '(404) 377-9622',
 '1565 S Ponce de Leon Ave NE, Atlanta, GA 30307', 'Atlanta', 'GA', '30307',
 33.7636, -84.3247, '{en,es}', false, true, 'Mon — Fri 5am — 9pm, Sat — Sun 7am — 6pm',
 true, true, true, true, true, false),

('YMCA — Northeast Cobb',
 'Cobb YMCA with pool, fitness center, after-school care, and summer camp.',
 'Cobb YMCA in Marietta.',
 (select id from categories where slug = 'family'),
 'https://www.ymcaatlanta.org', '(770) 977-5991',
 '3010 Johnson Ferry Rd, Marietta, GA 30062', 'Marietta', 'GA', '30062',
 34.0148, -84.4253, '{en,es}', false, true, 'Mon — Fri 5am — 9pm, Sat — Sun 7am — 6pm',
 true, true, true, true, true, false),

('Boys & Girls Clubs — Bowen Homes Branch',
 'Free after-school and summer programs for kids age 6 — 18 in Northwest Atlanta.',
 'Free after-school programs for kids.',
 (select id from categories where slug = 'family'),
 'https://www.bgcma.org', '(404) 752-1101',
 '1140 Bankhead Hwy NW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7710, -84.4477, '{en,es}', true, true, 'Mon — Fri 2:30pm — 7:30pm',
 true, false, true, true, true, true),

('Boys & Girls Clubs — Tara Branch',
 'After-school and summer programs for kids in Forest Park and Clayton County.',
 'After-school programs in Clayton County.',
 (select id from categories where slug = 'family'),
 'https://www.bgcma.org', '(404) 762-2767',
 '4181 W Fayetteville Rd, Forest Park, GA 30297', 'Forest Park', 'GA', '30297',
 33.6248, -84.3987, '{en,es}', true, true, 'Mon — Fri 2:30pm — 7:30pm',
 true, false, true, true, true, false),

('Girl Scouts of Greater Atlanta',
 'Major Girl Scouts council serving Atlanta and 34 counties — troops, camps, and STEM programs.',
 'Major Girl Scouts council.',
 (select id from categories where slug = 'family'),
 'https://www.gsgatl.org', '(770) 702-9000',
 '5601 N Allen Rd SE, Mableton, GA 30126', 'Mableton', 'GA', '30126',
 33.8050, -84.5821, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, true, false, true, true, true),

('Boy Scouts — Atlanta Area Council',
 'Major Boy Scouts council serving 12 counties in north Georgia — troops, camps, and merit badges.',
 'Major Boy Scouts council.',
 (select id from categories where slug = 'family'),
 'https://www.atlantabsa.org', '(770) 989-8820',
 '1800 Circle 75 Pkwy SE, Atlanta, GA 30339', 'Atlanta', 'GA', '30339',
 33.8780, -84.4724, '{en,es}', false, true, 'Mon — Fri 8:30am — 5pm',
 true, false, false, true, true, true),

('CHRIS 180 (Children''s Counseling)',
 'Trauma-informed counseling, group homes, and crisis services for children, youth, and families.',
 'Trauma-informed counseling for kids.',
 (select id from categories where slug = 'family'),
 'https://chris180.org', '(404) 486-9034',
 '1017 Fayetteville Rd SE, Atlanta, GA 30316', 'Atlanta', 'GA', '30316',
 33.7202, -84.3493, '{en,es}', true, true, 'Mon — Fri 8am — 6pm',
 true, false, true, true, true, true),

('Sheltering Arms — Bank of America Center',
 'Quality early-childhood education, Head Start, and family services — Bank of America campus.',
 'Quality early-childhood education.',
 (select id from categories where slug = 'family'),
 'https://shelteringarmsforkids.com', '(404) 588-3160',
 '385 Centennial Olympic Park Dr NW, Atlanta, GA 30313', 'Atlanta', 'GA', '30313',
 33.7611, -84.3988, '{en,es}', true, true, 'Mon — Fri 6:30am — 6pm',
 true, false, false, true, true, false),

('Head Start — Easter Seals North Georgia',
 'Federally funded preschool for low-income families ages 0 — 5 — multiple Atlanta locations.',
 'Federally funded preschool for low-income.',
 (select id from categories where slug = 'family'),
 'https://www.eastersealsnorthgeorgia.org', '(770) 943-1070',
 '5600 Roswell Rd NE Suite 105, Sandy Springs, GA 30342', 'Sandy Springs', 'GA', '30342',
 33.9035, -84.3801, '{en,es}', true, true, 'Mon — Fri 7:30am — 5:30pm',
 true, false, false, true, true, true),

-- ============== WOMEN'S — POPULAR WOMEN'S SERVICES ==============
('Atlanta Pregnancy Care Center',
 'Free pregnancy testing, ultrasounds, prenatal classes, and material assistance.',
 'Free pregnancy testing and prenatal care.',
 (select id from categories where slug = 'womens'),
 'https://atlantapregnancy.com', '(404) 873-1973',
 '821 Highland Ave NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7820, -84.3678, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Gwinnett Sexual Assault Center',
 'Free counseling, advocacy, forensic exams, and 24/7 hotline for sexual assault survivors in Gwinnett.',
 'Free sexual assault services in Gwinnett.',
 (select id from categories where slug = 'womens'),
 'https://www.gsacenter.org', '(770) 476-7407',
 '532 W Pike St, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9555, -83.9911, '{en,es,ko,vi}', true, true, '24/7',
 true, true, true, true, true, true),

('DeKalb Rape Crisis Center',
 'Free 24/7 hotline, counseling, and advocacy for sexual-assault survivors in DeKalb County.',
 'Free DeKalb sexual assault services.',
 (select id from categories where slug = 'womens'),
 'https://dekalbrapecrisiscenter.com', '(404) 377-1428',
 '1755 The Exchange Pkwy SE Suite 175, Atlanta, GA 30339', 'Atlanta', 'GA', '30339',
 33.8866, -84.4646, '{en,es}', true, true, '24/7',
 false, true, true, true, true, true),

('LiveSAFE Resources (Cobb)',
 'Cobb County''s leading domestic violence shelter, counseling, and 24/7 hotline.',
 'Cobb domestic violence shelter and hotline.',
 (select id from categories where slug = 'womens'),
 'https://www.livesaferesources.org', '(770) 427-3390',
 'PO Box 5137, Marietta, GA 30061', 'Marietta', 'GA', '30061',
 33.9526, -84.5499, '{en,es}', true, true, '24/7',
 true, true, true, true, true, true),

('Liberty House (Columbus)',
 'Domestic violence shelter, counseling, and advocacy services for women and children in Columbus, GA.',
 'Columbus DV shelter and counseling.',
 (select id from categories where slug = 'womens'),
 'https://www.libertyhousecolumbus.org', '(706) 327-3999',
 '1241 13th St, Columbus, GA 31901', 'Columbus', 'GA', '31901',
 32.4738, -84.9885, '{en,es}', true, true, '24/7',
 true, true, true, true, true, false),

('Caminar Latino',
 'Latino-led nonprofit ending violence in Latino families — counseling, support groups, advocacy.',
 'Latino-led DV counseling and advocacy.',
 (select id from categories where slug = 'womens'),
 'https://caminarlatino.org', '(404) 413-1454',
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, true, true, true, true),

('YWCA of Greater Atlanta',
 'Women''s leadership, racial justice, and economic empowerment programs across metro Atlanta.',
 'Women''s leadership and economic programs.',
 (select id from categories where slug = 'womens'),
 'https://www.ywcaatlanta.org', '(404) 527-7575',
 '957 N Highland Ave NE, Atlanta, GA 30306', 'Atlanta', 'GA', '30306',
 33.7872, -84.3539, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

-- ============== LEGAL — POPULAR LEGAL & ADVOCACY ORGS ==============
('Catholic Charities Atlanta — Immigration Legal Services',
 'BIA-recognized low-cost immigration legal services — citizenship, family petitions, asylum.',
 'BIA-recognized immigration legal services.',
 (select id from categories where slug = 'legal'),
 'https://catholiccharitiesatlanta.org', '(678) 222-3920',
 '2401 Lake Park Dr SE, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8526, -84.5119, '{en,es,vi,fr}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, true),

('Asian Americans Advancing Justice — Atlanta (Legal)',
 'Civil-rights legal services, voter education, and advocacy for AAPI communities in the South.',
 'AAPI civil-rights legal services.',
 (select id from categories where slug = 'legal'),
 'https://advancingjustice-atlanta.org', '(404) 585-8446',
 '5680 Oakbrook Pkwy Suite 148, Norcross, GA 30093', 'Norcross', 'GA', '30093',
 33.9395, -84.1985, '{en,zh,ko,vi,hi}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, true),

('CAIR Georgia',
 'Civil-rights legal aid and advocacy for Georgia''s Muslim community — discrimination, hate crimes.',
 'Civil-rights legal aid for Muslim community.',
 (select id from categories where slug = 'legal'),
 'https://www.cairgeorgia.org', '(404) 419-6390',
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,ar,ur,bn,so}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('GALEO — Georgia Latino Civil Rights',
 'Latino civic engagement, voter registration, and policy advocacy organization.',
 'Latino civic engagement and advocacy.',
 (select id from categories where slug = 'legal'),
 'https://galeo.org', '(770) 642-7223',
 '6065 Roswell Rd Suite 535, Sandy Springs, GA 30328', 'Sandy Springs', 'GA', '30328',
 33.9215, -84.3722, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Project South — Legal & Movement Building',
 'Southern movement-building organization with legal support for Black and immigrant communities.',
 'Southern movement-building legal support.',
 (select id from categories where slug = 'legal'),
 'https://projectsouth.org', '(404) 622-0602',
 '9 Gammon Ave SE, Atlanta, GA 30315', 'Atlanta', 'GA', '30315',
 33.7148, -84.3801, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Lawyers'' Committee for Civil Rights Under Law — Georgia',
 'National civil-rights legal organization with regional advocacy in Georgia.',
 'National civil-rights legal organization.',
 (select id from categories where slug = 'legal'),
 'https://www.lawyerscommittee.org', '(202) 662-8600',
 'Atlanta, GA', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('State Bar of Georgia — Lawyer Referral',
 'Lawyer referral service that matches Georgia residents with attorneys for any legal need.',
 'Lawyer referral service for Georgia.',
 (select id from categories where slug = 'legal'),
 'https://www.gabar.org', '(404) 521-0777',
 '104 Marietta St NW Suite 100, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7490, -84.3880, '{en,es}', false, true, 'Mon — Fri 8:30am — 4:30pm',
 true, false, false, true, true, false),

('USCIS — Atlanta Field Office',
 'U.S. Citizenship and Immigration Services field office for naturalization, green card interviews.',
 'USCIS field office for citizenship and green card.',
 (select id from categories where slug = 'legal'),
 'https://www.uscis.gov', '(800) 375-5283',
 '2150 Parklake Dr NE, Atlanta, GA 30345', 'Atlanta', 'GA', '30345',
 33.8568, -84.2851, '{en,es,zh,vi,ko,ar}', false, true, 'Mon — Fri by appointment',
 false, false, false, true, true, true),

-- ============== HEALTHCARE — TOP COMMUNITY HEALTH SERVICES ==============
('CDC Public Health Information Line',
 'Centers for Disease Control hotline for general health questions and travel-health guidance.',
 'CDC general health information line.',
 (select id from categories where slug = 'healthcare'),
 'https://www.cdc.gov', '1-800-232-4636',
 '1600 Clifton Rd NE, Atlanta, GA 30329', 'Atlanta', 'GA', '30329',
 33.7986, -84.3199, '{en,es}', true, true, 'Mon — Fri 8am — 8pm',
 false, false, false, true, true, false),

('Open Door Family Health Center — Decatur',
 'Federally qualified health center serving uninsured and Medicaid patients — pediatrics, dental, behavioral.',
 'Free clinic with dental and behavioral care.',
 (select id from categories where slug = 'healthcare'),
 'https://opendoorhealthga.org', '(404) 270-9100',
 '4151 Memorial Dr Suite 105, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,es,fr,am,sw}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Curtis V. Cooper Primary Health Care — Savannah',
 'Federally qualified health center in Savannah — primary care, dental, behavioral, Ryan White HIV services.',
 'Free clinic in Savannah.',
 (select id from categories where slug = 'healthcare'),
 'https://www.cvcphc.org', '(912) 527-1000',
 '106 E Jones St, Savannah, GA 31401', 'Savannah', 'GA', '31401',
 32.0793, -81.0928, '{en,es}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, false),

('Emory Family Medicine Clinic — Dunwoody',
 'Emory Healthcare family medicine practice — primary care for adults and children.',
 'Emory family medicine practice.',
 (select id from categories where slug = 'healthcare'),
 'https://www.emoryhealthcare.org', '(404) 778-7777',
 '4500 N Shallowford Rd Suite 209, Dunwoody, GA 30338', 'Dunwoody', 'GA', '30338',
 33.9229, -84.3133, '{en,es}', false, true, 'Mon — Fri 8am — 5pm',
 false, false, false, true, true, false),

('Piedmont Healthcare Urgent Care — Vinings',
 'Walk-in urgent care for non-life-threatening illness and injury — Piedmont system.',
 'Piedmont walk-in urgent care.',
 (select id from categories where slug = 'healthcare'),
 'https://www.piedmont.org/urgent-care', '(833) 528-1287',
 '4480 Atlanta Rd SE Suite 102, Smyrna, GA 30080', 'Smyrna', 'GA', '30080',
 33.8757, -84.4774, '{en,es}', false, true, 'Mon — Fri 8am — 8pm, Sat — Sun 9am — 5pm',
 true, true, true, true, true, false),

('PrEP Atlanta — AIDS Healthcare Foundation Clinic',
 'Free HIV testing, PrEP, PEP, and sexual-health services for the LGBTQ community.',
 'Free HIV testing and PrEP services.',
 (select id from categories where slug = 'healthcare'),
 'https://www.aidshealth.org', '(404) 870-4101',
 '1605 Chantilly Dr NE Suite 100, Atlanta, GA 30324', 'Atlanta', 'GA', '30324',
 33.8120, -84.3517, '{en,es}', true, true, 'Mon — Fri 9am — 6pm',
 true, false, true, true, true, true),

('Saint Joseph''s Mercy Care — Refugee Services',
 'Comprehensive primary care for refugees and uninsured immigrants — bilingual staff and interpreters.',
 'Comprehensive primary care for refugees.',
 (select id from categories where slug = 'healthcare'),
 'https://www.mercyatlanta.org', '(404) 880-3500',
 '424 Decatur St SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7521, -84.3781, '{en,es,ar,fr,sw,am}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

('Clarkston Community Health Center',
 'Free volunteer-run clinic for uninsured immigrants and refugees in Clarkston.',
 'Free volunteer clinic in Clarkston.',
 (select id from categories where slug = 'healthcare'),
 'https://clarkstonhealth.org', '(770) 998-2727',
 '4151 Memorial Dr Suite 102B, Decatur, GA 30032', 'Decatur', 'GA', '30032',
 33.7726, -84.2963, '{en,es,ar,fr,sw,am,my,ne}', true, true, 'Wed evenings, Sat 9am — 12pm',
 true, true, true, true, true, true),

('Cobb Community Pediatric Clinic',
 'Free pediatric primary care for uninsured low-income children in Cobb County.',
 'Free pediatric primary care in Cobb.',
 (select id from categories where slug = 'healthcare'),
 'https://goodsamcobb.org', '(770) 419-3120',
 '1605 Roberta Dr SW, Marietta, GA 30008', 'Marietta', 'GA', '30008',
 33.9034, -84.5664, '{en,es}', true, true, 'Mon — Thu 8am — 5pm',
 false, false, false, true, true, false),

('Mercy Care Atlanta — Chamblee',
 'Federally qualified health center serving uninsured and Medicaid patients in Chamblee.',
 'Free clinic for uninsured in Chamblee.',
 (select id from categories where slug = 'healthcare'),
 'https://www.mercyatlanta.org', '(678) 843-8800',
 '5345 New Peachtree Rd, Chamblee, GA 30341', 'Chamblee', 'GA', '30341',
 33.8855, -84.2961, '{en,es,zh,vi,ko}', true, true, 'Mon — Fri 8am — 5pm',
 true, false, false, true, true, true),

-- ============== HOUSING — TOP HOUSING SERVICES ==============
('Habitat for Humanity — Gwinnett & DeKalb',
 'Habitat affiliate building affordable homes and offering home-buyer education in Gwinnett and DeKalb.',
 'Affordable home-building in Gwinnett and DeKalb.',
 (select id from categories where slug = 'housing'),
 'https://habitatgwinnett.org', '(770) 931-8080',
 '750 Hi Hope Ln, Lawrenceville, GA 30043', 'Lawrenceville', 'GA', '30043',
 33.9858, -83.9930, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 true, true, false, true, true, true),

('NeighborWorks Columbus',
 'Affordable housing developer and home-buyer education in Columbus, GA.',
 'Affordable housing in Columbus.',
 (select id from categories where slug = 'housing'),
 'https://www.neighborworkscolumbus.org', '(706) 322-4020',
 '1554 13th St, Columbus, GA 31901', 'Columbus', 'GA', '31901',
 32.4738, -84.9885, '{en,es}', true, true, 'Mon — Fri 8:30am — 5pm',
 false, false, false, true, true, false),

('Atlanta Neighborhood Development Partnership (ANDP)',
 'Affordable housing developer and lender — single-family homes for working families in Atlanta.',
 'Affordable home developer and lender.',
 (select id from categories where slug = 'housing'),
 'https://andpi.org', '(404) 420-1600',
 '230 Peachtree St NW Suite 1409, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7592, -84.3879, '{en,es}', false, true, 'Mon — Fri 9am — 5pm',
 false, false, false, true, true, false),

('Decatur Cooperative Ministry',
 'Faith-based housing nonprofit providing emergency shelter, transitional housing, and rapid rehousing.',
 'Faith-based housing nonprofit.',
 (select id from categories where slug = 'housing'),
 'https://decaturcooperativeministry.org', '(404) 377-5365',
 '705 Commerce Dr, Decatur, GA 30030', 'Decatur', 'GA', '30030',
 33.7748, -84.3068, '{en,es}', true, true, 'Mon — Fri 9am — 5pm',
 true, false, false, true, true, false),

('Gateway Center (Atlanta)',
 'Atlanta''s largest day-resource center for adults experiencing homelessness — assessments, housing.',
 'Largest day-resource center for homeless.',
 (select id from categories where slug = 'housing'),
 'https://www.gatewayctr.org', '(404) 215-6600',
 '275 Pryor St SW, Atlanta, GA 30303', 'Atlanta', 'GA', '30303',
 33.7479, -84.3893, '{en,es}', true, true, 'Mon — Fri 7am — 7pm',
 true, false, false, true, true, true),

('Nicholas House',
 'Family shelter and housing program for families experiencing homelessness — Atlanta.',
 'Family shelter and housing program.',
 (select id from categories where slug = 'housing'),
 'https://www.nicholashouse.org', '(404) 622-0793',
 '830 Boulevard SE, Atlanta, GA 30312', 'Atlanta', 'GA', '30312',
 33.7359, -84.3729, '{en,es}', true, true, '24/7',
 true, true, true, true, true, true),

('My Sister''s House — Atlanta Mission',
 'Women and children''s emergency shelter and recovery program — part of Atlanta Mission.',
 'Women and children emergency shelter.',
 (select id from categories where slug = 'housing'),
 'https://atlantamission.org', '(404) 367-2419',
 '921 Howell Mill Rd NW, Atlanta, GA 30318', 'Atlanta', 'GA', '30318',
 33.7807, -84.4124, '{en,es}', true, true, '24/7',
 true, true, true, true, true, true),

('City of Refuge (Atlanta)',
 'Westside Atlanta nonprofit providing shelter, job training, and youth programs to families in need.',
 'Westside shelter and job training.',
 (select id from categories where slug = 'housing'),
 'https://cityofrefugeatl.org', '(404) 874-2241',
 '1300 Joseph E Boone Blvd NW, Atlanta, GA 30314', 'Atlanta', 'GA', '30314',
 33.7686, -84.4232, '{en,es}', true, true, 'Mon — Fri 8am — 6pm',
 true, true, true, true, true, true),

('Norcross Cooperative Ministry',
 'Food pantry, financial assistance, and counseling for families in northwest Gwinnett.',
 'Food pantry and family assistance.',
 (select id from categories where slug = 'housing'),
 'https://norcrosscoop.org', '(770) 263-8268',
 '500 Hunter St, Norcross, GA 30071', 'Norcross', 'GA', '30071',
 33.9402, -84.2128, '{en,es}', true, true, 'Mon — Fri 9am — 4pm',
 true, false, false, true, true, false),

('Lawrenceville Cooperative Ministry',
 'Food pantry, financial assistance, and clothing for families in Gwinnett County.',
 'Food pantry and family assistance.',
 (select id from categories where slug = 'housing'),
 'https://www.lawrencevillecoop.org', '(770) 963-1640',
 '52 Gwinnett Dr, Lawrenceville, GA 30046', 'Lawrenceville', 'GA', '30046',
 33.9550, -83.9959, '{en,es}', true, true, 'Mon — Fri 9am — 4pm',
 true, false, false, true, true, false)

on conflict do nothing;