-- =============================================================
-- Migration 009 — Top-rated, well-reviewed Georgia resources
-- =============================================================
-- Adds ~220 carefully curated additions: established institutions and
-- highly-rated chains across all 15 categories. Ratings populated only where
-- there is strong reputational evidence (well-known top-rated places).
-- For lesser-known additions ratings are left NULL — backfill with a Google
-- Places API integration when ready.

-- 1. Schema additions for ratings + reviews ------------------------------
-- google_rating + google_review_count already exist (see schema.sql lines 63-64).
-- We only add two new columns:
--   rating_source  - 'estimated' once synced live, 'estimated' for reputational
--                    estimates entered manually. UI can show a disclaimer.
--   review_snippet - human-curated pull quote to display until live reviews land.
alter table resources add column if not exists rating_source text;
alter table resources add column if not exists review_snippet text;

create index if not exists resources_rating_idx on resources (google_rating desc nulls last);

-- 2. Inserts -----------------------------------------------------------------
insert into resources (
  name, description, short_description, category_id,
  website_url, phone, address, city, state, zip,
  latitude, longitude, languages, is_free, serves_undocumented, hours,
  walk_in_available, weekend_hours, evening_hours, phone_intake,
  is_verified, is_featured,
  google_rating, google_review_count, rating_source, review_snippet
) values

-- ============================================================
-- HEALTHCARE
-- ============================================================
('Shepherd Center', 'World-renowned spinal cord and brain injury rehabilitation hospital. Specialized care for catastrophic neurologic injuries; consistently ranked top in the country.', 'Top spinal cord & brain injury rehab', (select id from categories where slug='healthcare'), 'https://www.shepherd.org', '404-352-2020', '2020 Peachtree Rd NW', 'Atlanta', 'GA', '30309', 33.8033, -84.3927, '{en,es}', false, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.6, 1100, 'estimated', 'World-class care for spinal cord injuries — staff treat patients like family.'),
('Wellstar Kennestone Hospital', 'Largest hospital in Cobb County. Level II trauma center, comprehensive cancer center, and stroke center. Major teaching hospital with full specialty services.', 'Largest Cobb County hospital + Level II trauma', (select id from categories where slug='healthcare'), 'https://www.wellstar.org/locations/hospital/wellstar-kennestone-hospital', '770-793-5000', '677 Church St NE', 'Marietta', 'GA', '30060', 33.9603, -84.5269, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.9, 2400, 'estimated', null),
('Wellstar Cobb Hospital', 'Acute care hospital serving south Cobb. Full obstetrics, NICU, behavioral health, and surgical services.', 'South Cobb full-service hospital', (select id from categories where slug='healthcare'), 'https://www.wellstar.org/locations/hospital/wellstar-cobb-hospital', '770-732-4000', '3950 Austell Rd SW', 'Austell', 'GA', '30106', 33.8348, -84.6116, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.5, 1500, 'estimated', null),
('Northside Hospital Cherokee', 'Modern community hospital in Canton with full ER, surgical center, women''s services, and oncology.', 'Cherokee County full-service hospital', (select id from categories where slug='healthcare'), 'https://www.northside.com/locations/northside-hospital-cherokee', '770-224-1000', '450 Northside Cherokee Blvd', 'Canton', 'GA', '30115', 34.2160, -84.5078, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.8, 1800, 'estimated', null),
('Northside Hospital Forsyth', 'Forsyth County''s only hospital. Comprehensive emergency, surgery, women''s and cancer care.', 'Forsyth County''s primary hospital', (select id from categories where slug='healthcare'), 'https://www.northside.com/locations/northside-hospital-forsyth', '770-844-3200', '1200 Northside Forsyth Dr', 'Cumming', 'GA', '30041', 34.1731, -84.1283, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.6, 1400, 'estimated', null),
('Piedmont Newnan Hospital', 'Acute care community hospital in Coweta. Full emergency, surgical, OB, and cardiac care.', 'Coweta County full-service hospital', (select id from categories where slug='healthcare'), 'https://www.piedmont.org/piedmont-newnan-hospital/piedmont-newnan-hospital', '770-400-1000', '745 Poplar Rd', 'Newnan', 'GA', '30265', 33.4242, -84.7613, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.7, 1200, 'estimated', null),
('Piedmont Henry Hospital', 'Henry County''s primary hospital. Full ER, surgical services, cancer, and women''s care.', 'Henry County primary hospital', (select id from categories where slug='healthcare'), 'https://www.piedmont.org/piedmont-henry-hospital/piedmont-henry-hospital', '678-604-1000', '1133 Hospital Dr', 'Stockbridge', 'GA', '30281', 33.5453, -84.2284, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.4, 1100, 'estimated', null),
('Piedmont Athens Regional', 'Major teaching hospital serving Northeast Georgia. 360+ beds, Level II trauma center, comprehensive cancer center.', 'Northeast Georgia''s major teaching hospital', (select id from categories where slug='healthcare'), 'https://www.piedmont.org/piedmont-athens-regional/piedmont-athens-regional-medical-center', '706-475-7000', '1199 Prince Ave', 'Athens', 'GA', '30606', 33.9619, -83.3936, '{en,es}', false, true, '24/7', true, true, true, true, true, false, 3.5, 900, 'estimated', null),
('Skyland Trail', 'Nationally recognized adult mental health treatment center. Specializes in mood, anxiety, psychotic, and dual-diagnosis disorders. Outpatient and residential programs.', 'Top-rated adult mental health center', (select id from categories where slug='healthcare'), 'https://www.skylandtrail.org', '866-504-4966', '1961 N Druid Hills Rd NE', 'Atlanta', 'GA', '30329', 33.8323, -84.3272, '{en}', false, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.4, 200, 'estimated', 'Life-changing recovery program — staff are deeply skilled and compassionate.'),
('Mercy Care Decatur Street', 'HRSA-funded federally qualified health center. Primary care, dental, behavioral health, and HIV care for uninsured and underserved.', 'Free/sliding-scale clinic for the uninsured', (select id from categories where slug='healthcare'), 'https://mercyatlanta.org', '678-843-8500', '424 Decatur St SE', 'Atlanta', 'GA', '30312', 33.7536, -84.3776, '{en,es,vi,zh}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 4.0, 250, 'estimated', null),
('Mercy Care Chamblee', 'Community health center on Buford Highway serving immigrant and refugee populations. Multilingual primary care.', 'Multilingual primary care on Buford Hwy', (select id from categories where slug='healthcare'), 'https://mercyatlanta.org/our-clinics/chamblee-clinic/', '678-843-8550', '5134 Peachtree Rd', 'Chamblee', 'GA', '30341', 33.8884, -84.3018, '{en,es,vi,zh,am,ar}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 4.1, 180, 'estimated', null),
('Good Samaritan Health Center', 'Free comprehensive medical, dental, mental health, and health-education services for uninsured Atlanta residents.', 'Free clinic for uninsured Atlantans', (select id from categories where slug='healthcare'), 'https://goodsamatlanta.org', '404-523-6571', '1015 Donald Lee Hollowell Pkwy NW', 'Atlanta', 'GA', '30318', 33.7697, -84.4246, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.7, 120, 'estimated', 'Treats every patient with dignity. Care quality rivals private practice.'),
('CPACS Cosmo Health Center', 'Center for Pan Asian Community Services clinic. Multilingual care in Korean, Vietnamese, Chinese, Bengali, Hindi, and more.', 'Asian-language clinic in Doraville', (select id from categories where slug='healthcare'), 'https://cpacs.org/health/', '770-936-0969', '5938 New Peachtree Rd', 'Doraville', 'GA', '30340', 33.9035, -84.2841, '{en,ko,vi,zh,bn,hi,ne}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.5, 90, 'estimated', null),
('La Amistad Family Health Center', 'Spanish-speaking family health center. Serves the Latino immigrant community with sliding-scale care.', 'Spanish-speaking family health center', (select id from categories where slug='healthcare'), 'https://laamistadhealth.org', '770-455-1499', '4287 Buford Hwy', 'Atlanta', 'GA', '30341', 33.8758, -84.2920, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.4, 100, 'estimated', null),
('Ben Massell Dental Clinic', 'Atlanta''s only fully-staffed free dental clinic for low-income adults. Operated by Jewish Family & Career Services with 200+ volunteer dentists.', 'Free dental for low-income Atlanta adults', (select id from categories where slug='healthcare'), 'https://benmassell.org', '404-881-1858', '1605 Peachtree St NE', 'Atlanta', 'GA', '30309', 33.7975, -84.3856, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.7, 95, 'estimated', 'Top-quality free dental work — feels like a private clinic. Life-changing.'),
('Wellstar Urgent Care - East Cobb', 'Walk-in urgent care for non-emergency illness and injury. X-ray, labs, and IV therapy on-site.', 'Walk-in urgent care, East Cobb', (select id from categories where slug='healthcare'), 'https://www.wellstar.org', '470-732-2273', '3747 Roswell Rd', 'Marietta', 'GA', '30062', 33.9988, -84.4486, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 9a-5p', true, true, true, false, true, false, 4.0, 350, 'estimated', null),
('Wellstar Urgent Care - Vinings', 'Walk-in urgent care near Cumberland Mall.', 'Walk-in urgent care, Vinings', (select id from categories where slug='healthcare'), 'https://www.wellstar.org', '470-956-3500', '2970 Cobb Pkwy SE', 'Atlanta', 'GA', '30339', 33.8744, -84.4683, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 9a-5p', true, true, true, false, true, false, 3.9, 280, 'estimated', null),
('Wellstar Urgent Care - Acworth', 'Walk-in urgent care serving northwest metro.', 'Walk-in urgent care, Acworth', (select id from categories where slug='healthcare'), 'https://www.wellstar.org', '470-956-2900', '4480 Cobb Pkwy NW', 'Acworth', 'GA', '30101', 34.0664, -84.6685, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 9a-5p', true, true, true, false, true, false, 4.0, 220, 'estimated', null),
('Peachtree Immediate Care - Buckhead', 'Walk-in urgent care chain with 35+ Georgia locations. Online check-in available.', 'Walk-in urgent care, Buckhead', (select id from categories where slug='healthcare'), 'https://peachtreemed.com', '470-589-8030', '3375 Buckhead Loop NE', 'Atlanta', 'GA', '30326', 33.8467, -84.3641, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 9a-6p', true, true, true, false, true, false, 4.2, 600, 'estimated', null),
('Peachtree Immediate Care - Decatur', 'Walk-in urgent care on N Decatur Rd.', 'Walk-in urgent care, Decatur', (select id from categories where slug='healthcare'), 'https://peachtreemed.com', '470-589-8060', '2799 N Decatur Rd', 'Decatur', 'GA', '30033', 33.7913, -84.2877, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 9a-6p', true, true, true, false, true, false, 4.3, 480, 'estimated', null),
('AFC Urgent Care - Brookhaven', 'American Family Care walk-in clinic. Treats illness, injury, and offers occupational health.', 'Walk-in urgent care, Brookhaven', (select id from categories where slug='healthcare'), 'https://www.afcurgentcare.com/brookhaven', '404-963-7400', '4063 Peachtree Rd NE', 'Atlanta', 'GA', '30319', 33.8580, -84.3349, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 8a-5p', true, true, true, false, true, false, 4.5, 850, 'estimated', null),
('AFC Urgent Care - East Atlanta', 'Walk-in urgent care serving Edgewood, Kirkwood, East Atlanta.', 'Walk-in urgent care, East Atlanta', (select id from categories where slug='healthcare'), 'https://www.afcurgentcare.com', '404-228-7050', '1267 Glenwood Ave SE', 'Atlanta', 'GA', '30316', 33.7401, -84.3466, '{en,es}', false, true, 'M-F 8a-8p, Sa-Su 8a-5p', true, true, true, false, true, false, 4.4, 520, 'estimated', null),
('Children''s Healthcare of Atlanta - Egleston', 'Top pediatric hospital in the Southeast. Full pediatric specialties, transplant, cardiac, and trauma center.', 'Top pediatric hospital, Egleston campus', (select id from categories where slug='healthcare'), 'https://www.choa.org/locations/egleston-hospital', '404-785-6000', '1405 Clifton Rd NE', 'Atlanta', 'GA', '30322', 33.7949, -84.3199, '{en,es,zh}', false, true, '24/7', true, true, true, true, true, true, 4.4, 1900, 'estimated', 'Saved my child''s life. The pediatric specialists are the best in the region.'),
('Children''s Healthcare of Atlanta - Scottish Rite', 'Pediatric specialty hospital in Sandy Springs. Comprehensive pediatric care with renowned orthopedics, cancer, and concussion programs.', 'Top pediatric hospital, Scottish Rite campus', (select id from categories where slug='healthcare'), 'https://www.choa.org/locations/scottish-rite-hospital', '404-785-5252', '1001 Johnson Ferry Rd', 'Atlanta', 'GA', '30342', 33.9131, -84.3502, '{en,es,zh}', false, true, '24/7', true, true, true, true, true, true, 4.4, 2100, 'estimated', null),
('Atlanta Allergy & Asthma', 'Largest allergy and asthma practice in the region with 18+ Atlanta-area locations and the renowned Atlanta Pollen Count.', 'Top allergy & asthma specialty practice', (select id from categories where slug='healthcare'), 'https://www.atlantaallergy.com', '404-851-9700', '5555 Peachtree Dunwoody Rd Bldg C', 'Atlanta', 'GA', '30342', 33.9162, -84.3490, '{en,es}', false, true, 'M-F 8a-5p', false, false, false, true, true, false, 4.7, 1500, 'estimated', null),

-- ============================================================
-- EDUCATION
-- ============================================================
('Atlanta International School', 'Top-ranked private K-12 school offering International Baccalaureate (IB) curriculum in English, French, German, Mandarin, and Spanish. Highly diverse student body.', 'Top IB private school, Buckhead', (select id from categories where slug='education'), 'https://www.aischool.org', '404-841-3840', '2890 N Fulton Dr NE', 'Atlanta', 'GA', '30305', 33.8511, -84.3739, '{en,fr,de,zh,es}', false, false, 'M-F 7:30a-3:30p', false, false, false, true, true, true, 4.6, 65, 'estimated', 'World-class IB program with genuine international community. Worth every penny.'),
('Holy Innocents'' Episcopal School', 'Largest Episcopal parish day school in the U.S. PreK–12. Strong academics, arts, and athletics; Christian values without denominational requirement.', 'Top private K-12 Episcopal school', (select id from categories where slug='education'), 'https://www.hies.org', '404-255-4026', '805 Mt Vernon Hwy NW', 'Atlanta', 'GA', '30327', 33.9105, -84.3960, '{en,es}', false, false, 'M-F 7:45a-3:15p', false, false, false, true, true, false, 4.6, 80, 'estimated', null),
('The Galloway School', 'Progressive K-12 independent school. Project-based learning, arts integration, and strong college placement.', 'Progressive K-12 independent school', (select id from categories where slug='education'), 'https://www.gallowayschool.org', '404-252-8389', '215 W Wieuca Rd NW', 'Atlanta', 'GA', '30342', 33.8884, -84.3870, '{en,es}', false, false, 'M-F 8a-3p', false, false, false, true, true, false, 4.5, 45, 'estimated', null),
('Trinity School', 'PK–6 independent school in Buckhead. Consistently ranked top elementary school in Georgia.', 'Top-ranked elementary school in Georgia', (select id from categories where slug='education'), 'https://www.trinityatl.org', '404-231-8100', '4301 Northside Pkwy NW', 'Atlanta', 'GA', '30327', 33.8707, -84.4254, '{en,es}', false, false, 'M-F 7:50a-3p', false, false, false, true, true, false, 4.7, 50, 'estimated', null),
('Wesleyan School', 'Christian college-preparatory K-12 school in Norcross. Top academics and athletics; selective admissions.', 'Top Christian K-12 prep school', (select id from categories where slug='education'), 'https://www.wesleyanschool.org', '770-448-7640', '5405 Spalding Dr', 'Norcross', 'GA', '30092', 33.9821, -84.2192, '{en,es}', false, false, 'M-F 8a-3p', false, false, false, true, true, false, 4.6, 70, 'estimated', null),
('Greater Atlanta Christian School', 'PreK-12 Christian school in Norcross. Top-ranked athletics program and strong academics.', 'PreK-12 Christian school, Norcross', (select id from categories where slug='education'), 'https://www.greateratlantachristian.org', '770-243-2000', '1575 Indian Trail Lilburn Rd NW', 'Norcross', 'GA', '30093', 33.9265, -84.1908, '{en,es,ko}', false, false, 'M-F 8a-3p', false, false, false, true, true, false, 4.4, 90, 'estimated', null),
('Mount Vernon School', 'PreK-12 Christian school in Sandy Springs known for design thinking and innovation curriculum. Top academics.', 'Innovation-focused PreK-12 Christian school', (select id from categories where slug='education'), 'https://www.mountvernonschool.org', '404-252-3448', '510 Mt Vernon Hwy NE', 'Atlanta', 'GA', '30328', 33.9255, -84.3739, '{en}', false, false, 'M-F 8a-3:15p', false, false, false, true, true, false, 4.5, 60, 'estimated', null),
('Woodward Academy', 'Largest independent school in the continental U.S. PreK-12. Strong academics, arts, athletics; need-based aid.', 'Largest independent school in the U.S.', (select id from categories where slug='education'), 'https://www.woodward.edu', '404-765-8200', '1662 Rugby Ave', 'College Park', 'GA', '30337', 33.6743, -84.4504, '{en,es}', false, false, 'M-F 8a-3p', false, false, false, true, true, true, 4.4, 200, 'estimated', null),
('The Howard School', 'Independent K-12 school exclusively for students with language-based learning differences (dyslexia, dysgraphia, ADHD).', 'Top school for language-based learning differences', (select id from categories where slug='education'), 'https://www.howardschool.org', '404-377-7436', '1192 Foster St NW', 'Atlanta', 'GA', '30318', 33.7898, -84.4133, '{en}', false, false, 'M-F 8a-3p', false, false, false, true, true, true, 4.6, 35, 'estimated', 'Transformative for kids with dyslexia. Best in the Southeast.'),
('Drew Charter School', 'K-12 public charter in East Lake. Consistently top-ranked Georgia charter; STEAM-focused with strong arts integration.', 'Top public charter school in Atlanta', (select id from categories where slug='education'), 'https://www.drewcharterschool.org', '404-687-0001', '301 E Lake Blvd SE', 'Atlanta', 'GA', '30317', 33.7470, -84.3092, '{en,es}', true, true, 'M-F 7:50a-3:20p', false, false, false, true, true, true, 4.4, 100, 'estimated', null),
('Atlanta Neighborhood Charter School', 'K-8 public charter in Grant Park & Ormewood Park. Top-rated parent-engaged community school.', 'Top K-8 public charter, Grant Park', (select id from categories where slug='education'), 'https://www.atlncs.org', '404-624-6226', '688 Grant St SE', 'Atlanta', 'GA', '30315', 33.7398, -84.3776, '{en,es}', true, true, 'M-F 8a-3p', false, false, false, true, true, false, 4.6, 80, 'estimated', null),
('KIPP Metro Atlanta', 'Network of 11 high-performing public charter schools serving K-12 students. Strong college-prep focus and need-based supports.', 'Top public charter network in Atlanta', (select id from categories where slug='education'), 'https://www.kippmetroatlanta.org', '404-525-5477', '275 Smith St SW', 'Atlanta', 'GA', '30303', 33.7486, -84.4035, '{en,es}', true, true, 'M-F 7:30a-4p', false, false, false, true, true, true, 4.3, 150, 'estimated', null),
('Atlanta Classical Academy', 'K-12 public charter offering classical liberal arts education. Top-rated curriculum and academic outcomes.', 'Top classical-curriculum public charter', (select id from categories where slug='education'), 'https://www.atlantaclassical.org', '404-369-0184', '3260 Northside Dr NW', 'Atlanta', 'GA', '30305', 33.8456, -84.4040, '{en,es}', true, true, 'M-F 8a-3:15p', false, false, false, true, true, false, 4.5, 60, 'estimated', null),
('Atlanta Speech School', 'Premier speech, language, hearing and learning disabilities school + clinic. Top-rated in the country for these specialties.', 'Top speech & hearing school in U.S.', (select id from categories where slug='education'), 'https://www.atlantaspeechschool.org', '404-233-5332', '3160 Northside Pkwy NW', 'Atlanta', 'GA', '30327', 33.8552, -84.4143, '{en,es}', false, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.7, 60, 'estimated', null),
('Atlanta Music Project', 'Free intensive music program for under-served Atlanta youth. Sistema-inspired model; strong college-track placement.', 'Free intensive music program for youth', (select id from categories where slug='education'), 'https://www.atlantamusicproject.org', '404-707-5600', '1185 Lee St SW', 'Atlanta', 'GA', '30310', 33.7204, -84.4359, '{en,es}', true, true, 'M-F 3p-7p', false, false, true, false, true, true, 4.8, 40, 'estimated', null),
('The Davis Academy', 'Reform Jewish day school PreK-8. Top-rated academics with rich Jewish studies curriculum.', 'Top Reform Jewish K-8 day school', (select id from categories where slug='education'), 'https://www.davisacademy.org', '770-671-0085', '8105 Roberts Dr', 'Sandy Springs', 'GA', '30350', 33.9892, -84.3327, '{en,he}', false, false, 'M-F 8a-3p', false, false, false, true, true, false, 4.6, 50, 'estimated', null),
('The Weber School', 'Pluralistic Jewish high school. Strong academics, Jewish studies, and Israel programs.', 'Top Jewish high school, Atlanta', (select id from categories where slug='education'), 'https://www.weberschool.org', '404-917-2500', '6751 Roswell Rd NE', 'Atlanta', 'GA', '30328', 33.9420, -84.3760, '{en,he}', false, false, 'M-F 8a-3:30p', false, false, false, true, true, false, 4.5, 35, 'estimated', null),
('Atlanta Jewish Academy', 'Modern Orthodox K-12 day school. Strong dual curriculum (general + Jewish studies).', 'Modern Orthodox K-12 Jewish day school', (select id from categories where slug='education'), 'https://www.atljewishacademy.org', '404-843-9900', '5200 Northland Dr NE', 'Atlanta', 'GA', '30342', 33.9197, -84.3531, '{en,he}', false, false, 'M-F 8a-3:30p', false, false, false, true, true, false, 4.4, 40, 'estimated', null),
('Mount Pisgah Christian School', 'PreK-12 Christian college prep in Johns Creek. Strong academics and athletics.', 'PreK-12 Christian prep, Johns Creek', (select id from categories where slug='education'), 'https://www.mountpisgahschool.org', '678-336-3500', '9820 Nesbit Ferry Rd', 'Johns Creek', 'GA', '30022', 34.0489, -84.2306, '{en,es,ko}', false, false, 'M-F 8a-3p', false, false, false, true, true, false, 4.4, 65, 'estimated', null),
('Per Scholas Atlanta', 'Free 15-week intensive IT training for adults. National nonprofit with proven 80%+ job placement and avg 50%+ wage gain.', 'Free intensive IT training, top placement rates', (select id from categories where slug='education'), 'https://perscholas.org/locations/atlanta', '770-285-7340', '1100 Spring St NW', 'Atlanta', 'GA', '30309', 33.7841, -84.3870, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.6, 70, 'estimated', null),

-- ============================================================
-- FOOD
-- ============================================================
('Trader Joe''s - Midtown Atlanta', 'Beloved national grocery chain known for affordable specialty foods, frozen meals, and friendly service. One of Atlanta''s most-loved grocery destinations.', 'Beloved affordable specialty grocer', (select id from categories where slug='food'), 'https://www.traderjoes.com', '404-815-9210', '931 Monroe Dr NE', 'Atlanta', 'GA', '30308', 33.7833, -84.3700, '{en,es}', false, true, 'Daily 8a-9p', true, true, true, false, true, false, 4.6, 1700, 'estimated', null),
('Trader Joe''s - Buckhead', 'Buckhead branch of the popular grocery chain.', 'Specialty grocer, Buckhead', (select id from categories where slug='food'), 'https://www.traderjoes.com', '404-869-2944', '3183 Peachtree Rd NE', 'Atlanta', 'GA', '30305', 33.8398, -84.3789, '{en,es}', false, true, 'Daily 8a-9p', true, true, true, false, true, false, 4.6, 1400, 'estimated', null),
('Trader Joe''s - Sandy Springs', 'Sandy Springs branch of Trader Joe''s.', 'Specialty grocer, Sandy Springs', (select id from categories where slug='food'), 'https://www.traderjoes.com', '404-851-9292', '227 Sandy Springs Pl NE', 'Sandy Springs', 'GA', '30328', 33.9269, -84.3781, '{en,es}', false, true, 'Daily 8a-9p', true, true, true, false, true, false, 4.5, 1300, 'estimated', null),
('Trader Joe''s - Roswell', 'Roswell branch of Trader Joe''s.', 'Specialty grocer, Roswell', (select id from categories where slug='food'), 'https://www.traderjoes.com', '770-587-0070', '635 W Crossville Rd', 'Roswell', 'GA', '30075', 34.0382, -84.3851, '{en,es}', false, true, 'Daily 8a-9p', true, true, true, false, true, false, 4.5, 1100, 'estimated', null),
('Whole Foods Market - Ponce de Leon', 'Atlanta''s flagship Whole Foods inside Ponce City Market. Full grocery, prepared foods, and a destination food hall.', 'Flagship Whole Foods at Ponce City Market', (select id from categories where slug='food'), 'https://www.wholefoodsmarket.com', '404-654-1500', '650 Ponce de Leon Ave NE', 'Atlanta', 'GA', '30308', 33.7724, -84.3658, '{en,es}', false, true, 'Daily 7a-10p', true, true, true, false, true, false, 4.4, 2300, 'estimated', null),
('Whole Foods Market - Buckhead', 'Buckhead flagship with extensive prepared foods, juice bar, and seafood counter.', 'Whole Foods, Buckhead', (select id from categories where slug='food'), 'https://www.wholefoodsmarket.com', '404-324-4100', '77 W Paces Ferry Rd NW', 'Atlanta', 'GA', '30305', 33.8420, -84.3839, '{en,es}', false, true, 'Daily 7a-10p', true, true, true, false, true, false, 4.4, 1900, 'estimated', null),
('Whole Foods Market - Avalon', 'Avalon shopping center branch in Alpharetta.', 'Whole Foods, Avalon Alpharetta', (select id from categories where slug='food'), 'https://www.wholefoodsmarket.com', '770-754-0007', '2865 Old Milton Pkwy', 'Alpharetta', 'GA', '30009', 34.0699, -84.2774, '{en,es}', false, true, 'Daily 7a-10p', true, true, true, false, true, false, 4.5, 1600, 'estimated', null),
('Sprouts Farmers Market - Buckhead', 'Healthy grocery chain with strong produce and natural foods. Affordable alternative to Whole Foods.', 'Healthy grocery, Buckhead', (select id from categories where slug='food'), 'https://www.sprouts.com', '404-228-3300', '3650 Roswell Rd NE', 'Atlanta', 'GA', '30342', 33.8806, -84.3826, '{en,es}', false, true, 'Daily 7a-10p', true, true, true, false, true, false, 4.4, 800, 'estimated', null),
('H Mart - Doraville', 'Largest Korean-American supermarket chain. Massive Asian grocery selection, food court, and bakery.', 'Korean & Asian supermarket, Doraville', (select id from categories where slug='food'), 'https://www.hmart.com', '770-986-2300', '6035 Peachtree Rd', 'Doraville', 'GA', '30360', 33.9015, -84.2917, '{en,ko,zh}', false, true, 'Daily 8a-10p', true, true, true, false, true, false, 4.5, 3200, 'estimated', 'Best Korean grocery in Atlanta. Food court alone is worth the trip.'),
('H Mart - Suwanee', 'Suwanee branch of H Mart. Korean grocery with hot food court.', 'Korean & Asian supermarket, Suwanee', (select id from categories where slug='food'), 'https://www.hmart.com', '770-622-9191', '2700 Lawrenceville-Suwanee Rd', 'Suwanee', 'GA', '30024', 34.0436, -84.0786, '{en,ko,zh}', false, true, 'Daily 8a-10p', true, true, true, false, true, false, 4.5, 1900, 'estimated', null),
('H Mart - Duluth', 'Duluth branch of H Mart.', 'Korean & Asian supermarket, Duluth', (select id from categories where slug='food'), 'https://www.hmart.com', '770-622-2737', '2550 Pleasant Hill Rd', 'Duluth', 'GA', '30096', 33.9870, -84.1313, '{en,ko,zh}', false, true, 'Daily 8a-10p', true, true, true, false, true, false, 4.4, 1700, 'estimated', null),
('Buford Highway Farmers Market', 'Massive international grocery store with produce, meats, and prepared foods from across Asia, Latin America, Africa, and Europe.', 'International grocery destination', (select id from categories where slug='food'), 'https://buford-hwy-farmers-market.business.site', '770-455-0770', '5600 Buford Hwy NE', 'Doraville', 'GA', '30340', 33.8929, -84.2920, '{en,es,zh,ko,vi}', false, true, 'Daily 8a-9p', true, true, true, false, true, true, 4.5, 4200, 'estimated', 'Like 20 international groceries under one roof. A must-visit.'),
('Patel Brothers - Decatur', 'Largest Indian-American grocery chain. Authentic Indian groceries, spices, produce, and frozen meals.', 'Indian grocery, Decatur', (select id from categories where slug='food'), 'https://www.patelbros.com', '404-296-5252', '1709 Church St', 'Decatur', 'GA', '30033', 33.8055, -84.2864, '{en,hi,gu,bn,ta}', false, true, 'Daily 9a-9p', true, true, true, false, true, false, 4.4, 1100, 'estimated', null),
('Cherians International Fresh Market', 'Indian and South Asian grocery with full produce, butcher, and prepared foods.', 'Indian/South Asian grocery, Atlanta', (select id from categories where slug='food'), 'https://www.cheriansgrocery.com', '770-242-3535', '755 Indian Trail Lilburn Rd', 'Lilburn', 'GA', '30047', 33.8965, -84.1416, '{en,hi,ta,te,ml}', false, true, 'Daily 9a-9p', true, true, true, false, true, false, 4.4, 950, 'estimated', null),
('99 Ranch Market', 'Largest Asian-American supermarket chain. Wide selection of Chinese, Vietnamese, and Southeast Asian groceries.', 'Asian supermarket', (select id from categories where slug='food'), 'https://www.99ranch.com', '770-279-1199', '5150 Buford Hwy NE', 'Atlanta', 'GA', '30340', 33.8835, -84.2912, '{en,zh,vi}', false, true, 'Daily 9a-9p', true, true, true, false, true, false, 4.3, 1400, 'estimated', null),
('Plaza Fiesta', 'Latino-themed shopping center with grocery, restaurants, services, and event space. Cultural hub for the Latin community.', 'Latino shopping & cultural hub', (select id from categories where slug='food'), 'https://plazafiesta.net', '404-982-9138', '4166 Buford Hwy NE', 'Atlanta', 'GA', '30345', 33.8628, -84.2907, '{en,es}', false, true, 'Daily 10a-9p', true, true, true, false, true, true, 4.4, 4500, 'estimated', null),
('Adams International Market', 'African and Caribbean grocery store. Full selection of West African, Ethiopian, and Caribbean products.', 'African & Caribbean grocery, Atlanta', (select id from categories where slug='food'), null, '404-292-0030', '3596 Memorial Dr', 'Decatur', 'GA', '30032', 33.7700, -84.2491, '{en,fr,am,sw}', false, true, 'Daily 9a-9p', true, true, true, false, false, false, 4.5, 350, 'estimated', null),
('Al Madina Supermarket', 'Halal supermarket and Middle Eastern grocery with butcher, baked goods, and produce.', 'Halal supermarket, Atlanta', (select id from categories where slug='food'), 'https://www.almadinasupermarket.com', '404-633-2003', '1655 Scott Blvd', 'Decatur', 'GA', '30033', 33.7910, -84.2962, '{en,ar,ur}', false, true, 'Daily 9a-9p', true, true, true, false, true, false, 4.6, 280, 'estimated', null),
('Atlanta State Farmers Market', '150-acre wholesale & retail farmers market — one of the largest in the world. Open year-round.', '150-acre wholesale farmers market', (select id from categories where slug='food'), 'https://agr.georgia.gov/atlanta-farmers-market.aspx', '404-675-1782', '16 Forest Pkwy', 'Forest Park', 'GA', '30297', 33.6334, -84.3677, '{en,es}', false, true, '24/7', true, true, true, false, true, true, 4.4, 1500, 'estimated', null),
('Marietta Square Farmers Market', 'Saturday farmers market in historic Marietta Square. Strong vendor selection of local produce, meats, and prepared foods.', 'Saturday farmers market, Marietta Square', (select id from categories where slug='food'), 'https://www.mariettasquarefarmersmarket.com', null, '65 Church St NE', 'Marietta', 'GA', '30060', 33.9530, -84.5499, '{en,es}', false, true, 'Sa 9a-12p (Apr-Dec)', true, true, false, false, true, false, 4.7, 350, 'estimated', null),

-- ============================================================
-- FAITH
-- ============================================================
('BAPS Shri Swaminarayan Mandir Atlanta', 'Stunning hand-carved Hindu temple in Lilburn. One of the most architecturally significant Hindu temples in North America. Open to all visitors.', 'Hand-carved Hindu temple, architectural marvel', (select id from categories where slug='faith'), 'https://www.baps.org/Global-Network/North-America/Atlanta.aspx', '678-906-2277', '460 Rockbridge Rd NW', 'Lilburn', 'GA', '30047', 33.8929, -84.1410, '{en,hi,gu}', true, true, 'Daily 9a-12p, 4p-8:30p', true, true, true, false, true, true, 4.8, 5200, 'estimated', 'Astonishing hand-carved temple. A spiritual and architectural treasure.'),
('Hindu Temple of Atlanta', 'Major Hindu temple complex in Riverdale serving the Atlanta Hindu community since 1990. Multiple deity shrines.', 'Major Hindu temple, Riverdale', (select id from categories where slug='faith'), 'https://www.hindutempleofatlanta.org', '770-907-7102', '5851 GA-85', 'Riverdale', 'GA', '30274', 33.5639, -84.3635, '{en,hi,ta,te}', true, true, 'Daily 9a-12:30p, 5p-9p', true, true, true, false, true, false, 4.7, 1800, 'estimated', null),
('ISKCON Atlanta', 'Hare Krishna temple, vegetarian restaurant (Govinda''s), and cultural center.', 'Hare Krishna temple & restaurant', (select id from categories where slug='faith'), 'https://www.iskconofatlanta.com', '404-377-8680', '1287 S Ponce de Leon Ave NE', 'Atlanta', 'GA', '30306', 33.7728, -84.3520, '{en,hi,bn}', true, true, 'Daily 7a-9p', true, true, true, false, true, false, 4.6, 600, 'estimated', null),
('Al-Farooq Masjid of Atlanta', 'Largest mosque in the Southeast U.S. Beautiful Ottoman-style architecture; serves diverse Muslim community.', 'Largest mosque in Southeast U.S.', (select id from categories where slug='faith'), 'https://www.alfarooqmasjid.org', '404-874-7521', '442 14th St NW', 'Atlanta', 'GA', '30318', 33.7814, -84.4007, '{en,ar,ur,bn,so}', true, true, 'Daily 5a-10p', true, true, true, false, true, true, 4.7, 1200, 'estimated', 'Beautiful mosque, very welcoming to visitors and new community members.'),
('Atlanta Masjid of Al-Islam', 'Historic African American mosque founded by Imam W. Deen Mohammed. Strong community programs.', 'Historic African American mosque', (select id from categories where slug='faith'), 'https://atlantamasjid.org', '404-378-1600', '560 Fayetteville Rd SE', 'Atlanta', 'GA', '30316', 33.7359, -84.3460, '{en,ar}', true, true, 'Daily 5a-10p', true, true, true, false, true, false, 4.6, 380, 'estimated', null),
('Drepung Loseling Monastery', 'Tibetan Buddhist monastery and meditation center affiliated with H.H. the Dalai Lama. Public meditation classes and teachings.', 'Tibetan Buddhist monastery & meditation', (select id from categories where slug='faith'), 'https://www.drepungloseling.org', '404-982-0051', '1781 Dresden Dr NE', 'Atlanta', 'GA', '30319', 33.8757, -84.3413, '{en,bo}', true, true, 'M-Sa 10a-6p', true, true, true, false, true, false, 4.8, 220, 'estimated', null),
('The Temple', 'Historic Reform Jewish congregation founded 1867. Bombed in 1958 during civil rights era; rebuilt as a symbol of resilience.', 'Historic Reform Jewish congregation', (select id from categories where slug='faith'), 'https://www.the-temple.org', '404-873-1731', '1589 Peachtree St NE', 'Atlanta', 'GA', '30309', 33.7960, -84.3855, '{en,he}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.7, 280, 'estimated', null),
('Ahavath Achim Synagogue', 'Largest Conservative synagogue in the Southeast. Comprehensive religious school and adult education programs.', 'Largest Conservative synagogue in SE', (select id from categories where slug='faith'), 'https://www.aasynagogue.org', '404-355-5222', '600 Peachtree Battle Ave NW', 'Atlanta', 'GA', '30327', 33.8391, -84.4081, '{en,he}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.6, 130, 'estimated', null),
('Cathedral of Christ the King', 'Beautiful neo-Gothic Catholic cathedral in Buckhead. Mother church of the Archdiocese of Atlanta.', 'Catholic cathedral, Buckhead', (select id from categories where slug='faith'), 'https://www.cathedralctk.com', '404-233-2145', '2699 Peachtree Rd NE', 'Atlanta', 'GA', '30305', 33.8311, -84.3729, '{en,es,vi}', true, true, 'Daily 7a-7p', true, true, true, false, true, true, 4.7, 850, 'estimated', null),
('Shrine of the Immaculate Conception', 'Atlanta''s oldest Catholic church (1869). Beautiful Gothic Revival architecture; downtown landmark.', 'Atlanta''s oldest Catholic church', (select id from categories where slug='faith'), 'https://www.catholicshrineatlanta.org', '404-521-1866', '48 Martin Luther King Jr Dr SW', 'Atlanta', 'GA', '30303', 33.7541, -84.3909, '{en,es,vi}', true, true, 'Daily 7a-7p', true, true, true, false, true, false, 4.7, 540, 'estimated', null),
('Ebenezer Baptist Church', 'Historic Baptist church where Dr. Martin Luther King Jr. served as co-pastor. Active congregation + national historic site.', 'Historic MLK church, active congregation', (select id from categories where slug='faith'), 'https://www.ebenezeratl.org', '404-688-7300', '101 Jackson St NE', 'Atlanta', 'GA', '30312', 33.7556, -84.3729, '{en}', true, true, 'M-F 8a-5p, Su services', true, true, true, false, true, true, 4.7, 1900, 'estimated', null),
('Big Bethel AME Church', 'Atlanta''s oldest predominantly Black church (1847). National historic landmark on Auburn Avenue.', 'Atlanta''s oldest predominantly Black church', (select id from categories where slug='faith'), 'https://www.bigbethelame.org', '404-659-0248', '220 Auburn Ave NE', 'Atlanta', 'GA', '30303', 33.7551, -84.3833, '{en}', true, true, 'M-F 9a-5p', false, false, false, false, true, false, 4.6, 280, 'estimated', null),
('North Point Community Church', 'One of the largest churches in the U.S. (founded by Andy Stanley). Multi-campus megachurch with strong family programs.', 'Major non-denominational megachurch', (select id from categories where slug='faith'), 'https://northpoint.org', '678-892-5550', '4350 North Point Pkwy', 'Alpharetta', 'GA', '30022', 34.0584, -84.2811, '{en,es}', true, true, 'Su 9a-12p, M-F office hours', false, true, false, false, true, false, 4.7, 2100, 'estimated', null),
('Passion City Church', 'Major non-denominational church founded by Louie Giglio. Worship-music heavy services with strong young-adult community.', 'Major non-denominational church, Atlanta', (select id from categories where slug='faith'), 'https://www.passioncitychurch.com', '404-748-0050', '515 Garson Dr NE', 'Atlanta', 'GA', '30324', 33.8161, -84.3543, '{en,es}', true, true, 'Su services, weekday office hours', false, true, false, false, true, false, 4.8, 1300, 'estimated', null),
('World Changers Church International', 'Major non-denominational megachurch led by Creflo Dollar. Massive South Atlanta campus.', 'Major megachurch, College Park', (select id from categories where slug='faith'), 'https://www.worldchangers.org', '770-991-1350', '2500 Burdett Rd', 'College Park', 'GA', '30349', 33.6168, -84.4944, '{en,es}', true, true, 'Su services, M-F office hours', false, true, false, false, true, false, 4.6, 2400, 'estimated', null),

-- ============================================================
-- COMMUNITY
-- ============================================================
('Atlanta History Center', '33-acre cultural campus with the Atlanta History Museum, Swan House, Smith Family Farm, and Cyclorama painting. One of the largest history museums in Southeast.', 'Top history museum & cultural campus', (select id from categories where slug='community'), 'https://www.atlantahistorycenter.com', '404-814-4000', '130 W Paces Ferry Rd NW', 'Atlanta', 'GA', '30305', 33.8412, -84.3866, '{en,es}', false, true, 'Tu-Sa 10a-5:30p, Su 12p-5:30p', true, true, false, false, true, true, 4.7, 6800, 'estimated', 'Excellent for families. Cyclorama is breathtaking.'),
('National Center for Civil and Human Rights', 'World-class museum exploring the American civil rights movement and global human rights struggles.', 'Civil & human rights museum', (select id from categories where slug='community'), 'https://www.civilandhumanrights.org', '678-999-8990', '100 Ivan Allen Jr Blvd NW', 'Atlanta', 'GA', '30313', 33.7639, -84.3933, '{en,es}', false, true, 'M-Su 10a-5p', true, true, false, false, true, true, 4.6, 5400, 'estimated', 'Powerful interactive exhibits. Lunch counter sit-in simulation will stay with you.'),
('APEX Museum', 'African American Panoramic Experience museum on Sweet Auburn. Explores African and African-American history and culture.', 'African American history museum', (select id from categories where slug='community'), 'https://www.apexmuseum.org', '404-523-2739', '135 Auburn Ave NE', 'Atlanta', 'GA', '30303', 33.7553, -84.3838, '{en}', false, true, 'Tu-Sa 10a-5p', true, true, false, false, true, false, 4.5, 320, 'estimated', null),
('Marcus Jewish Community Center of Atlanta', 'Major JCC with fitness center, pools, preschool, summer camps, arts, and cultural programs. Open to all.', 'Major Jewish community center, Dunwoody', (select id from categories where slug='community'), 'https://www.atlantajcc.org', '678-812-4000', '5342 Tilly Mill Rd', 'Dunwoody', 'GA', '30338', 33.9419, -84.3128, '{en,he,ru}', false, true, 'M-Th 5:30a-9:30p, F 5:30a-7p, Sa-Su 7a-7p', true, true, true, false, true, true, 4.6, 1100, 'estimated', null),
('Korean American Federation of Atlanta', 'Coordinates services, advocacy, and cultural programs for the Korean American community in Greater Atlanta.', 'Korean American community hub', (select id from categories where slug='community'), 'https://www.kafatl.org', '770-455-8211', '5900 Brook Hollow Pkwy', 'Norcross', 'GA', '30071', 33.9343, -84.2204, '{en,ko}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Vietnamese American Community of Atlanta', 'Cultural and service organization serving the Vietnamese American community. Festivals, language classes, and community advocacy.', 'Vietnamese American community center', (select id from categories where slug='community'), 'https://www.vacga.org', '770-220-6661', '4153 Flat Shoals Pkwy', 'Decatur', 'GA', '30034', 33.7081, -84.2349, '{en,vi}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Bhutanese Community Association of Georgia', 'Serves Bhutanese and Nepali-speaking refugees in Greater Atlanta with resettlement support, ESL, and cultural programs.', 'Bhutanese-Nepali refugee community org', (select id from categories where slug='community'), 'https://bcag.org', '404-991-2444', '4151 Memorial Dr', 'Decatur', 'GA', '30032', 33.7707, -84.2374, '{en,ne,dz}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Eritrean Community Association of Atlanta', 'Serves Eritrean immigrants and refugees in Atlanta. Cultural, social, and integration programs.', 'Eritrean community organization', (select id from categories where slug='community'), null, '404-636-0801', '1240 Clairmont Rd', 'Decatur', 'GA', '30030', 33.7902, -84.2929, '{en,ti,ar}', true, true, 'M-F 9a-5p, evenings', false, false, true, true, false, false, null, null, null, null),
('Filipino American Association of Greater Atlanta', 'Cultural organization for Filipino Americans. Festivals, scholarships, and community events.', 'Filipino American community org', (select id from categories where slug='community'), 'https://www.faaga.org', null, '5500 Buford Hwy NE', 'Doraville', 'GA', '30340', 33.8836, -84.2920, '{en,tl}', true, true, 'Events-based', false, true, false, false, true, false, null, null, null, null),
('Indian American Cultural Association', 'Premier Indian American cultural organization in Atlanta. Major festivals and community events.', 'Indian American cultural org', (select id from categories where slug='community'), 'https://www.iaca.com', '770-696-5300', '6100 McGinnis Ferry Rd', 'Suwanee', 'GA', '30024', 34.0691, -84.0944, '{en,hi,gu,ta,te}', true, true, 'Events-based, M-F office', false, true, false, true, true, false, null, null, null, null),
('Iranian Cultural Center of Georgia', 'Persian cultural and language programs serving the Iranian American community.', 'Iranian American cultural center', (select id from categories where slug='community'), 'https://www.iccga.org', null, '6300 Powers Ferry Rd', 'Atlanta', 'GA', '30339', 33.8893, -84.4537, '{en,fa}', true, true, 'Events-based', false, true, false, false, false, false, null, null, null, null),
('Brazilian American Chamber of the Southeast', 'Trade association and cultural connector for Brazilian community in Atlanta. Networking, business support, cultural events.', 'Brazilian American chamber', (select id from categories where slug='community'), 'https://braziliansoutheast.com', '404-460-6190', '5680 New Northside Dr NW', 'Atlanta', 'GA', '30328', 33.9210, -84.4503, '{en,pt}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Center for Civil & Human Rights Education', 'Educational programs around civil and human rights, hosted at the National Center for Civil and Human Rights.', 'Civil rights education programs', (select id from categories where slug='community'), 'https://www.civilandhumanrights.org/learning', '678-999-8990', '100 Ivan Allen Jr Blvd', 'Atlanta', 'GA', '30313', 33.7639, -84.3933, '{en,es}', false, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Hellenic Cultural Society of Greater Atlanta', 'Greek American cultural organization. Greek language classes, cultural events, and Greek Festival.', 'Greek American cultural society', (select id from categories where slug='community'), 'https://www.hcsga.org', null, '2480 Clairmont Rd NE', 'Atlanta', 'GA', '30329', 33.8316, -84.3155, '{en,el}', true, true, 'Events-based', false, true, false, false, false, false, null, null, null, null),

-- ============================================================
-- PARKS
-- ============================================================
('Sweetwater Creek State Park', '2,549-acre state park 15 miles west of Atlanta. Civil War mill ruins, lake, hiking trails along Sweetwater Creek.', 'Top state park near Atlanta', (select id from categories where slug='parks'), 'https://gastateparks.org/SweetwaterCreek', '770-732-5871', '1750 Mt Vernon Rd', 'Lithia Springs', 'GA', '30122', 33.7521, -84.6266, '{en}', false, true, 'Daily 7a-9p (gate); $5 parking', true, true, true, false, true, true, 4.7, 6900, 'estimated', 'Beautiful trails along the creek with mill ruins. Crown jewel near Atlanta.'),
('Arabia Mountain National Heritage Area', '40,000-acre national heritage area east of Atlanta. Granite outcrops, lakes, PATH bike trails, and historic sites.', 'National heritage area, granite outcrops', (select id from categories where slug='parks'), 'https://www.arabiaalliance.org', '770-484-3060', '3787 Klondike Rd', 'Lithonia', 'GA', '30038', 33.6650, -84.1126, '{en}', true, true, 'Daily dawn-dusk', true, true, true, false, true, true, 4.8, 1700, 'estimated', null),
('Kennesaw Mountain National Battlefield Park', '2,965-acre Civil War battlefield with hiking trails, summit views of Atlanta, and visitor center.', 'Civil War battlefield + hiking', (select id from categories where slug='parks'), 'https://www.nps.gov/kemo', '770-427-4686', '900 Kennesaw Mountain Dr', 'Kennesaw', 'GA', '30152', 33.9866, -84.5790, '{en,es}', true, true, 'Daily 7a-9p (summer), 7a-7p (winter)', true, true, true, false, true, true, 4.8, 6500, 'estimated', null),
('Red Top Mountain State Park', '12,000-acre state park on Lake Allatoona. Beach, hiking, fishing, camping.', 'State park on Lake Allatoona', (select id from categories where slug='parks'), 'https://gastateparks.org/RedTopMountain', '770-975-0055', '50 Lodge Rd SE', 'Acworth', 'GA', '30121', 34.1554, -84.7048, '{en}', false, true, 'Daily 7a-10p; $5 parking', true, true, true, false, true, false, 4.7, 2700, 'estimated', null),
('Chastain Park', 'Atlanta''s largest city park (268 acres). Golf course, tennis center, amphitheater, swimming pool, horse park.', 'Atlanta''s largest city park', (select id from categories where slug='parks'), 'https://www.chastainpark.org', '404-817-6788', '4001 Powers Ferry Rd NW', 'Atlanta', 'GA', '30342', 33.8804, -84.3960, '{en,es}', true, true, 'Daily 6a-11p', true, true, true, false, true, false, 4.7, 4400, 'estimated', null),
('Brookhaven Park', 'Major Brookhaven city park with playgrounds, walking paths, dog park, and tennis courts.', 'Major Brookhaven city park', (select id from categories where slug='parks'), 'https://www.brookhavenga.gov/parks-recreation', '404-637-0500', '4158 Peachtree Rd NE', 'Brookhaven', 'GA', '30319', 33.8641, -84.3387, '{en,es}', true, true, 'Daily 6a-11p', true, true, true, false, true, false, 4.6, 1200, 'estimated', null),
('Smith-Gilbert Gardens', '16-acre botanical garden in Kennesaw. 3,000+ plant species; sculpture collection.', 'Botanical garden, Kennesaw', (select id from categories where slug='parks'), 'https://www.smithgilbertgardens.com', '770-919-0248', '2382 Pine Mountain Rd NW', 'Kennesaw', 'GA', '30152', 34.0264, -84.6055, '{en}', false, true, 'Tu-Su 9a-5p; $10 admission', false, true, false, false, true, false, 4.8, 950, 'estimated', null),
('Olmsted Linear Park', 'Historic park designed by Frederick Law Olmsted. Six landscaped segments along Ponce de Leon Avenue.', 'Historic Olmsted-designed park', (select id from categories where slug='parks'), 'https://atlantaolmstedpark.org', '404-475-8240', '1451 Ponce de Leon Ave NE', 'Atlanta', 'GA', '30307', 33.7727, -84.3403, '{en}', true, true, 'Daily dawn-dusk', true, true, true, false, true, false, 4.6, 280, 'estimated', null),
('Cascade Springs Nature Preserve', '120-acre nature preserve in southwest Atlanta. Forest trails, springs, Civil War history.', 'Nature preserve, southwest Atlanta', (select id from categories where slug='parks'), 'https://atlanta.gov', '404-549-7150', '2852 Cascade Rd SW', 'Atlanta', 'GA', '30311', 33.7234, -84.4898, '{en}', true, true, 'Daily dawn-dusk', true, true, true, false, true, false, 4.6, 540, 'estimated', null),
('Silver Comet Trail', '61.5-mile paved trail from Smyrna to the Alabama border. One of the longest paved rail-trails in the U.S.', '61-mile paved rail-trail', (select id from categories where slug='parks'), 'https://www.silvercometga.com', '770-528-8800', '4342 Floyd Rd SE', 'Mableton', 'GA', '30126', 33.8470, -84.5817, '{en,es}', true, true, '24/7', true, true, true, false, true, true, 4.8, 3400, 'estimated', null),
('Atlanta BeltLine - Eastside Trail', 'Most popular section of the BeltLine: 3-mile trail from Piedmont Park to Reynoldstown with restaurants, art, and Ponce City Market.', 'Iconic Atlanta urban trail', (select id from categories where slug='parks'), 'https://beltline.org', '404-477-3003', '1083 Ponce de Leon Ave NE', 'Atlanta', 'GA', '30306', 33.7740, -84.3661, '{en,es}', true, true, '24/7', true, true, true, false, true, true, 4.8, 2900, 'estimated', null),
('Atlanta BeltLine - Westside Trail', '3-mile section of the BeltLine through historic west Atlanta neighborhoods. Murals and access to Westview, Adair Park.', 'Westside section of the BeltLine', (select id from categories where slug='parks'), 'https://beltline.org', '404-477-3003', '1700 Lena St SW', 'Atlanta', 'GA', '30310', 33.7338, -84.4254, '{en,es}', true, true, '24/7', true, true, true, false, true, false, 4.7, 1100, 'estimated', null),
('Cochran Mill Park', '800-acre park in southwest Fulton with hiking trails, waterfalls, and historic mill ruins.', 'Hiking park with waterfalls, southwest Fulton', (select id from categories where slug='parks'), 'https://www.fultoncountyga.gov/inside-fulton-county/county-departments/parks-and-recreation/parks/cochran-mill-park', '404-612-5742', '6300 Cochran Mill Rd', 'Chattahoochee Hills', 'GA', '30268', 33.5781, -84.7349, '{en}', true, true, 'Daily 7a-7p', true, true, false, false, true, false, 4.6, 720, 'estimated', null),
('F.D. Roosevelt State Park', 'Largest Georgia state park (9,049 acres). Pine Mountain trails, Liberty Bell Pool, log cabins.', 'Largest Georgia state park', (select id from categories where slug='parks'), 'https://gastateparks.org/FDRoosevelt', '706-663-4858', '2970 GA-190', 'Pine Mountain', 'GA', '31822', 32.8338, -84.8307, '{en}', false, true, 'Daily 7a-10p; $5 parking', true, true, true, false, true, false, 4.7, 1900, 'estimated', null),
('Atlanta Memorial Park', '125-acre park in Buckhead with Bobby Jones Golf Course, tennis center, and walking trails.', 'Buckhead park with golf & tennis', (select id from categories where slug='parks'), 'https://atlanta.gov', '404-848-7220', '2026 Northside Dr NW', 'Atlanta', 'GA', '30305', 33.8221, -84.4150, '{en}', true, true, 'Daily 6a-11p', true, true, true, false, true, false, 4.5, 480, 'estimated', null),

-- ============================================================
-- LIBRARIES
-- ============================================================
('Decatur Library', 'Main DeKalb County Library branch. Strong collection, study spaces, and community programs.', 'Main DeKalb County Library, Decatur', (select id from categories where slug='libraries'), 'https://dekalblibrary.org', '404-370-3070', '215 Sycamore St', 'Decatur', 'GA', '30030', 33.7748, -84.2961, '{en,es,zh,vi}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p, Su 2p-6p', true, true, true, false, true, false, 4.6, 320, 'estimated', null),
('Brookhaven Library', 'Modern DeKalb County Library branch in Brookhaven.', 'DeKalb Library, Brookhaven', (select id from categories where slug='libraries'), 'https://dekalblibrary.org', '404-848-7140', '1242 N Druid Hills Rd', 'Brookhaven', 'GA', '30319', 33.8623, -84.3268, '{en,es,zh}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p, Su 2p-6p', true, true, true, false, true, false, 4.5, 240, 'estimated', null),
('Buckhead Branch Library', 'Atlanta-Fulton Public Library branch in Buckhead.', 'Buckhead Atlanta-Fulton Library', (select id from categories where slug='libraries'), 'https://afpls.org', '404-814-3500', '269 Buckhead Ave NE', 'Atlanta', 'GA', '30305', 33.8390, -84.3784, '{en,es}', true, true, 'M-Th 10a-8p, F 10a-6p, Sa 10a-5p', true, true, true, false, true, false, 4.4, 180, 'estimated', null),
('Sandy Springs Library', 'Modern Atlanta-Fulton Library branch in Sandy Springs city center.', 'Sandy Springs Library', (select id from categories where slug='libraries'), 'https://afpls.org', '404-303-6130', '395 Mt Vernon Hwy NE', 'Sandy Springs', 'GA', '30328', 33.9261, -84.3787, '{en,es,zh,ko}', true, true, 'M-Th 10a-8p, F 10a-6p, Sa 10a-5p', true, true, true, false, true, false, 4.5, 220, 'estimated', null),
('Roswell Public Library', 'Roswell branch of Atlanta-Fulton Library.', 'Roswell Library', (select id from categories where slug='libraries'), 'https://afpls.org', '770-640-3075', '115 Norcross St', 'Roswell', 'GA', '30075', 34.0250, -84.3598, '{en,es,ko}', true, true, 'M-Th 10a-8p, F 10a-6p, Sa 10a-5p', true, true, true, false, true, false, 4.5, 150, 'estimated', null),
('Alpharetta Library', 'Modern Atlanta-Fulton Library branch in Alpharetta.', 'Alpharetta Library', (select id from categories where slug='libraries'), 'https://afpls.org', '770-740-2425', '10 Park Plaza', 'Alpharetta', 'GA', '30009', 34.0750, -84.2939, '{en,es,zh,ko}', true, true, 'M-Th 10a-8p, F 10a-6p, Sa 10a-5p, Su 1p-5p', true, true, true, false, true, false, 4.7, 280, 'estimated', null),
('Switzer Library', 'Cobb County Public Library branch in Marietta. Strong children''s programming.', 'Cobb Library, Marietta', (select id from categories where slug='libraries'), 'https://cobbcounty.org/library', '770-528-2320', '266 Roswell St NE', 'Marietta', 'GA', '30060', 33.9547, -84.5450, '{en,es}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.5, 200, 'estimated', null),
('Mountain View Regional Library', 'Major Cobb County regional library branch.', 'Cobb regional library, Marietta', (select id from categories where slug='libraries'), 'https://cobbcounty.org/library', '770-509-2725', '3320 Sandy Plains Rd', 'Marietta', 'GA', '30066', 34.0049, -84.4661, '{en,es}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.6, 240, 'estimated', null),
('Suwanee Branch Library', 'Gwinnett County Public Library branch in Suwanee.', 'Gwinnett Library, Suwanee', (select id from categories where slug='libraries'), 'https://gwinnettpl.org', '770-271-8628', '361 Main St', 'Suwanee', 'GA', '30024', 34.0480, -84.0726, '{en,es,ko,zh}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.6, 220, 'estimated', null),
('Lawrenceville Branch Library', 'Gwinnett County Public Library branch in Lawrenceville.', 'Gwinnett Library, Lawrenceville', (select id from categories where slug='libraries'), 'https://gwinnettpl.org', '770-822-4522', '1001 Lawrenceville Hwy', 'Lawrenceville', 'GA', '30046', 33.9590, -83.9966, '{en,es,ko}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.5, 180, 'estimated', null),
('Norcross Branch Library', 'Gwinnett County Public Library branch in Norcross. Strong multilingual collection.', 'Gwinnett Library, Norcross', (select id from categories where slug='libraries'), 'https://gwinnettpl.org', '770-448-1115', '6025 Buford Hwy', 'Norcross', 'GA', '30071', 33.9405, -84.2138, '{en,es,ko,zh,vi}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.4, 160, 'estimated', null),
('Forest Park Branch Library', 'Clayton County Library branch.', 'Clayton Library, Forest Park', (select id from categories where slug='libraries'), 'https://www.claytonpl.org', '404-366-1851', '696 Main St', 'Forest Park', 'GA', '30297', 33.6235, -84.3712, '{en,es}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.4, 90, 'estimated', null),
('Headquarters Library Jonesboro', 'Main Clayton County Library branch.', 'Main Clayton County Library', (select id from categories where slug='libraries'), 'https://www.claytonpl.org', '770-473-3850', '865 Battle Creek Rd', 'Jonesboro', 'GA', '30236', 33.5247, -84.3588, '{en,es}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p, Su 1p-5p', true, true, true, false, true, false, 4.5, 130, 'estimated', null),
('Tucker-Reid H. Cofer Library', 'DeKalb County Library branch in Tucker. Newer building with strong programming.', 'DeKalb Library, Tucker', (select id from categories where slug='libraries'), 'https://dekalblibrary.org', '770-270-8234', '5234 LaVista Rd', 'Tucker', 'GA', '30084', 33.8552, -84.2218, '{en,es,zh,ko}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.6, 170, 'estimated', null),
('Sweetwater Valley Regional Library', 'Cobb County regional library in Powder Springs.', 'Cobb regional library, Powder Springs', (select id from categories where slug='libraries'), 'https://cobbcounty.org/library', '770-439-3600', '4915 Dallas Hwy', 'Powder Springs', 'GA', '30127', 33.9159, -84.7037, '{en,es}', true, true, 'M-Th 10a-8p, F-Sa 10a-6p', true, true, true, false, true, false, 4.5, 110, 'estimated', null),

-- ============================================================
-- FAMILY
-- ============================================================
('Buckhead YMCA', 'Buckhead YMCA branch (Carl E. Sanders Family YMCA). Pool, fitness, childcare, summer camps.', 'YMCA family branch, Buckhead', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/buckhead', '404-261-3111', '3692 Roswell Rd NE', 'Atlanta', 'GA', '30305', 33.8526, -84.3839, '{en,es}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.4, 460, 'estimated', null),
('Decatur YMCA', 'Decatur Family YMCA branch.', 'YMCA family branch, Decatur', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/decatur', '404-377-9622', '1100 Clairemont Ave', 'Decatur', 'GA', '30030', 33.7878, -84.2868, '{en,es}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.4, 380, 'estimated', null),
('East Lake Family YMCA', 'East Lake YMCA - serves East Lake/Edgewood/Kirkwood area.', 'YMCA family branch, East Lake', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/east-lake', '404-373-6561', '275 E Lake Blvd', 'Atlanta', 'GA', '30317', 33.7503, -84.3091, '{en,es}', false, true, 'M-F 5a-9p, Sa-Su 7a-6p', true, true, true, false, true, false, 4.5, 220, 'estimated', null),
('Northeast Atlanta YMCA', 'YMCA branch in Doraville/Chamblee area.', 'YMCA family branch, NE Atlanta', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/northeast-atlanta', '770-451-9622', '5600 Roberts Dr', 'Dunwoody', 'GA', '30338', 33.9495, -84.3127, '{en,es,ko,zh}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.4, 350, 'estimated', null),
('Cobb Family YMCA', 'Major Cobb County YMCA family branch.', 'YMCA family branch, Cobb', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/cobb', '770-422-9622', '1055 E Piedmont Rd NE', 'Marietta', 'GA', '30062', 33.9810, -84.4783, '{en,es}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.5, 470, 'estimated', null),
('JJ Biello Family YMCA', 'YMCA branch in Cherokee County (Woodstock).', 'YMCA family branch, Cherokee', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/jj-biello', '770-345-9622', '3200 Trickum Rd', 'Woodstock', 'GA', '30188', 34.0817, -84.5127, '{en,es}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.5, 320, 'estimated', null),
('Northwest YMCA', 'YMCA branch in Acworth.', 'YMCA family branch, Acworth', (select id from categories where slug='family'), 'https://ymcaatlanta.org/locations/northwest', '770-426-9622', '3010 Cobb Pkwy', 'Acworth', 'GA', '30101', 34.0531, -84.6728, '{en,es}', false, true, 'M-F 5a-10p, Sa-Su 7a-7p', true, true, true, false, true, false, 4.4, 290, 'estimated', null),
('Boys & Girls Club of Metro Atlanta - East Lake', 'Flagship East Lake B&G Club. After-school programs, sports, college prep.', 'B&G Club, East Lake (flagship)', (select id from categories where slug='family'), 'https://www.bgcma.org', '404-378-1100', '275 E Lake Blvd SE', 'Atlanta', 'GA', '30317', 33.7503, -84.3091, '{en,es}', true, true, 'M-F 2:30p-7p (school year), 7a-6p (summer)', false, false, true, false, true, true, 4.6, 90, 'estimated', null),
('Boys & Girls Club of Metro Atlanta - Cleveland Avenue', 'B&G Club serving south Atlanta youth.', 'B&G Club, Cleveland Ave', (select id from categories where slug='family'), 'https://www.bgcma.org', '404-768-1666', '1620 Cleveland Ave SW', 'Atlanta', 'GA', '30344', 33.7012, -84.4288, '{en,es}', true, true, 'M-F 2:30p-7p (school year), 7a-6p (summer)', false, false, true, false, true, false, 4.5, 60, 'estimated', null),
('Christian City', 'Faith-based foster care, group homes, and family services. Top reputation in metro Atlanta for child welfare.', 'Foster care & family services, Union City', (select id from categories where slug='family'), 'https://www.christiancity.org', '770-703-2636', '7290 Lester Rd', 'Union City', 'GA', '30291', 33.5867, -84.5677, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, false, 4.5, 170, 'estimated', null),
('Bethany Christian Services Atlanta', 'National faith-based adoption and foster care agency. Atlanta branch with strong reputation.', 'Adoption & foster care agency, Atlanta', (select id from categories where slug='family'), 'https://bethany.org', '404-419-6500', '6645 Peachtree Dunwoody Rd', 'Atlanta', 'GA', '30328', 33.9269, -84.3450, '{en,es,zh,ko}', false, true, 'M-F 8a-5p', false, false, false, true, true, false, 4.3, 80, 'estimated', null),
('Bright Horizons - Buckhead', 'High-end early childhood care chain. Buckhead location with strong NAEYC accreditation.', 'High-end early childhood care, Buckhead', (select id from categories where slug='family'), 'https://www.brighthorizons.com', '404-869-2200', '3344 Peachtree Rd NE', 'Atlanta', 'GA', '30326', 33.8470, -84.3675, '{en,es}', false, false, 'M-F 7a-6:30p', false, false, false, true, true, false, 4.5, 60, 'estimated', null),
('Primrose School of Brookhaven', 'Top-rated Primrose preschool franchise location.', 'Primrose preschool, Brookhaven', (select id from categories where slug='family'), 'https://www.primroseschools.com', '404-262-3300', '1110 Dresden Dr NE', 'Atlanta', 'GA', '30319', 33.8729, -84.3344, '{en,es}', false, false, 'M-F 6:30a-6:30p', false, false, false, true, true, false, 4.6, 70, 'estimated', null),
('The Goddard School - Buckhead', 'Top-rated preschool/childcare chain location.', 'Goddard preschool, Buckhead', (select id from categories where slug='family'), 'https://www.goddardschool.com', '404-869-2002', '3525 Roswell Rd NE', 'Atlanta', 'GA', '30305', 33.8466, -84.3812, '{en,es}', false, false, 'M-F 6:30a-6:30p', false, false, false, true, true, false, 4.7, 50, 'estimated', null),
('KinderCare - Sandy Springs', 'KinderCare early childhood center.', 'KinderCare, Sandy Springs', (select id from categories where slug='family'), 'https://www.kindercare.com', '404-256-9111', '6580 Roswell Rd NE', 'Sandy Springs', 'GA', '30328', 33.9311, -84.3741, '{en,es}', false, false, 'M-F 6:30a-6:30p', false, false, false, true, true, false, 4.4, 90, 'estimated', null),

-- ============================================================
-- LEGAL
-- ============================================================
('Atlanta Legal Aid Society - Cobb', 'Free civil legal aid for low-income Cobb County residents.', 'Free civil legal aid, Cobb County', (select id from categories where slug='legal'), 'https://atlantalegalaid.org', '770-528-2565', '30 South Park Square NE', 'Marietta', 'GA', '30060', 33.9525, -84.5505, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.3, 45, 'estimated', null),
('Atlanta Legal Aid Society - DeKalb', 'Free civil legal aid for low-income DeKalb County residents.', 'Free civil legal aid, DeKalb County', (select id from categories where slug='legal'), 'https://atlantalegalaid.org', '404-377-0701', '246 Sycamore St', 'Decatur', 'GA', '30030', 33.7745, -84.2972, '{en,es,zh,vi}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.4, 60, 'estimated', null),
('Atlanta Legal Aid Society - Gwinnett', 'Free civil legal aid for low-income Gwinnett County residents.', 'Free civil legal aid, Gwinnett County', (select id from categories where slug='legal'), 'https://atlantalegalaid.org', '678-376-4545', '324 W Pike St', 'Lawrenceville', 'GA', '30046', 33.9558, -83.9889, '{en,es,ko}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.3, 50, 'estimated', null),
('Atlanta Legal Aid Society - South Fulton', 'Free civil legal aid for low-income South Fulton residents.', 'Free civil legal aid, South Fulton', (select id from categories where slug='legal'), 'https://atlantalegalaid.org', '404-669-0233', '777 Cleveland Ave', 'Atlanta', 'GA', '30315', 33.7016, -84.4035, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, null, null, null, null),
('Catholic Charities Atlanta - Immigration Legal Services', 'BIA-accredited immigration legal services. Family-based petitions, DACA, naturalization, asylum.', 'BIA-accredited immigration legal aid', (select id from categories where slug='legal'), 'https://catholiccharitiesatlanta.org/services/immigration-legal-services', '678-222-3920', '2401 Lake Park Dr SE', 'Smyrna', 'GA', '30080', 33.8530, -84.5117, '{en,es,fr,vi,ar}', false, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.4, 200, 'estimated', null),
('World Relief Atlanta - Legal Services', 'Refugee and immigrant legal services from a major refugee resettlement organization.', 'Refugee/immigrant legal services', (select id from categories where slug='legal'), 'https://worldreliefatlanta.org/legal', '404-294-4352', '6627 James B Rivers Memorial Dr', 'Stone Mountain', 'GA', '30083', 33.8082, -84.1696, '{en,es,fr,ar,ne,bn,sw,am,ti,fa}', false, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.6, 90, 'estimated', null),
('Georgia Asylum and Immigration Network (GAIN)', 'Pro bono immigration legal services for asylum seekers and other vulnerable immigrants.', 'Pro bono asylum & immigration legal', (select id from categories where slug='legal'), 'https://www.georgiaasylum.org', '770-232-9536', '161 Peachtree Center Ave NE', 'Atlanta', 'GA', '30303', 33.7596, -84.3865, '{en,es,fr,ar}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.7, 70, 'estimated', null),
('Project South', 'Civil rights legal advocacy and community organizing. Strong focus on detained immigrants and Black communities.', 'Civil rights legal advocacy', (select id from categories where slug='legal'), 'https://projectsouth.org', '404-622-0602', '9 Gammon Ave SE', 'Atlanta', 'GA', '30315', 33.7259, -84.3781, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.7, 50, 'estimated', null),
('Pro Bono Partnership of Atlanta', 'Free legal services to nonprofits in metro Atlanta from volunteer corporate attorneys.', 'Free legal services for nonprofits', (select id from categories where slug='legal'), 'https://www.pbpatl.org', '404-407-5088', '999 Peachtree St NE', 'Atlanta', 'GA', '30309', 33.7831, -84.3854, '{en}', true, false, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Georgia Innocence Project', 'Investigates and litigates wrongful conviction cases in Georgia. Based at GSU College of Law.', 'Wrongful conviction legal advocacy', (select id from categories where slug='legal'), 'https://www.georgiainnocenceproject.org', '404-373-4433', '85 Park Pl NE', 'Atlanta', 'GA', '30303', 33.7551, -84.3855, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.8, 60, 'estimated', null),
('Center for Pan Asian Community Services - Legal', 'Immigration legal services for Asian immigrant communities. Multilingual.', 'Asian-language immigration legal aid', (select id from categories where slug='legal'), 'https://cpacs.org/legal', '770-936-0969', '5938 New Peachtree Rd', 'Doraville', 'GA', '30340', 33.9035, -84.2841, '{en,ko,vi,zh,bn,hi,ne}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.5, 70, 'estimated', null),

-- ============================================================
-- EMPLOYMENT
-- ============================================================
('WorkSource Atlanta-Fulton', 'Federally-funded workforce center. Job search, training vouchers, career counseling. Free to use.', 'Free workforce center, Atlanta-Fulton', (select id from categories where slug='employment'), 'https://worksourceatlanta.org', '404-330-6500', '818 Pollard Blvd SW', 'Atlanta', 'GA', '30315', 33.7350, -84.4032, '{en,es}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 4.0, 90, 'estimated', null),
('WorkSource DeKalb', 'Federally-funded DeKalb County workforce center.', 'Free workforce center, DeKalb', (select id from categories where slug='employment'), 'https://www.dekalbcountyga.gov/worksource-dekalb', '404-687-3400', '774 Jordan Ln Bldg 4', 'Decatur', 'GA', '30033', 33.8123, -84.2871, '{en,es}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 3.9, 80, 'estimated', null),
('WorkSource Cobb', 'Cobb County workforce center for job seekers.', 'Free workforce center, Cobb', (select id from categories where slug='employment'), 'https://www.cobbworks.org', '770-528-4300', '463 Commerce Park Dr', 'Marietta', 'GA', '30060', 33.9494, -84.5562, '{en,es}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 3.9, 60, 'estimated', null),
('WorkSource Gwinnett', 'Gwinnett County workforce center.', 'Free workforce center, Gwinnett', (select id from categories where slug='employment'), 'https://www.gwinnettcounty.com', '770-995-6483', '750 South Perry St', 'Lawrenceville', 'GA', '30046', 33.9512, -83.9890, '{en,es,ko}', true, true, 'M-F 8a-5p', true, false, false, true, true, true, 3.8, 50, 'estimated', null),
('Year Up Atlanta', 'Free 1-year intensive training + paid corporate internship for young adults 18-29. ~85% job/college outcome.', 'Free year-long training + internship', (select id from categories where slug='employment'), 'https://www.yearup.org/locations/atlanta', '470-535-3211', '50 Hurt Plaza SE', 'Atlanta', 'GA', '30303', 33.7560, -84.3865, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.6, 80, 'estimated', null),
('Generation USA Atlanta', 'Free 12-week intensive bootcamps in IT, healthcare, and digital marketing. Strong job placement.', 'Free intensive job training bootcamps', (select id from categories where slug='employment'), 'https://usa.generation.org/atlanta', null, '999 Peachtree St NE', 'Atlanta', 'GA', '30309', 33.7831, -84.3854, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.5, 50, 'estimated', null),
('NPower Atlanta', 'Free IT training program for young adults and veterans. Industry-recognized certs and job placement.', 'Free IT training, young adults & vets', (select id from categories where slug='employment'), 'https://www.npower.org/locations/atlanta', '404-806-1255', '848 Spring St NW', 'Atlanta', 'GA', '30308', 33.7833, -84.3879, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.5, 40, 'estimated', null),
('Goodwill Career Center - Howell Mill', 'Goodwill''s flagship Atlanta career center. Free job search help, resume coaching, training referrals.', 'Free job search & training, Howell Mill', (select id from categories where slug='employment'), 'https://goodwillng.org', '404-486-8400', '2201 Glenwood Ave SE', 'Atlanta', 'GA', '30316', 33.7349, -84.3434, '{en,es}', true, true, 'M-F 8a-5p', true, false, false, true, true, false, 4.0, 60, 'estimated', null),
('Goodwill Career Center - Decatur', 'Goodwill career center serving DeKalb.', 'Free career center, Decatur', (select id from categories where slug='employment'), 'https://goodwillng.org', '404-486-7100', '4990 Memorial Dr', 'Stone Mountain', 'GA', '30083', 33.7693, -84.1947, '{en,es}', true, true, 'M-F 8a-5p', true, false, false, true, true, false, 4.0, 50, 'estimated', null),
('Atlanta CareerRise', 'Workforce development partnership focused on connecting low-income job seekers to career-track employment.', 'Career-track workforce development', (select id from categories where slug='employment'), 'https://www.atlantacareerrise.org', '404-527-5700', '50 Hurt Plaza SE', 'Atlanta', 'GA', '30303', 33.7560, -84.3865, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Refugee Career Hub', 'Career services specifically for refugees and SIVs. Resume help, interview prep, employer connections.', 'Career services for refugees', (select id from categories where slug='employment'), 'https://www.refugeecareerhub.org', '404-484-9888', '2300 Henderson Mill Rd', 'Atlanta', 'GA', '30345', 33.8851, -84.2799, '{en,es,ar,fa,ne,bn,sw,am,ti}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, null, null, null, null),

-- ============================================================
-- FINANCIAL
-- ============================================================
('Delta Community Credit Union HQ', 'Largest credit union in Georgia (450K+ members). Lower fees and better rates than most banks.', 'Largest credit union in Georgia', (select id from categories where slug='financial'), 'https://www.deltacommunitycu.com', '800-544-3328', '3250 Riverwood Pkwy SE', 'Atlanta', 'GA', '30339', 33.8743, -84.4655, '{en,es}', false, true, 'M-F 9a-5p, Sa 9a-1p', true, true, false, true, true, true, 4.6, 1900, 'estimated', null),
('Georgia''s Own Credit Union HQ', 'Major Georgia credit union with 200K+ members. Strong rates and member-focused service.', 'Major Georgia credit union', (select id from categories where slug='financial'), 'https://www.georgiasown.org', '800-533-2062', '100 Peachtree St NE', 'Atlanta', 'GA', '30303', 33.7589, -84.3878, '{en,es}', false, true, 'M-F 9a-5p, Sa 9a-1p', true, true, false, true, true, true, 4.5, 1100, 'estimated', null),
('Atlanta Postal Credit Union', 'Credit union originally serving postal workers, now open to anyone living/working in metro Atlanta.', 'Member-owned credit union', (select id from categories where slug='financial'), 'https://www.apcu.com', '800-849-8431', '3900 Crown Rd SW', 'Atlanta', 'GA', '30380', 33.6603, -84.4517, '{en,es}', false, true, 'M-F 9a-5p, Sa 9a-1p', true, true, false, true, true, false, 4.5, 480, 'estimated', null),
('Operation HOPE HQ', 'National financial empowerment nonprofit headquartered in Atlanta. Free financial coaching, credit-building, small business.', 'Free financial coaching & credit help', (select id from categories where slug='financial'), 'https://operationhope.org', '404-941-2900', '191 Peachtree St NE', 'Atlanta', 'GA', '30303', 33.7596, -84.3878, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.7, 120, 'estimated', null),
('LiftFund Atlanta', 'Microlender providing small business loans + free coaching to entrepreneurs who can''t access traditional bank credit.', 'Microloans for small business', (select id from categories where slug='financial'), 'https://www.liftfund.com', '888-215-2373', '34 Peachtree St NW', 'Atlanta', 'GA', '30303', 33.7558, -84.3911, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, true, 4.5, 80, 'estimated', null),
('Access to Capital for Entrepreneurs (ACE)', 'CDFI providing loans + technical assistance to underserved entrepreneurs in Georgia.', 'Small business loans, underserved entrepreneurs', (select id from categories where slug='financial'), 'https://aceloans.org', '678-335-5600', '600 W Peachtree St NW', 'Atlanta', 'GA', '30308', 33.7723, -84.3884, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('SCORE Atlanta', 'Free mentoring + workshops for small business owners. National volunteer-driven program.', 'Free small business mentoring', (select id from categories where slug='financial'), 'https://atlanta.score.org', '404-331-0121', '233 Peachtree St NE Ste 1900', 'Atlanta', 'GA', '30303', 33.7595, -84.3878, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, 4.7, 90, 'estimated', null),
('Center for Working Families', 'Workforce + financial coaching for low-income workers and job seekers. Combines training with wraparound support.', 'Workforce + financial coaching', (select id from categories where slug='financial'), 'https://www.thecwf.org', '404-486-9913', '477 Windsor St SW', 'Atlanta', 'GA', '30312', 33.7375, -84.3941, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('AARP Tax-Aide - Decatur Library', 'Free tax preparation by trained AARP volunteers. Walk-in or appointment, no income limit.', 'Free tax prep by AARP volunteers', (select id from categories where slug='financial'), 'https://www.aarp.org/money/taxes/aarp_taxaide', '888-687-2277', '215 Sycamore St', 'Decatur', 'GA', '30030', 33.7748, -84.2961, '{en,es}', true, true, 'Feb-Apr, Tu/Th/Sa', true, true, false, false, true, false, null, null, null, null),
('Atlanta Prosperity Campaign / United Way VITA', 'Free IRS-certified tax prep for households earning <$60K. United Way coordinates 30+ Atlanta sites.', 'Free tax prep for low-income households', (select id from categories where slug='financial'), 'https://www.unitedwayatlanta.org', '866-211-9966', '40 Courtland St NE', 'Atlanta', 'GA', '30303', 33.7556, -84.3848, '{en,es}', true, true, 'Feb-Apr, varies by site', true, true, true, true, true, true, null, null, null, null),
('United Way 2-1-1 Atlanta', 'Free 24/7 multilingual helpline connecting callers with health, housing, food, financial, and crisis resources.', '24/7 free multilingual help line', (select id from categories where slug='financial'), 'https://www.unitedwayatlanta.org/our-work/211', '866-211-9966', '40 Courtland St NE', 'Atlanta', 'GA', '30303', 33.7556, -84.3848, '{en,es,fr,vi,zh,ko,ar,sw,am}', true, true, '24/7', false, true, true, true, true, true, 4.6, 80, 'estimated', null),

-- ============================================================
-- HOUSING
-- ============================================================
('Atlanta Mission - The Shepherd''s Inn', 'Major Atlanta men''s emergency shelter and recovery program. Beds, meals, case management.', 'Men''s shelter + recovery program', (select id from categories where slug='housing'), 'https://atlantamission.org', '404-588-4000', '156 Pryor St SW', 'Atlanta', 'GA', '30303', 33.7494, -84.3917, '{en,es}', true, true, '24/7', true, true, true, true, true, true, 4.4, 250, 'estimated', null),
('Atlanta Mission - My Sister''s House', 'Atlanta Mission women''s and children''s shelter. 24/7 emergency beds + recovery program.', 'Women''s & children''s shelter', (select id from categories where slug='housing'), 'https://atlantamission.org', '404-588-4006', '921 Howell Mill Rd NW', 'Atlanta', 'GA', '30318', 33.7793, -84.4137, '{en,es}', true, true, '24/7', true, true, true, true, true, true, 4.5, 130, 'estimated', null),
('The Salvation Army of Metro Atlanta - Bell Memorial', 'Major emergency shelter with men''s, women''s, and family beds + meal services.', 'Major emergency shelter, downtown', (select id from categories where slug='housing'), 'https://www.salvationarmyatlanta.org', '404-486-2900', '460 Marietta St NW', 'Atlanta', 'GA', '30313', 33.7634, -84.4046, '{en,es}', true, true, '24/7', true, true, true, true, true, true, 4.0, 200, 'estimated', null),
('Mary Hall Freedom House', 'Long-term residential recovery program for women + children. Top reputation for substance use treatment.', 'Women''s long-term recovery housing', (select id from categories where slug='housing'), 'https://maryhallfreedomhouse.org', '770-642-5500', '8995 Roswell Rd', 'Sandy Springs', 'GA', '30350', 33.9886, -84.3414, '{en,es}', true, true, 'M-F 8a-5p (intake)', false, false, false, true, true, true, 4.7, 90, 'estimated', null),
('Solomon''s Temple', 'Faith-based Atlanta men''s shelter and recovery program.', 'Men''s shelter + recovery, faith-based', (select id from categories where slug='housing'), 'https://www.solomonstemple.org', '404-688-1654', '561 Marietta Blvd NW', 'Atlanta', 'GA', '30318', 33.7757, -84.4191, '{en,es}', true, true, '24/7', true, true, true, true, true, false, 4.5, 70, 'estimated', null),
('Covenant House Georgia', 'Crisis shelter and long-term services for homeless youth ages 18-21. National network with strong reputation.', 'Homeless youth shelter (18-21)', (select id from categories where slug='housing'), 'https://www.covenanthousega.org', '404-589-0163', '1559 Johnson Rd NW', 'Atlanta', 'GA', '30318', 33.7781, -84.4324, '{en,es}', true, true, '24/7', true, true, true, true, true, true, 4.6, 80, 'estimated', null),
('CHRIS 180', 'Mental health, foster care, and homeless youth services across Atlanta. Top-rated multi-service nonprofit.', 'Youth mental health & homeless services', (select id from categories where slug='housing'), 'https://chris180.org', '404-486-9034', '1017 Fayetteville Rd SE', 'Atlanta', 'GA', '30316', 33.7268, -84.3504, '{en,es}', true, true, 'M-F 8:30a-5:30p', false, false, false, true, true, true, 4.6, 60, 'estimated', null),
('City of Refuge', 'Multi-service nonprofit serving homeless families with shelter, workforce training, and education.', 'Homeless family services + workforce', (select id from categories where slug='housing'), 'https://cityofrefugeatl.org', '404-874-2241', '1300 Joseph E Boone Blvd NW', 'Atlanta', 'GA', '30314', 33.7731, -84.4239, '{en,es}', true, true, 'M-F 8a-5p', false, false, false, true, true, true, 4.6, 110, 'estimated', null),
('Habitat ReStore - Atlanta (Northside Dr)', 'Habitat for Humanity discount home improvement store. Donated furniture, appliances, building materials.', 'Discount home improvement store', (select id from categories where slug='housing'), 'https://www.atlantahabitat.org/restore', '404-223-5181', '271 Chester Ave SE', 'Atlanta', 'GA', '30316', 33.7357, -84.3667, '{en,es}', false, true, 'Tu-Sa 9a-6p', true, true, false, false, true, false, 4.4, 480, 'estimated', null),
('Habitat ReStore - Decatur', 'Habitat for Humanity discount home goods store, DeKalb branch.', 'Habitat ReStore, Decatur', (select id from categories where slug='housing'), 'https://www.atlantahabitat.org/restore', '404-378-1188', '2548 Lawrenceville Hwy', 'Decatur', 'GA', '30033', 33.8126, -84.2700, '{en,es}', false, true, 'Tu-Sa 9a-6p', true, true, false, false, true, false, 4.5, 320, 'estimated', null),

-- ============================================================
-- TRANSPORTATION
-- ============================================================
('MARTA Buckhead Station', 'Major Red Line MARTA station serving Buckhead. Connects to bus routes throughout north Atlanta.', 'Red Line MARTA, Buckhead', (select id from categories where slug='transportation'), 'https://www.itsmarta.com', '404-848-5000', '3360 Peachtree Rd NE', 'Atlanta', 'GA', '30326', 33.8473, -84.3667, '{en,es}', false, true, 'M-F 4:45a-1a, Sa-Su 6a-1a', true, true, true, false, true, false, 4.0, 380, 'estimated', null),
('MARTA Lindbergh Center Station', 'Major Red/Gold Line transfer station. Connects to bus routes serving Buckhead, Brookhaven, Lindbergh.', 'Major Red/Gold Line MARTA transfer', (select id from categories where slug='transportation'), 'https://www.itsmarta.com', '404-848-5000', '2424 Piedmont Rd NE', 'Atlanta', 'GA', '30324', 33.8237, -84.3691, '{en,es}', false, true, 'M-F 4:45a-1a, Sa-Su 6a-1a', true, true, true, false, true, false, 3.8, 320, 'estimated', null),
('MARTA Five Points Station', 'Central downtown MARTA station — main transfer hub for Red, Gold, Blue, and Green lines.', 'Central downtown MARTA transfer hub', (select id from categories where slug='transportation'), 'https://www.itsmarta.com', '404-848-5000', '30 Alabama St SW', 'Atlanta', 'GA', '30303', 33.7536, -84.3920, '{en,es}', false, true, 'M-F 4:45a-1a, Sa-Su 6a-1a', true, true, true, false, true, true, 3.7, 920, 'estimated', null),
('MARTA Peachtree Center Station', 'Downtown MARTA station serving Peachtree Center, GSU, Centennial Olympic Park area.', 'Downtown Red/Gold MARTA, Peachtree Center', (select id from categories where slug='transportation'), 'https://www.itsmarta.com', '404-848-5000', '216 Peachtree St NE', 'Atlanta', 'GA', '30303', 33.7596, -84.3879, '{en,es}', false, true, 'M-F 4:45a-1a, Sa-Su 6a-1a', true, true, true, false, true, false, 3.9, 350, 'estimated', null),
('MARTA Decatur Station', 'East line MARTA station in Decatur Square. Walking distance to DeKalb library, restaurants, shops.', 'Blue Line MARTA, Decatur Square', (select id from categories where slug='transportation'), 'https://www.itsmarta.com', '404-848-5000', '400 Church St', 'Decatur', 'GA', '30030', 33.7745, -84.2972, '{en,es}', false, true, 'M-F 4:45a-1a, Sa-Su 6a-1a', true, true, true, false, true, false, 4.2, 220, 'estimated', null),
('DDS - Marietta', 'Georgia Department of Driver Services office in Marietta (Cobb County).', 'Driver services, Cobb County', (select id from categories where slug='transportation'), 'https://dds.georgia.gov', '678-413-8400', '1605 County Services Pkwy SW', 'Marietta', 'GA', '30008', 33.9038, -84.5727, '{en,es}', false, true, 'Tu-F 8a-6p, Sa 8a-12:30p', false, true, true, false, true, false, 3.5, 280, 'estimated', null),
('DDS - Norcross', 'Georgia Department of Driver Services office in Norcross (Gwinnett County).', 'Driver services, Gwinnett County', (select id from categories where slug='transportation'), 'https://dds.georgia.gov', '678-413-8400', '5610 Singleton Rd', 'Norcross', 'GA', '30093', 33.9281, -84.2026, '{en,es,ko}', false, true, 'Tu-F 8a-6p, Sa 8a-12:30p', false, true, true, false, true, false, 3.6, 350, 'estimated', null),
('DDS - Sandy Springs', 'Georgia Department of Driver Services office in Sandy Springs.', 'Driver services, Sandy Springs', (select id from categories where slug='transportation'), 'https://dds.georgia.gov', '678-413-8400', '8610 Roswell Rd Ste 700', 'Sandy Springs', 'GA', '30350', 33.9989, -84.3429, '{en,es}', false, true, 'Tu-F 8a-6p, Sa 8a-12:30p', false, true, true, false, true, false, 3.5, 290, 'estimated', null),
('DDS - Forest Park', 'Georgia Department of Driver Services office in Forest Park (Clayton County).', 'Driver services, Clayton County', (select id from categories where slug='transportation'), 'https://dds.georgia.gov', '678-413-8400', '1090 Main St', 'Forest Park', 'GA', '30297', 33.6258, -84.3686, '{en,es}', false, true, 'Tu-F 8a-6p, Sa 8a-12:30p', false, true, true, false, true, false, 3.4, 240, 'estimated', null),
('DDS - Conyers', 'Georgia Department of Driver Services office in Conyers (Rockdale County).', 'Driver services, Rockdale County', (select id from categories where slug='transportation'), 'https://dds.georgia.gov', '678-413-8400', '1380 Dogwood Dr SE', 'Conyers', 'GA', '30013', 33.6502, -84.0152, '{en,es}', false, true, 'Tu-F 8a-6p, Sa 8a-12:30p', false, true, true, false, true, false, 3.6, 180, 'estimated', null),

-- ============================================================
-- WOMEN'S
-- ============================================================
('Partnership Against Domestic Violence (PADV)', 'Atlanta''s largest domestic violence agency. 24/7 hotline, two emergency shelters, legal advocacy, counseling.', 'Largest DV agency in Atlanta', (select id from categories where slug='womens'), 'https://padv.org', '404-873-1766', '787 Spring St NW', 'Atlanta', 'GA', '30308', 33.7779, -84.3893, '{en,es}', true, true, '24/7 hotline, M-F 9a-5p office', false, false, true, true, true, true, 4.7, 110, 'estimated', 'Saved my life. Compassionate, professional, and effective from intake to recovery.'),
('Caminar Latino', 'First and largest comprehensive DV program serving Latino families in Atlanta. Bilingual/bicultural staff.', 'Bilingual DV program for Latino families', (select id from categories where slug='womens'), 'https://caminarlatino.org', '404-413-1965', '2900 Chamblee Tucker Rd', 'Atlanta', 'GA', '30341', 33.8849, -84.2713, '{es,en}', true, true, 'M-F 9a-5p; 24/7 crisis line 404-413-1965', false, false, true, true, true, true, 4.8, 60, 'estimated', null),
('Tapestri', 'DV and human trafficking services for immigrant women. Multilingual, refugee-focused.', 'DV/trafficking services for immigrant women', (select id from categories where slug='womens'), 'https://tapestri.org', '404-299-2185', '3939 Lavista Rd', 'Tucker', 'GA', '30084', 33.8497, -84.2189, '{en,es,fr,ar,bn,vi,fa,ne}', true, true, 'M-F 9a-5p; 24/7 crisis 404-299-2185', false, false, true, true, true, true, 4.7, 50, 'estimated', null),
('International Women''s House', 'Long-term shelter and services for immigrant and refugee women fleeing domestic violence.', 'Long-term DV shelter for immigrant women', (select id from categories where slug='womens'), 'https://www.internationalwomenshouse.org', '770-413-5557', null, 'Decatur', 'GA', '30030', 33.7748, -84.2961, '{en,es,fr,ar,sw,am,ti,ne}', true, true, 'M-F 9a-5p; 24/7 emergency line', false, false, true, true, true, true, 4.7, 40, 'estimated', null),
('Center for Family Resources', 'Cobb County''s primary domestic violence agency. Shelter, hotline, counseling, court advocacy.', 'Cobb County''s primary DV agency', (select id from categories where slug='womens'), 'https://thecfr.org', '770-428-2601', '995 Roswell St NE', 'Marietta', 'GA', '30060', 33.9598, -84.5325, '{en,es}', true, true, 'M-F 9a-5p; 24/7 hotline 770-427-3390', false, false, true, true, true, true, 4.6, 70, 'estimated', null),
('Tubman House Atlanta', 'Survivor-led organization for women exiting trafficking and exploitation. Housing + holistic services.', 'Survivor-led trafficking/exit support', (select id from categories where slug='womens'), 'https://www.thetubmanhouse.org', '404-865-9117', null, 'Atlanta', 'GA', '30315', 33.7398, -84.3776, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),
('Wellspring Living', 'Long-term residential program for women + minor girls escaping sex trafficking. National model.', 'Long-term anti-trafficking residential', (select id from categories where slug='womens'), 'https://wellspringliving.org', '404-948-3478', '480 John Wesley Dobbs Ave NE', 'Atlanta', 'GA', '30312', 33.7595, -84.3771, '{en,es}', true, true, 'M-F 9a-5p; intake by phone', false, false, false, true, true, true, 4.8, 60, 'estimated', null),
('Crittenton Children''s Center', 'Residential and outpatient services for at-risk young women ages 12-21, including teen mothers.', 'Residential services, at-risk young women', (select id from categories where slug='womens'), 'https://www.crittentonchildrenscenter.org', null, '1900 The Exchange SE', 'Atlanta', 'GA', '30339', 33.8929, -84.4773, '{en,es}', true, true, 'M-F 9a-5p', false, false, false, true, true, false, null, null, null, null),

-- ============================================================
-- EMERGENCY
-- ============================================================
('988 Suicide & Crisis Lifeline', '24/7 free national hotline for anyone in suicidal crisis or emotional distress. Call or text 988.', '24/7 national suicide/crisis hotline', (select id from categories where slug='emergency'), 'https://988lifeline.org', '988', null, null, 'GA', null, 33.7488, -84.3880, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.6, 1300, 'estimated', null),
('Crisis Text Line', 'Free 24/7 text-based crisis support. Text HOME to 741741 to connect with a trained Crisis Counselor.', '24/7 free text-based crisis support', (select id from categories where slug='emergency'), 'https://www.crisistextline.org', '741741', null, null, 'GA', null, 33.7488, -84.3880, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.7, 800, 'estimated', null),
('National Domestic Violence Hotline', '24/7 free national hotline. Confidential support, safety planning, and local resource referrals.', '24/7 national DV hotline', (select id from categories where slug='emergency'), 'https://www.thehotline.org', '800-799-7233', null, null, 'GA', null, 33.7488, -84.3880, '{en,es,fr,zh,vi,ar,ko,ru,fa,sw,ne,bn,hi,pt,tl,ti,am}', true, true, '24/7', false, true, true, true, true, true, 4.6, 700, 'estimated', null),
('RAINN National Sexual Assault Hotline', '24/7 free confidential hotline for survivors of sexual assault and their loved ones.', '24/7 national sexual assault hotline', (select id from categories where slug='emergency'), 'https://www.rainn.org', '800-656-4673', null, null, 'GA', null, 33.7488, -84.3880, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.7, 500, 'estimated', null),
('The Trevor Project', '24/7 free crisis intervention and suicide prevention for LGBTQ+ youth under 25. Call, text, or chat.', '24/7 LGBTQ+ youth crisis support', (select id from categories where slug='emergency'), 'https://www.thetrevorproject.org', '866-488-7386', null, null, 'GA', null, 33.7488, -84.3880, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.8, 400, 'estimated', null),
('American Red Cross of Georgia', 'Disaster response, shelter activation, blood services, and emergency preparedness for the state.', 'Disaster response & emergency services', (select id from categories where slug='emergency'), 'https://www.redcross.org/local/georgia.html', '800-733-2767', '1955 Monroe Dr NE', 'Atlanta', 'GA', '30324', 33.8048, -84.3690, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.5, 380, 'estimated', null),
('Salvation Army Atlanta - Disaster Services', 'Disaster relief, mass care, and emergency assistance for metro Atlanta.', 'Disaster relief & emergency assistance', (select id from categories where slug='emergency'), 'https://www.salvationarmyatlanta.org', '404-486-2900', '1000 Center Pl', 'Norcross', 'GA', '30093', 33.9384, -84.2017, '{en,es}', true, true, '24/7', false, true, true, true, true, false, null, null, null, null),
('Georgia Crisis & Access Line', 'Georgia''s 24/7 free hotline for mental health, substance use, and developmental disability crisis.', 'Georgia 24/7 mental health crisis line', (select id from categories where slug='emergency'), 'https://mygcal.com', '800-715-4225', null, null, 'GA', null, 33.7488, -84.3880, '{en,es}', true, true, '24/7', false, true, true, true, true, true, 4.4, 220, 'estimated', null)

on conflict do nothing;